// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Accepts an incoming call
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> AcceptCallAsync(int callId = default, CallProtocol protocol = default)
    {

           using var activity =  StartCallActivity("AcceptCallAsync", typeof(AcceptCall).FullName ?? "AcceptCallAsync");

           try
           {
             return client.AcceptCallAsync(callId, protocol);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd