// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Adds tasks to a checklist in a message
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> AddChecklistTasksAsync(long chatId = default, long messageId = default, InputChecklistTask[] tasks = default)
    {

           using var activity =  StartCallActivity("AddChecklistTasksAsync", typeof(AddChecklistTasks).FullName ?? "AddChecklistTasksAsync");

           try
           {
             return client.AddChecklistTasksAsync(chatId, messageId, tasks);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd