// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Adds a user to the contact list or edits an existing contact by their user identifier
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> AddContactAsync(long userId = default, ImportedContact contact = default, bool sharePhoneNumber = default)
    {

           using var activity =  StartCallActivity("AddContactAsync", typeof(AddContact).FullName ?? "AddContactAsync");

           try
           {
             return client.AddContactAsync(userId, contact, sharePhoneNumber);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd