// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Adds a chat to a chat list. A chat can't be simultaneously in Main and Archive chat lists, so it is automatically removed from another one if needed
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> AddChatToListAsync(long chatId = default, ChatList chatList = default)
    {

           using var activity =  StartCallActivity("AddChatToListAsync", typeof(AddChatToList).FullName ?? "AddChatToListAsync");

           try
           {
             return client.AddChatToListAsync(chatId, chatList);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd