// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Adds a custom server language pack to the list of installed language packs in current localization target. Can be called before authorization
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> AddCustomServerLanguagePackAsync(string languagePackId = default)
    {

           using var activity =  StartCallActivity("AddCustomServerLanguagePackAsync", typeof(AddCustomServerLanguagePack).FullName ?? "AddCustomServerLanguagePackAsync");

           try
           {
             return client.AddCustomServerLanguagePackAsync(languagePackId);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd