// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Adds a chat folder by an invite link
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> AddChatFolderByInviteLinkAsync(string inviteLink = default, long[] chatIds = default)
    {

           using var activity =  StartCallActivity("AddChatFolderByInviteLinkAsync", typeof(AddChatFolderByInviteLink).FullName ?? "AddChatFolderByInviteLinkAsync");

           try
           {
             return client.AddChatFolderByInviteLinkAsync(inviteLink, chatIds);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd