// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Adds multiple new members to a chat; requires can_invite_users member right. Currently, this method is only available for supergroups and channels.
    /// This method can't be used to join a chat. Members can't be added to a channel if it has more than 200 members. Returns information about members that weren't added
    /// </summary>
    public Task<TdLib.TdApi.Objects.FailedToAddMembers> AddChatMembersAsync(long chatId = default, long[] userIds = default)
    {

           using var activity =  StartCallActivity("AddChatMembersAsync", typeof(AddChatMembers).FullName ?? "AddChatMembersAsync");

           try
           {
             return client.AddChatMembersAsync(chatId, userIds);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd