// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Adds a new member to a chat; requires can_invite_users member right. Members can't be added to private or secret chats. Returns information about members that weren't added
    /// </summary>
    public Task<TdLib.TdApi.Objects.FailedToAddMembers> AddChatMemberAsync(long chatId = default, long userId = default, int forwardLimit = default)
    {

           using var activity =  StartCallActivity("AddChatMemberAsync", typeof(AddChatMember).FullName ?? "AddChatMemberAsync");

           try
           {
             return client.AddChatMemberAsync(chatId, userId, forwardLimit);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd