// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Adds a file from a message to the list of file downloads. Download progress and completion of the download will be notified through updateFile updates.
    /// If message database is used, the list of file downloads is persistent across application restarts. The downloading is independent of download using downloadFile, i.e. it continues if downloadFile is canceled or is used to download a part of the file
    /// </summary>
    public Task<TdLib.TdApi.Objects.File> AddFileToDownloadsAsync(int fileId = default, long chatId = default, long messageId = default, int priority = default)
    {

           using var activity =  StartCallActivity("AddFileToDownloadsAsync", typeof(AddFileToDownloads).FullName ?? "AddFileToDownloadsAsync");

           try
           {
             return client.AddFileToDownloadsAsync(fileId, chatId, messageId, priority);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd