// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Adds a message to TDLib internal log. Can be called synchronously
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> AddLogMessageAsync(int verbosityLevel = default, string text = default)
    {

           using var activity =  StartCallActivity("AddLogMessageAsync", typeof(AddLogMessage).FullName ?? "AddLogMessageAsync");

           try
           {
             return client.AddLogMessageAsync(verbosityLevel, text);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd