// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Adds a passkey allowed to be used for the login by the current user and returns the added passkey. Call getPasskeyParameters to get parameters for creating of the passkey
    /// </summary>
    public Task<TdLib.TdApi.Objects.Passkey> AddLoginPasskeyAsync(string clientData = default, byte[] attestationObject = default)
    {

           using var activity =  StartCallActivity("AddLoginPasskeyAsync", typeof(AddLoginPasskey).FullName ?? "AddLoginPasskeyAsync");

           try
           {
             return client.AddLoginPasskeyAsync(clientData, attestationObject);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd