// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Adds pending paid reaction in a live story group call. Can't be used in live stories posted by the current user.
    /// Call commitPendingLiveStoryReactions or removePendingLiveStoryReactions to actually send all pending reactions when the undo timer is over or abort the sending
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> AddPendingLiveStoryReactionAsync(int groupCallId = default, long starCount = default)
    {

           using var activity =  StartCallActivity("AddPendingLiveStoryReactionAsync", typeof(AddPendingLiveStoryReaction).FullName ?? "AddPendingLiveStoryReactionAsync");

           try
           {
             return client.AddPendingLiveStoryReactionAsync(groupCallId, starCount);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd