// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Adds a proxy server for network requests. Can be called before authorization
    /// </summary>
    public Task<TdLib.TdApi.Objects.AddedProxy> AddProxyAsync(Proxy proxy = default, bool enable = default)
    {

           using var activity =  StartCallActivity("AddProxyAsync", typeof(AddProxy).FullName ?? "AddProxyAsync");

           try
           {
             return client.AddProxyAsync(proxy, enable);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd