// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Adds an audio file to the beginning of the profile audio files of the current user
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> AddProfileAudioAsync(int fileId = default)
    {

           using var activity =  StartCallActivity("AddProfileAudioAsync", typeof(AddProfileAudio).FullName ?? "AddProfileAudioAsync");

           try
           {
             return client.AddProfileAudioAsync(fileId);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd