// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Adds a message to a quick reply shortcut. If shortcut doesn't exist and there are less than getOption("quick_reply_shortcut_count_max") shortcuts, then a new shortcut is created.
    /// The shortcut must not contain more than getOption("quick_reply_shortcut_message_count_max") messages after adding the new message. Returns the added message
    /// </summary>
    public Task<TdLib.TdApi.Objects.QuickReplyMessage> AddQuickReplyShortcutMessageAsync(string shortcutName = default, long replyToMessageId = default, InputMessageContent inputMessageContent = default)
    {

           using var activity =  StartCallActivity("AddQuickReplyShortcutMessageAsync", typeof(AddQuickReplyShortcutMessage).FullName ?? "AddQuickReplyShortcutMessageAsync");

           try
           {
             return client.AddQuickReplyShortcutMessageAsync(shortcutName, replyToMessageId, inputMessageContent);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd