// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Manually adds a new sticker to the list of recently used stickers. The new sticker is added to the top of the list. If the sticker was already in the list, it is removed from the list first.
    /// Only stickers belonging to a sticker set or in WEBP or WEBM format can be added to this list. Emoji stickers can't be added to recent stickers
    /// </summary>
    public Task<TdLib.TdApi.Objects.Stickers> AddRecentStickerAsync(bool isAttached = default, InputFile sticker = default)
    {

           using var activity =  StartCallActivity("AddRecentStickerAsync", typeof(AddRecentSticker).FullName ?? "AddRecentStickerAsync");

           try
           {
             return client.AddRecentStickerAsync(isAttached, sticker);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd