// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Adds a chat to the list of recently found chats. The chat is added to the beginning of the list. If the chat is already in the list, it will be removed from the list first
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> AddRecentlyFoundChatAsync(long chatId = default)
    {

           using var activity =  StartCallActivity("AddRecentlyFoundChatAsync", typeof(AddRecentlyFoundChat).FullName ?? "AddRecentlyFoundChatAsync");

           try
           {
             return client.AddRecentlyFoundChatAsync(chatId);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd