// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Adds a new sticker to a set
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> AddStickerToSetAsync(long userId = default, string name = default, InputSticker sticker = default)
    {

           using var activity =  StartCallActivity("AddStickerToSetAsync", typeof(AddStickerToSet).FullName ?? "AddStickerToSetAsync");

           try
           {
             return client.AddStickerToSetAsync(userId, name, sticker);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd