// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Manually adds a new animation to the list of saved animations. The new animation is added to the beginning of the list. If the animation was already in the list, it is removed first.
    /// Only non-secret video animations with MIME type "video/mp4" can be added to the list
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> AddSavedAnimationAsync(InputFile animation = default)
    {

           using var activity =  StartCallActivity("AddSavedAnimationAsync", typeof(AddSavedAnimation).FullName ?? "AddSavedAnimationAsync");

           try
           {
             return client.AddSavedAnimationAsync(animation);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd