// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Allows the specified bot to send messages to the user
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> AllowBotToSendMessagesAsync(long botUserId = default)
    {

           using var activity =  StartCallActivity("AllowBotToSendMessagesAsync", typeof(AllowBotToSendMessages).FullName ?? "AllowBotToSendMessagesAsync");

           try
           {
             return client.AllowBotToSendMessagesAsync(botUserId);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd