// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Sets the result of interaction with a Web App and sends corresponding message on behalf of the user to the chat from which the query originated; for bots only
    /// </summary>
    public Task<TdLib.TdApi.Objects.SentWebAppMessage> AnswerWebAppQueryAsync(string webAppQueryId = default, InputInlineQueryResult result = default)
    {

           using var activity =  StartCallActivity("AnswerWebAppQueryAsync", typeof(AnswerWebAppQuery).FullName ?? "AnswerWebAppQueryAsync");

           try
           {
             return client.AnswerWebAppQueryAsync(webAppQueryId, result);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd