// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Informs server about an in-store purchase. For official applications only
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> AssignStoreTransactionAsync(StoreTransaction transaction = default, StorePaymentPurpose purpose = default)
    {

           using var activity =  StartCallActivity("AssignStoreTransactionAsync", typeof(AssignStoreTransaction).FullName ?? "AssignStoreTransactionAsync");

           try
           {
             return client.AssignStoreTransactionAsync(transaction, purpose);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd