// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Bans users from a group call not bound to a chat; requires groupCall.is_owned. Only the owner of the group call can invite the banned users back
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> BanGroupCallParticipantsAsync(int groupCallId = default, long[] userIds = default)
    {

           using var activity =  StartCallActivity("BanGroupCallParticipantsAsync", typeof(BanGroupCallParticipants).FullName ?? "BanGroupCallParticipantsAsync");

           try
           {
             return client.BanGroupCallParticipantsAsync(groupCallId, userIds);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd