// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Boosts a chat and returns the list of available chat boost slots for the current user after the boost
    /// </summary>
    public Task<TdLib.TdApi.Objects.ChatBoostSlots> BoostChatAsync(long chatId = default, int[] slotIds = default)
    {

           using var activity =  StartCallActivity("BoostChatAsync", typeof(BoostChat).FullName ?? "BoostChatAsync");

           try
           {
             return client.BoostChatAsync(chatId, slotIds);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd