// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Checks whether the specified bot can send messages to the user. Returns a 404 error if can't and the access can be granted by call to allowBotToSendMessages
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> CanBotSendMessagesAsync(long botUserId = default)
    {

           using var activity =  StartCallActivity("CanBotSendMessagesAsync", typeof(CanBotSendMessages).FullName ?? "CanBotSendMessagesAsync");

           try
           {
             return client.CanBotSendMessagesAsync(botUserId);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd