// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Cancels verification of the 2-step verification recovery email address
    /// </summary>
    public Task<TdLib.TdApi.Objects.PasswordState> CancelRecoveryEmailAddressVerificationAsync()
    {

           using var activity =  StartCallActivity("CancelRecoveryEmailAddressVerificationAsync", typeof(CancelRecoveryEmailAddressVerification).FullName ?? "CancelRecoveryEmailAddressVerificationAsync");

           try
           {
             return client.CancelRecoveryEmailAddressVerificationAsync();
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd