// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Cancels reset of 2-step verification password. The method can be called if passwordState.pending_reset_date &gt; 0
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> CancelPasswordResetAsync()
    {

           using var activity =  StartCallActivity("CancelPasswordResetAsync", typeof(CancelPasswordReset).FullName ?? "CancelPasswordResetAsync");

           try
           {
             return client.CancelPasswordResetAsync();
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd