// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Checks whether an in-store purchase is possible. Must be called before any in-store purchase. For official applications only
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> CanPurchaseFromStoreAsync(StorePaymentPurpose purpose = default)
    {

           using var activity =  StartCallActivity("CanPurchaseFromStoreAsync", typeof(CanPurchaseFromStore).FullName ?? "CanPurchaseFromStoreAsync");

           try
           {
             return client.CanPurchaseFromStoreAsync(purpose);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd