// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Checks whether the current session can be used to transfer a chat ownership to another user
    /// </summary>
    public Task<TdLib.TdApi.Objects.CanTransferOwnershipResult> CanTransferOwnershipAsync()
    {

           using var activity =  StartCallActivity("CanTransferOwnershipAsync", typeof(CanTransferOwnership).FullName ?? "CanTransferOwnershipAsync");

           try
           {
             return client.CanTransferOwnershipAsync();
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd