// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns information about a Telegram Premium gift code
    /// </summary>
    public Task<TdLib.TdApi.Objects.PremiumGiftCodeInfo> CheckPremiumGiftCodeAsync(string code = default)
    {

           using var activity =  StartCallActivity("CheckPremiumGiftCodeAsync", typeof(CheckPremiumGiftCode).FullName ?? "CheckPremiumGiftCodeAsync");

           try
           {
             return client.CheckPremiumGiftCodeAsync(code);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd