// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Checks a passkey to log in to the corresponding account. Call getAuthenticationPasskeyParameters to get parameters for the passkey. Works only when the current authorization state is
    /// authorizationStateWaitPhoneNumber or authorizationStateWaitOtherDeviceConfirmation, or if there is no pending authentication query and the current authorization state is
    /// authorizationStateWaitPremiumPurchase, authorizationStateWaitEmailAddress, authorizationStateWaitEmailCode, authorizationStateWaitCode, authorizationStateWaitRegistration, or authorizationStateWaitPassword
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> CheckAuthenticationPasskeyAsync(string credentialId = default, string clientData = default, byte[] authenticatorData = default, byte[] signature = default, byte[] userHandle = default)
    {

           using var activity =  StartCallActivity("CheckAuthenticationPasskeyAsync", typeof(CheckAuthenticationPasskey).FullName ?? "CheckAuthenticationPasskeyAsync");

           try
           {
             return client.CheckAuthenticationPasskeyAsync(credentialId, clientData, authenticatorData, signature, userHandle);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd