// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Checks whether a file can be downloaded and saved locally by Web App request
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> CheckWebAppFileDownloadAsync(long botUserId = default, string fileName = default, string url = default)
    {

           using var activity =  StartCallActivity("CheckWebAppFileDownloadAsync", typeof(CheckWebAppFileDownload).FullName ?? "CheckWebAppFileDownloadAsync");

           try
           {
             return client.CheckWebAppFileDownloadAsync(botUserId, fileName, url);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd