// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Checks the 2-step verification recovery email address verification code
    /// </summary>
    public Task<TdLib.TdApi.Objects.PasswordState> CheckRecoveryEmailAddressCodeAsync(string code = default)
    {

           using var activity =  StartCallActivity("CheckRecoveryEmailAddressCodeAsync", typeof(CheckRecoveryEmailAddressCode).FullName ?? "CheckRecoveryEmailAddressCodeAsync");

           try
           {
             return client.CheckRecoveryEmailAddressCodeAsync(code);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd