// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Checks the validity of an invite link for a chat and returns information about the corresponding chat
    /// </summary>
    public Task<TdLib.TdApi.Objects.ChatInviteLinkInfo> CheckChatInviteLinkAsync(string inviteLink = default)
    {

           using var activity =  StartCallActivity("CheckChatInviteLinkAsync", typeof(CheckChatInviteLink).FullName ?? "CheckChatInviteLinkAsync");

           try
           {
             return client.CheckChatInviteLinkAsync(inviteLink);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd