// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Checks the authentication code. Works only when the current authorization state is authorizationStateWaitCode
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> CheckAuthenticationCodeAsync(string code = default)
    {

           using var activity =  StartCallActivity("CheckAuthenticationCodeAsync", typeof(CheckAuthenticationCode).FullName ?? "CheckAuthenticationCodeAsync");

           try
           {
             return client.CheckAuthenticationCodeAsync(code);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd