// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Checks the login email address authentication
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> CheckLoginEmailAddressCodeAsync(EmailAddressAuthentication code = default)
    {

           using var activity =  StartCallActivity("CheckLoginEmailAddressCodeAsync", typeof(CheckLoginEmailAddressCode).FullName ?? "CheckLoginEmailAddressCodeAsync");

           try
           {
             return client.CheckLoginEmailAddressCodeAsync(code);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd