// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Checks whether a username can be set for a chat
    /// </summary>
    public Task<TdLib.TdApi.Objects.CheckChatUsernameResult> CheckChatUsernameAsync(long chatId = default, string username = default)
    {

           using var activity =  StartCallActivity("CheckChatUsernameAsync", typeof(CheckChatUsername).FullName ?? "CheckChatUsernameAsync");

           try
           {
             return client.CheckChatUsernameAsync(chatId, username);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd