// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Checks whether an in-store purchase of Telegram Premium is possible before authorization. Works only when the current authorization state is authorizationStateWaitPremiumPurchase
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> CheckAuthenticationPremiumPurchaseAsync(string currency = default, long amount = default)
    {

           using var activity =  StartCallActivity("CheckAuthenticationPremiumPurchaseAsync", typeof(CheckAuthenticationPremiumPurchase).FullName ?? "CheckAuthenticationPremiumPurchaseAsync");

           try
           {
             return client.CheckAuthenticationPremiumPurchaseAsync(currency, amount);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd