// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Checks the authentication token of a bot; to log in as a bot. Works only when the current authorization state is authorizationStateWaitPhoneNumber. Can be used instead of setAuthenticationPhoneNumber and checkAuthenticationCode to log in
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> CheckAuthenticationBotTokenAsync(string token = default)
    {

           using var activity =  StartCallActivity("CheckAuthenticationBotTokenAsync", typeof(CheckAuthenticationBotToken).FullName ?? "CheckAuthenticationBotTokenAsync");

           try
           {
             return client.CheckAuthenticationBotTokenAsync(token);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd