// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Checks the authentication code and completes the request for which the code was sent if appropriate
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> CheckPhoneNumberCodeAsync(string code = default)
    {

           using var activity =  StartCallActivity("CheckPhoneNumberCodeAsync", typeof(CheckPhoneNumberCode).FullName ?? "CheckPhoneNumberCodeAsync");

           try
           {
             return client.CheckPhoneNumberCodeAsync(code);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd