// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Checks validness of a name for a quick reply shortcut. Can be called synchronously
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> CheckQuickReplyShortcutNameAsync(string name = default)
    {

           using var activity =  StartCallActivity("CheckQuickReplyShortcutNameAsync", typeof(CheckQuickReplyShortcutName).FullName ?? "CheckQuickReplyShortcutNameAsync");

           try
           {
             return client.CheckQuickReplyShortcutNameAsync(name);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd