// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Clears the list of all autosave settings exceptions. The method is guaranteed to work only after at least one call to getAutosaveSettings
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> ClearAutosaveSettingsExceptionsAsync()
    {

           using var activity =  StartCallActivity("ClearAutosaveSettingsExceptionsAsync", typeof(ClearAutosaveSettingsExceptions).FullName ?? "ClearAutosaveSettingsExceptionsAsync");

           try
           {
             return client.ClearAutosaveSettingsExceptionsAsync();
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd