// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Removes potentially dangerous characters from the name of a file. Returns an empty string on failure. Can be called synchronously
    /// </summary>
    public Task<TdLib.TdApi.Objects.Text> CleanFileNameAsync(string fileName = default)
    {

           using var activity =  StartCallActivity("CleanFileNameAsync", typeof(CleanFileName).FullName ?? "CleanFileNameAsync");

           try
           {
             return client.CleanFileNameAsync(fileName);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd