// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Clears the list of recently used reactions
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> ClearRecentReactionsAsync()
    {

           using var activity =  StartCallActivity("ClearRecentReactionsAsync", typeof(ClearRecentReactions).FullName ?? "ClearRecentReactionsAsync");

           try
           {
             return client.ClearRecentReactionsAsync();
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd