// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Informs TDLib that a message with an animated emoji was clicked by the user. Returns a big animated sticker to be played or a 404 error if usual animation needs to be played
    /// </summary>
    public Task<TdLib.TdApi.Objects.Sticker> ClickAnimatedEmojiMessageAsync(long chatId = default, long messageId = default)
    {

           using var activity =  StartCallActivity("ClickAnimatedEmojiMessageAsync", typeof(ClickAnimatedEmojiMessage).FullName ?? "ClickAnimatedEmojiMessageAsync");

           try
           {
             return client.ClickAnimatedEmojiMessageAsync(chatId, messageId);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd