// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Informs TDLib that the user clicked Premium subscription button on the Premium features screen
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> ClickPremiumSubscriptionButtonAsync()
    {

           using var activity =  StartCallActivity("ClickPremiumSubscriptionButtonAsync", typeof(ClickPremiumSubscriptionButton).FullName ?? "ClickPremiumSubscriptionButtonAsync");

           try
           {
             return client.ClickPremiumSubscriptionButtonAsync();
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd