// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Informs TDLib that the user opened the sponsored chat via the button, the name, the chat photo, a mention in the sponsored message text, or the media in the sponsored message
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> ClickChatSponsoredMessageAsync(long chatId = default, long messageId = default, bool isMediaClick = default, bool fromFullscreen = default)
    {

           using var activity =  StartCallActivity("ClickChatSponsoredMessageAsync", typeof(ClickChatSponsoredMessage).FullName ?? "ClickChatSponsoredMessageAsync");

           try
           {
             return client.ClickChatSponsoredMessageAsync(chatId, messageId, isMediaClick, fromFullscreen);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd