// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Informs TDLib that the user clicked a video message advertisement
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> ClickVideoMessageAdvertisementAsync(long advertisementUniqueId = default)
    {

           using var activity =  StartCallActivity("ClickVideoMessageAdvertisementAsync", typeof(ClickVideoMessageAdvertisement).FullName ?? "ClickVideoMessageAdvertisementAsync");

           try
           {
             return client.ClickVideoMessageAdvertisementAsync(advertisementUniqueId);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd