// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Informs TDLib that a previously opened Web App was closed
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> CloseWebAppAsync(long webAppLaunchId = default)
    {

           using var activity =  StartCallActivity("CloseWebAppAsync", typeof(CloseWebApp).FullName ?? "CloseWebAppAsync");

           try
           {
             return client.CloseWebAppAsync(webAppLaunchId);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd