// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Closes a secret chat, effectively transferring its state to secretChatStateClosed
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> CloseSecretChatAsync(int secretChatId = default)
    {

           using var activity =  StartCallActivity("CloseSecretChatAsync", typeof(CloseSecretChat).FullName ?? "CloseSecretChatAsync");

           try
           {
             return client.CloseSecretChatAsync(secretChatId);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd