// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Informs TDLib that a story is closed by the user
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> CloseStoryAsync(long storyPosterChatId = default, int storyId = default)
    {

           using var activity =  StartCallActivity("CloseStoryAsync", typeof(CloseStory).FullName ?? "CloseStoryAsync");

           try
           {
             return client.CloseStoryAsync(storyPosterChatId, storyId);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd