// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Confirms an unconfirmed session of the current user from another device
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> ConfirmSessionAsync(long sessionId = default)
    {

           using var activity =  StartCallActivity("ConfirmSessionAsync", typeof(ConfirmSession).FullName ?? "ConfirmSessionAsync");

           try
           {
             return client.ConfirmSessionAsync(sessionId);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd