// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Confirms QR code authentication on another device. Returns created session on success
    /// </summary>
    public Task<TdLib.TdApi.Objects.Session> ConfirmQrCodeAuthenticationAsync(string link = default)
    {

           using var activity =  StartCallActivity("ConfirmQrCodeAuthenticationAsync", typeof(ConfirmQrCodeAuthentication).FullName ?? "ConfirmQrCodeAuthenticationAsync");

           try
           {
             return client.ConfirmQrCodeAuthenticationAsync(link);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd