// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Crafts a new gift from other gifts that will be permanently lost
    /// </summary>
    public Task<TdLib.TdApi.Objects.CraftGiftResult> CraftGiftAsync(string[] receivedGiftIds = default)
    {

           using var activity =  StartCallActivity("CraftGiftAsync", typeof(CraftGift).FullName ?? "CraftGiftAsync");

           try
           {
             return client.CraftGiftAsync(receivedGiftIds);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd