// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns an existing chat corresponding to a known supergroup or channel
    /// </summary>
    public Task<TdLib.TdApi.Objects.Chat> CreateSupergroupChatAsync(long supergroupId = default, bool force = default)
    {

           using var activity =  StartCallActivity("CreateSupergroupChatAsync", typeof(CreateSupergroupChat).FullName ?? "CreateSupergroupChatAsync");

           try
           {
             return client.CreateSupergroupChatAsync(supergroupId, force);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd