// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Creates a video chat (a group call bound to a chat); for basic groups, supergroups and channels only; requires can_manage_video_chats administrator right
    /// </summary>
    public Task<TdLib.TdApi.Objects.GroupCallId> CreateVideoChatAsync(long chatId = default, string title = default, int startDate = default, bool isRtmpStream = default)
    {

           using var activity =  StartCallActivity("CreateVideoChatAsync", typeof(CreateVideoChat).FullName ?? "CreateVideoChatAsync");

           try
           {
             return client.CreateVideoChatAsync(chatId, title, startDate, isRtmpStream);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd