// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns an existing chat corresponding to a known basic group
    /// </summary>
    public Task<TdLib.TdApi.Objects.Chat> CreateBasicGroupChatAsync(long basicGroupId = default, bool force = default)
    {

           using var activity =  StartCallActivity("CreateBasicGroupChatAsync", typeof(CreateBasicGroupChat).FullName ?? "CreateBasicGroupChatAsync");

           try
           {
             return client.CreateBasicGroupChatAsync(basicGroupId, force);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd