// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Creates a new supergroup or channel and sends a corresponding messageSupergroupChatCreate. Returns the newly created chat
    /// </summary>
    public Task<TdLib.TdApi.Objects.Chat> CreateNewSupergroupChatAsync(string title = default, bool isForum = default, bool isChannel = default, string description = default, ChatLocation location = default, int messageAutoDeleteTime = default, bool forImport = default)
    {

           using var activity =  StartCallActivity("CreateNewSupergroupChatAsync", typeof(CreateNewSupergroupChat).FullName ?? "CreateNewSupergroupChatAsync");

           try
           {
             return client.CreateNewSupergroupChatAsync(title, isForum, isChannel, description, location, messageAutoDeleteTime, forImport);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd