// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Creates a new group call that isn't bound to a chat
    /// </summary>
    public Task<TdLib.TdApi.Objects.GroupCallInfo> CreateGroupCallAsync(GroupCallJoinParameters joinParameters = default)
    {

           using var activity =  StartCallActivity("CreateGroupCallAsync", typeof(CreateGroupCall).FullName ?? "CreateGroupCallAsync");

           try
           {
             return client.CreateGroupCallAsync(joinParameters);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd