// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Creates a new subscription invite link for a channel chat. Requires can_invite_users right in the chat
    /// </summary>
    public Task<TdLib.TdApi.Objects.ChatInviteLink> CreateChatSubscriptionInviteLinkAsync(long chatId = default, string name = default, StarSubscriptionPricing subscriptionPricing = default)
    {

           using var activity =  StartCallActivity("CreateChatSubscriptionInviteLinkAsync", typeof(CreateChatSubscriptionInviteLink).FullName ?? "CreateChatSubscriptionInviteLinkAsync");

           try
           {
             return client.CreateChatSubscriptionInviteLinkAsync(chatId, name, subscriptionPricing);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd