// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Creates a new temporary password for processing payments
    /// </summary>
    public Task<TdLib.TdApi.Objects.TemporaryPasswordState> CreateTemporaryPasswordAsync(string password = default, int validFor = default)
    {

           using var activity =  StartCallActivity("CreateTemporaryPasswordAsync", typeof(CreateTemporaryPassword).FullName ?? "CreateTemporaryPasswordAsync");

           try
           {
             return client.CreateTemporaryPasswordAsync(password, validFor);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd