// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns an existing chat corresponding to a given user
    /// </summary>
    public Task<TdLib.TdApi.Objects.Chat> CreatePrivateChatAsync(long userId = default, bool force = default)
    {

           using var activity =  StartCallActivity("CreatePrivateChatAsync", typeof(CreatePrivateChat).FullName ?? "CreatePrivateChatAsync");

           try
           {
             return client.CreatePrivateChatAsync(userId, force);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd