// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Creates a new basic group and sends a corresponding messageBasicGroupChatCreate. Returns information about the newly created chat
    /// </summary>
    public Task<TdLib.TdApi.Objects.CreatedBasicGroupChat> CreateNewBasicGroupChatAsync(long[] userIds = default, string title = default, int messageAutoDeleteTime = default)
    {

           using var activity =  StartCallActivity("CreateNewBasicGroupChatAsync", typeof(CreateNewBasicGroupChat).FullName ?? "CreateNewBasicGroupChatAsync");

           try
           {
             return client.CreateNewBasicGroupChatAsync(userIds, title, messageAutoDeleteTime);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd