// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Creates new chat folder. Returns information about the created chat folder. There can be up to getOption("chat_folder_count_max") chat folders, but the limit can be increased with Telegram Premium
    /// </summary>
    public Task<TdLib.TdApi.Objects.ChatFolderInfo> CreateChatFolderAsync(ChatFolder folder = default)
    {

           using var activity =  StartCallActivity("CreateChatFolderAsync", typeof(CreateChatFolder).FullName ?? "CreateChatFolderAsync");

           try
           {
             return client.CreateChatFolderAsync(folder);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd