// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Creates a new invite link for a chat. Available for basic groups, supergroups, and channels. Requires administrator privileges and can_invite_users right in the chat
    /// </summary>
    public Task<TdLib.TdApi.Objects.ChatInviteLink> CreateChatInviteLinkAsync(long chatId = default, string name = default, int expirationDate = default, int memberLimit = default, bool createsJoinRequest = default)
    {

           using var activity =  StartCallActivity("CreateChatInviteLinkAsync", typeof(CreateChatInviteLink).FullName ?? "CreateChatInviteLinkAsync");

           try
           {
             return client.CreateChatInviteLinkAsync(chatId, name, expirationDate, memberLimit, createsJoinRequest);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd