// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Creates an album of stories; requires can_edit_stories administrator right for supergroup and channel chats
    /// </summary>
    public Task<TdLib.TdApi.Objects.StoryAlbum> CreateStoryAlbumAsync(long storyPosterChatId = default, string name = default, int[] storyIds = default)
    {

           using var activity =  StartCallActivity("CreateStoryAlbumAsync", typeof(CreateStoryAlbum).FullName ?? "CreateStoryAlbumAsync");

           try
           {
             return client.CreateStoryAlbumAsync(storyPosterChatId, name, storyIds);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd