// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Creates a new invite link for a chat folder. A link can be created for a chat folder if it has only pinned and included chats
    /// </summary>
    public Task<TdLib.TdApi.Objects.ChatFolderInviteLink> CreateChatFolderInviteLinkAsync(int chatFolderId = default, string name = default, long[] chatIds = default)
    {

           using var activity =  StartCallActivity("CreateChatFolderInviteLinkAsync", typeof(CreateChatFolderInviteLink).FullName ?? "CreateChatFolderInviteLinkAsync");

           try
           {
             return client.CreateChatFolderInviteLinkAsync(chatFolderId, name, chatIds);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd