// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Declines a suggested post in a channel direct messages chat
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> DeclineSuggestedPostAsync(long chatId = default, long messageId = default, string comment = default)
    {

           using var activity =  StartCallActivity("DeclineSuggestedPostAsync", typeof(DeclineSuggestedPost).FullName ?? "DeclineSuggestedPostAsync");

           try
           {
             return client.DeclineSuggestedPostAsync(chatId, messageId, comment);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd