// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Decrypts group call data received by tgcalls
    /// </summary>
    public Task<TdLib.TdApi.Objects.Data> DecryptGroupCallDataAsync(int groupCallId = default, MessageSender participantId = default, GroupCallDataChannel dataChannel = default, byte[] data = default)
    {

           using var activity =  StartCallActivity("DecryptGroupCallDataAsync", typeof(DecryptGroupCallData).FullName ?? "DecryptGroupCallDataAsync");

           try
           {
             return client.DecryptGroupCallDataAsync(groupCallId, participantId, dataChannel, data);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd