// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Deletes messages on behalf of a business account; for bots only
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> DeleteBusinessMessagesAsync(string businessConnectionId = default, long[] messageIds = default)
    {

           using var activity =  StartCallActivity("DeleteBusinessMessagesAsync", typeof(DeleteBusinessMessages).FullName ?? "DeleteBusinessMessagesAsync");

           try
           {
             return client.DeleteBusinessMessagesAsync(businessConnectionId, messageIds);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd