// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Deletes a quick reply shortcut
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> DeleteQuickReplyShortcutAsync(int shortcutId = default)
    {

           using var activity =  StartCallActivity("DeleteQuickReplyShortcutAsync", typeof(DeleteQuickReplyShortcut).FullName ?? "DeleteQuickReplyShortcutAsync");

           try
           {
             return client.DeleteQuickReplyShortcutAsync(shortcutId);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd