// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Deletes saved credentials for all payment provider bots
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> DeleteSavedCredentialsAsync()
    {

           using var activity =  StartCallActivity("DeleteSavedCredentialsAsync", typeof(DeleteSavedCredentials).FullName ?? "DeleteSavedCredentialsAsync");

           try
           {
             return client.DeleteSavedCredentialsAsync();
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd