// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Deletes a gift collection. If the collection is owned by a channel chat, then requires can_post_messages administrator right in the channel chat
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> DeleteGiftCollectionAsync(MessageSender ownerId = default, int collectionId = default)
    {

           using var activity =  StartCallActivity("DeleteGiftCollectionAsync", typeof(DeleteGiftCollection).FullName ?? "DeleteGiftCollectionAsync");

           try
           {
             return client.DeleteGiftCollectionAsync(ownerId, collectionId);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd