// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Deletes revoked chat invite links. Requires administrator privileges and can_invite_users right in the chat for own links and owner privileges for other links
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> DeleteRevokedChatInviteLinkAsync(long chatId = default, string inviteLink = default)
    {

           using var activity =  StartCallActivity("DeleteRevokedChatInviteLinkAsync", typeof(DeleteRevokedChatInviteLink).FullName ?? "DeleteRevokedChatInviteLinkAsync");

           try
           {
             return client.DeleteRevokedChatInviteLinkAsync(chatId, inviteLink);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd