// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Deletes all messages sent by the specified message sender in a chat. Supported only for supergroups; requires can_delete_messages administrator right
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> DeleteChatMessagesBySenderAsync(long chatId = default, MessageSender senderId = default)
    {

           using var activity =  StartCallActivity("DeleteChatMessagesBySenderAsync", typeof(DeleteChatMessagesBySender).FullName ?? "DeleteChatMessagesBySenderAsync");

           try
           {
             return client.DeleteChatMessagesBySenderAsync(chatId, senderId);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd