// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Deletes a chat along with all messages in the corresponding chat for all chat members. For group chats this will release the usernames and remove all members.
    /// Use the field chat.can_be_deleted_for_all_users to find whether the method can be applied to the chat
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> DeleteChatAsync(long chatId = default)
    {

           using var activity =  StartCallActivity("DeleteChatAsync", typeof(DeleteChat).FullName ?? "DeleteChatAsync");

           try
           {
             return client.DeleteChatAsync(chatId);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd