// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Deletes all messages in the chat. Use chat.can_be_deleted_only_for_self and chat.can_be_deleted_for_all_users fields to find whether and how the method can be applied to the chat
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> DeleteChatHistoryAsync(long chatId = default, bool removeFromChatList = default, bool revoke = default)
    {

           using var activity =  StartCallActivity("DeleteChatHistoryAsync", typeof(DeleteChatHistory).FullName ?? "DeleteChatHistoryAsync");

           try
           {
             return client.DeleteChatHistoryAsync(chatId, removeFromChatList, revoke);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd