// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Deletes the default reply markup from a chat. Must be called after a one-time keyboard or a replyMarkupForceReply reply markup has been used or dismissed
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> DeleteChatReplyMarkupAsync(long chatId = default, long messageId = default)
    {

           using var activity =  StartCallActivity("DeleteChatReplyMarkupAsync", typeof(DeleteChatReplyMarkup).FullName ?? "DeleteChatReplyMarkupAsync");

           try
           {
             return client.DeleteChatReplyMarkupAsync(chatId, messageId);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd