// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Deletes saved order information
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> DeleteSavedOrderInfoAsync()
    {

           using var activity =  StartCallActivity("DeleteSavedOrderInfoAsync", typeof(DeleteSavedOrderInfo).FullName ?? "DeleteSavedOrderInfoAsync");

           try
           {
             return client.DeleteSavedOrderInfoAsync();
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd