// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Deletes all messages between the specified dates in the topic in a channel direct messages chat administered by the current user. Messages sent in the last 30 seconds will not be deleted
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> DeleteDirectMessagesChatTopicMessagesByDateAsync(long chatId = default, long topicId = default, int minDate = default, int maxDate = default)
    {

           using var activity =  StartCallActivity("DeleteDirectMessagesChatTopicMessagesByDateAsync", typeof(DeleteDirectMessagesChatTopicMessagesByDate).FullName ?? "DeleteDirectMessagesChatTopicMessagesByDateAsync");

           try
           {
             return client.DeleteDirectMessagesChatTopicMessagesByDateAsync(chatId, topicId, minDate, maxDate);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd