// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Deletes all messages between the specified dates in a chat. Supported only for private chats and basic groups. Messages sent in the last 30 seconds will not be deleted
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> DeleteChatMessagesByDateAsync(long chatId = default, int minDate = default, int maxDate = default, bool revoke = default)
    {

           using var activity =  StartCallActivity("DeleteChatMessagesByDateAsync", typeof(DeleteChatMessagesByDate).FullName ?? "DeleteChatMessagesByDateAsync");

           try
           {
             return client.DeleteChatMessagesByDateAsync(chatId, minDate, maxDate, revoke);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd