// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Deletes all messages in the topic in a channel direct messages chat administered by the current user
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> DeleteDirectMessagesChatTopicHistoryAsync(long chatId = default, long topicId = default)
    {

           using var activity =  StartCallActivity("DeleteDirectMessagesChatTopicHistoryAsync", typeof(DeleteDirectMessagesChatTopicHistory).FullName ?? "DeleteDirectMessagesChatTopicHistoryAsync");

           try
           {
             return client.DeleteDirectMessagesChatTopicHistoryAsync(chatId, topicId);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd