// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Deletes background in a specific chat
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> DeleteChatBackgroundAsync(long chatId = default, bool restorePrevious = default)
    {

           using var activity =  StartCallActivity("DeleteChatBackgroundAsync", typeof(DeleteChatBackground).FullName ?? "DeleteChatBackgroundAsync");

           try
           {
             return client.DeleteChatBackgroundAsync(chatId, restorePrevious);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd