// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Deletes the account of the current user, deleting all information associated with the user from the server. The phone number of the account can be used to create a new account.
    /// Can be called before authorization when the current authorization state is authorizationStateWaitPassword
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> DeleteAccountAsync(string reason = default, string password = default)
    {

           using var activity =  StartCallActivity("DeleteAccountAsync", typeof(DeleteAccount).FullName ?? "DeleteAccountAsync");

           try
           {
             return client.DeleteAccountAsync(reason, password);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd