// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Deletes all revoked chat invite links created by a given chat administrator. Requires administrator privileges and can_invite_users right in the chat for own links and owner privileges for other links
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> DeleteAllRevokedChatInviteLinksAsync(long chatId = default, long creatorUserId = default)
    {

           using var activity =  StartCallActivity("DeleteAllRevokedChatInviteLinksAsync", typeof(DeleteAllRevokedChatInviteLinks).FullName ?? "DeleteAllRevokedChatInviteLinksAsync");

           try
           {
             return client.DeleteAllRevokedChatInviteLinksAsync(chatId, creatorUserId);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd