// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Deletes a previously posted story. Can be called only if story.can_be_deleted == true
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> DeleteStoryAsync(long storyPosterChatId = default, int storyId = default)
    {

           using var activity =  StartCallActivity("DeleteStoryAsync", typeof(DeleteStory).FullName ?? "DeleteStoryAsync");

           try
           {
             return client.DeleteStoryAsync(storyPosterChatId, storyId);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd