// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Deletes a story posted by the bot on behalf of a business account; for bots only
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> DeleteBusinessStoryAsync(string businessConnectionId = default, int storyId = default)
    {

           using var activity =  StartCallActivity("DeleteBusinessStoryAsync", typeof(DeleteBusinessStory).FullName ?? "DeleteBusinessStoryAsync");

           try
           {
             return client.DeleteBusinessStoryAsync(businessConnectionId, storyId);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd