// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Deletes an invite link for a chat folder
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> DeleteChatFolderInviteLinkAsync(int chatFolderId = default, string inviteLink = default)
    {

           using var activity =  StartCallActivity("DeleteChatFolderInviteLinkAsync", typeof(DeleteChatFolderInviteLink).FullName ?? "DeleteChatFolderInviteLinkAsync");

           try
           {
             return client.DeleteChatFolderInviteLinkAsync(chatFolderId, inviteLink);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd