// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Deletes all call messages
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> DeleteAllCallMessagesAsync(bool revoke = default)
    {

           using var activity =  StartCallActivity("DeleteAllCallMessagesAsync", typeof(DeleteAllCallMessages).FullName ?? "DeleteAllCallMessagesAsync");

           try
           {
             return client.DeleteAllCallMessagesAsync(revoke);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd