// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Closes the TDLib instance, destroying all local data without a proper logout. The current user session will remain in the list of all active sessions. All local data will be destroyed.
    /// After the destruction completes updateAuthorizationState with authorizationStateClosed will be sent. Can be called before authorization
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> DestroyAsync()
    {

           using var activity =  StartCallActivity("DestroyAsync", typeof(Destroy).FullName ?? "DestroyAsync");

           try
           {
             return client.DestroyAsync();
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd