// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Disconnects all websites from the current user's Telegram account
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> DisconnectAllWebsitesAsync()
    {

           using var activity =  StartCallActivity("DisconnectAllWebsitesAsync", typeof(DisconnectAllWebsites).FullName ?? "DisconnectAllWebsitesAsync");

           try
           {
             return client.DisconnectAllWebsitesAsync();
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd