// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Discards a call
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> DiscardCallAsync(int callId = default, bool isDisconnected = default, string inviteLink = default, int duration = default, bool isVideo = default, long connectionId = default)
    {

           using var activity =  StartCallActivity("DiscardCallAsync", typeof(DiscardCall).FullName ?? "DiscardCallAsync");

           try
           {
             return client.DiscardCallAsync(callId, isDisconnected, inviteLink, duration, isVideo, connectionId);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd