// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Drops original details for an upgraded gift
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> DropGiftOriginalDetailsAsync(string receivedGiftId = default, long starCount = default)
    {

           using var activity =  StartCallActivity("DropGiftOriginalDetailsAsync", typeof(DropGiftOriginalDetails).FullName ?? "DropGiftOriginalDetailsAsync");

           try
           {
             return client.DropGiftOriginalDetailsAsync(receivedGiftId, starCount);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd