// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Edits the reply markup of a message sent on behalf of a business account; for bots only
    /// </summary>
    public Task<TdLib.TdApi.Objects.BusinessMessage> EditBusinessMessageReplyMarkupAsync(string businessConnectionId = default, long chatId = default, long messageId = default, ReplyMarkup replyMarkup = default)
    {

           using var activity =  StartCallActivity("EditBusinessMessageReplyMarkupAsync", typeof(EditBusinessMessageReplyMarkup).FullName ?? "EditBusinessMessageReplyMarkupAsync");

           try
           {
             return client.EditBusinessMessageReplyMarkupAsync(businessConnectionId, chatId, messageId, replyMarkup);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd