// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Edits the content of a live location in an inline message sent via a bot; for bots only
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> EditInlineMessageLiveLocationAsync(string inlineMessageId = default, ReplyMarkup replyMarkup = default, Location location = default, int livePeriod = default, int heading = default, int proximityAlertRadius = default)
    {

           using var activity =  StartCallActivity("EditInlineMessageLiveLocationAsync", typeof(EditInlineMessageLiveLocation).FullName ?? "EditInlineMessageLiveLocationAsync");

           try
           {
             return client.EditInlineMessageLiveLocationAsync(inlineMessageId, replyMarkup, location, livePeriod, heading, proximityAlertRadius);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd