// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Edits the message reply markup; for bots only. Returns the edited message after the edit is completed on the server side
    /// </summary>
    public Task<TdLib.TdApi.Objects.Message> EditMessageReplyMarkupAsync(long chatId = default, long messageId = default, ReplyMarkup replyMarkup = default)
    {

           using var activity =  StartCallActivity("EditMessageReplyMarkupAsync", typeof(EditMessageReplyMarkup).FullName ?? "EditMessageReplyMarkupAsync");

           try
           {
             return client.EditMessageReplyMarkupAsync(chatId, messageId, replyMarkup);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd