// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Edits title and icon of a topic in a forum supergroup chat or a chat with a bot with topics; for supergroup chats requires can_manage_topics administrator right
    /// unless the user is creator of the topic
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> EditForumTopicAsync(long chatId = default, int forumTopicId = default, string name = default, bool editIconCustomEmoji = default, long iconCustomEmojiId = default)
    {

           using var activity =  StartCallActivity("EditForumTopicAsync", typeof(EditForumTopic).FullName ?? "EditForumTopicAsync");

           try
           {
             return client.EditForumTopicAsync(chatId, forumTopicId, name, editIconCustomEmoji, iconCustomEmojiId);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd