// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Edits a business chat link of the current account. Requires Telegram Business subscription. Returns the edited link
    /// </summary>
    public Task<TdLib.TdApi.Objects.BusinessChatLink> EditBusinessChatLinkAsync(string link = default, InputBusinessChatLink linkInfo = default)
    {

           using var activity =  StartCallActivity("EditBusinessChatLinkAsync", typeof(EditBusinessChatLink).FullName ?? "EditBusinessChatLinkAsync");

           try
           {
             return client.EditBusinessChatLinkAsync(link, linkInfo);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd