// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Edits the text of a text or game message sent on behalf of a business account; for bots only
    /// </summary>
    public Task<TdLib.TdApi.Objects.BusinessMessage> EditBusinessMessageTextAsync(string businessConnectionId = default, long chatId = default, long messageId = default, ReplyMarkup replyMarkup = default, InputMessageContent inputMessageContent = default)
    {

           using var activity =  StartCallActivity("EditBusinessMessageTextAsync", typeof(EditBusinessMessageText).FullName ?? "EditBusinessMessageTextAsync");

           try
           {
             return client.EditBusinessMessageTextAsync(businessConnectionId, chatId, messageId, replyMarkup, inputMessageContent);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd