// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Edits the reply markup of an inline message sent via a bot; for bots only
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> EditInlineMessageReplyMarkupAsync(string inlineMessageId = default, ReplyMarkup replyMarkup = default)
    {

           using var activity =  StartCallActivity("EditInlineMessageReplyMarkupAsync", typeof(EditInlineMessageReplyMarkup).FullName ?? "EditInlineMessageReplyMarkupAsync");

           try
           {
             return client.EditInlineMessageReplyMarkupAsync(inlineMessageId, replyMarkup);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd