// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Edits the media content of a message with a text, an animation, an audio, a document, a photo or a video in a message sent on behalf of a business account; for bots only
    /// </summary>
    public Task<TdLib.TdApi.Objects.BusinessMessage> EditBusinessMessageMediaAsync(string businessConnectionId = default, long chatId = default, long messageId = default, ReplyMarkup replyMarkup = default, InputMessageContent inputMessageContent = default)
    {

           using var activity =  StartCallActivity("EditBusinessMessageMediaAsync", typeof(EditBusinessMessageMedia).FullName ?? "EditBusinessMessageMediaAsync");

           try
           {
             return client.EditBusinessMessageMediaAsync(businessConnectionId, chatId, messageId, replyMarkup, inputMessageContent);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd