// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Edits an invite link for a chat folder
    /// </summary>
    public Task<TdLib.TdApi.Objects.ChatFolderInviteLink> EditChatFolderInviteLinkAsync(int chatFolderId = default, string inviteLink = default, string name = default, long[] chatIds = default)
    {

           using var activity =  StartCallActivity("EditChatFolderInviteLinkAsync", typeof(EditChatFolderInviteLink).FullName ?? "EditChatFolderInviteLinkAsync");

           try
           {
             return client.EditChatFolderInviteLinkAsync(chatFolderId, inviteLink, name, chatIds);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd