// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Edits the message content caption. Returns the edited message after the edit is completed on the server side
    /// </summary>
    public Task<TdLib.TdApi.Objects.Message> EditMessageCaptionAsync(long chatId = default, long messageId = default, ReplyMarkup replyMarkup = default, FormattedText caption = default, bool showCaptionAboveMedia = default)
    {

           using var activity =  StartCallActivity("EditMessageCaptionAsync", typeof(EditMessageCaption).FullName ?? "EditMessageCaptionAsync");

           try
           {
             return client.EditMessageCaptionAsync(chatId, messageId, replyMarkup, caption, showCaptionAboveMedia);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd