// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Changes content and caption of a story. Can be called only if story.can_be_edited == true
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> EditStoryAsync(long storyPosterChatId = default, int storyId = default, InputStoryContent content = default, InputStoryAreas areas = default, FormattedText caption = default)
    {

           using var activity =  StartCallActivity("EditStoryAsync", typeof(EditStory).FullName ?? "EditStoryAsync");

           try
           {
             return client.EditStoryAsync(storyPosterChatId, storyId, content, areas, caption);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd