// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Edits the media content of a message with a text, an animation, an audio, a document, a photo or a video in an inline message sent via a bot; for bots only
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> EditInlineMessageMediaAsync(string inlineMessageId = default, ReplyMarkup replyMarkup = default, InputMessageContent inputMessageContent = default)
    {

           using var activity =  StartCallActivity("EditInlineMessageMediaAsync", typeof(EditInlineMessageMedia).FullName ?? "EditInlineMessageMediaAsync");

           try
           {
             return client.EditInlineMessageMediaAsync(inlineMessageId, replyMarkup, inputMessageContent);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd