// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Edits the caption of an inline message sent via a bot; for bots only
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> EditInlineMessageCaptionAsync(string inlineMessageId = default, ReplyMarkup replyMarkup = default, FormattedText caption = default, bool showCaptionAboveMedia = default)
    {

           using var activity =  StartCallActivity("EditInlineMessageCaptionAsync", typeof(EditInlineMessageCaption).FullName ?? "EditInlineMessageCaptionAsync");

           try
           {
             return client.EditInlineMessageCaptionAsync(inlineMessageId, replyMarkup, caption, showCaptionAboveMedia);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd