// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Finishes the file generation
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> FinishFileGenerationAsync(long generationId = default, Error error = default)
    {

           using var activity =  StartCallActivity("FinishFileGenerationAsync", typeof(FinishFileGeneration).FullName ?? "FinishFileGenerationAsync");

           try
           {
             return client.FinishFileGenerationAsync(generationId, error);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd