// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Forwards previously sent messages. Returns the forwarded messages in the same order as the message identifiers passed in message_ids. If a message can't be forwarded, null will be returned instead of the message
    /// </summary>
    public Task<TdLib.TdApi.Objects.Messages> ForwardMessagesAsync(long chatId = default, MessageTopic topicId = default, long fromChatId = default, long[] messageIds = default, MessageSendOptions options = default, bool sendCopy = default, bool removeCaption = default)
    {

           using var activity =  StartCallActivity("ForwardMessagesAsync", typeof(ForwardMessages).FullName ?? "ForwardMessagesAsync");

           try
           {
             return client.ForwardMessagesAsync(chatId, topicId, fromChatId, messageIds, options, sendCopy, removeCaption);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd