// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns gifts that can be sent to other users and channel chats
    /// </summary>
    public Task<TdLib.TdApi.Objects.AvailableGifts> GetAvailableGiftsAsync()
    {

           using var activity =  StartCallActivity("GetAvailableGiftsAsync", typeof(GetAvailableGifts).FullName ?? "GetAvailableGiftsAsync");

           try
           {
             return client.GetAvailableGiftsAsync();
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd