// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns the current authorization state. This is an offline method. For informational purposes only. Use updateAuthorizationState instead to maintain the current authorization state. Can be called before initialization
    /// </summary>
    public Task<TdLib.TdApi.Objects.AuthorizationState> GetAuthorizationStateAsync()
    {

           using var activity =  StartCallActivity("GetAuthorizationStateAsync", typeof(GetAuthorizationState).FullName ?? "GetAuthorizationStateAsync");

           try
           {
             return client.GetAuthorizationStateAsync();
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd