// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns parameters for authentication using a passkey as JSON-serialized string
    /// </summary>
    public Task<TdLib.TdApi.Objects.Text> GetAuthenticationPasskeyParametersAsync()
    {

           using var activity =  StartCallActivity("GetAuthenticationPasskeyParametersAsync", typeof(GetAuthenticationPasskeyParameters).FullName ?? "GetAuthenticationPasskeyParametersAsync");

           try
           {
             return client.GetAuthenticationPasskeyParametersAsync();
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd