// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns all available Telegram Passport elements
    /// </summary>
    public Task<TdLib.TdApi.Objects.PassportElements> GetAllPassportElementsAsync(string password = default)
    {

           using var activity =  StartCallActivity("GetAllPassportElementsAsync", typeof(GetAllPassportElements).FullName ?? "GetAllPassportElementsAsync");

           try
           {
             return client.GetAllPassportElementsAsync(password);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd