// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns autosave settings for the current user
    /// </summary>
    public Task<TdLib.TdApi.Objects.AutosaveSettings> GetAutosaveSettingsAsync()
    {

           using var activity =  StartCallActivity("GetAutosaveSettingsAsync", typeof(GetAutosaveSettings).FullName ?? "GetAutosaveSettingsAsync");

           try
           {
             return client.GetAutosaveSettingsAsync();
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd