// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns settings for automatic moving of chats to and from the Archive chat lists
    /// </summary>
    public Task<TdLib.TdApi.Objects.ArchiveChatListSettings> GetArchiveChatListSettingsAsync()
    {

           using var activity =  StartCallActivity("GetArchiveChatListSettingsAsync", typeof(GetArchiveChatListSettings).FullName ?? "GetArchiveChatListSettingsAsync");

           try
           {
             return client.GetArchiveChatListSettingsAsync();
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd