// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns approximate number of bots similar to the given bot
    /// </summary>
    public Task<TdLib.TdApi.Objects.Count> GetBotSimilarBotCountAsync(long botUserId = default, bool returnLocal = default)
    {

           using var activity =  StartCallActivity("GetBotSimilarBotCountAsync", typeof(GetBotSimilarBotCount).FullName ?? "GetBotSimilarBotCountAsync");

           try
           {
             return client.GetBotSimilarBotCountAsync(botUserId, returnLocal);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd