// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns information about a bank card
    /// </summary>
    public Task<TdLib.TdApi.Objects.BankCardInfo> GetBankCardInfoAsync(string bankCardNumber = default)
    {

           using var activity =  StartCallActivity("GetBankCardInfoAsync", typeof(GetBankCardInfo).FullName ?? "GetBankCardInfoAsync");

           try
           {
             return client.GetBankCardInfoAsync(bankCardNumber);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd