// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns a list of bots similar to the given bot
    /// </summary>
    public Task<TdLib.TdApi.Objects.Users> GetBotSimilarBotsAsync(long botUserId = default)
    {

           using var activity =  StartCallActivity("GetBotSimilarBotsAsync", typeof(GetBotSimilarBots).FullName ?? "GetBotSimilarBotsAsync");

           try
           {
             return client.GetBotSimilarBotsAsync(botUserId);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd