// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns business chat links created for the current account
    /// </summary>
    public Task<TdLib.TdApi.Objects.BusinessChatLinks> GetBusinessChatLinksAsync()
    {

           using var activity =  StartCallActivity("GetBusinessChatLinksAsync", typeof(GetBusinessChatLinks).FullName ?? "GetBusinessChatLinksAsync");

           try
           {
             return client.GetBusinessChatLinksAsync();
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd