// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Constructs a persistent HTTP URL for a background
    /// </summary>
    public Task<TdLib.TdApi.Objects.HttpUrl> GetBackgroundUrlAsync(string name = default, BackgroundType type = default)
    {

           using var activity =  StartCallActivity("GetBackgroundUrlAsync", typeof(GetBackgroundUrl).FullName ?? "GetBackgroundUrlAsync");

           try
           {
             return client.GetBackgroundUrlAsync(name, type);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd