// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns information about features, available to Business users
    /// </summary>
    public Task<TdLib.TdApi.Objects.BusinessFeatures> GetBusinessFeaturesAsync(BusinessFeature source = default)
    {

           using var activity =  StartCallActivity("GetBusinessFeaturesAsync", typeof(GetBusinessFeatures).FullName ?? "GetBusinessFeaturesAsync");

           try
           {
             return client.GetBusinessFeaturesAsync(source);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd