// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns the user who will become the owner of the chat after 7 days if the current user does not return to the supergroup or channel during that period or immediately for basic groups; requires owner privileges in the chat.
    /// Available only for supergroups and channel chats
    /// </summary>
    public Task<TdLib.TdApi.Objects.User> GetChatOwnerAfterLeavingAsync(long chatId = default)
    {

           using var activity =  StartCallActivity("GetChatOwnerAfterLeavingAsync", typeof(GetChatOwnerAfterLeaving).FullName ?? "GetChatOwnerAfterLeavingAsync");

           try
           {
             return client.GetChatOwnerAfterLeavingAsync(chatId);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd