// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns information about a chat by its identifier. This is an offline method if the current user is not a bot
    /// </summary>
    public Task<TdLib.TdApi.Objects.Chat> GetChatAsync(long chatId = default)
    {

           using var activity =  StartCallActivity("GetChatAsync", typeof(GetChat).FullName ?? "GetChatAsync");

           try
           {
             return client.GetChatAsync(chatId);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd