// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns the current boost status for a supergroup or a channel chat
    /// </summary>
    public Task<TdLib.TdApi.Objects.ChatBoostStatus> GetChatBoostStatusAsync(long chatId = default)
    {

           using var activity =  StartCallActivity("GetChatBoostStatusAsync", typeof(GetChatBoostStatus).FullName ?? "GetChatBoostStatusAsync");

           try
           {
             return client.GetChatBoostStatusAsync(chatId);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd