// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns information about a newest pinned message in the chat. Returns a 404 error if the message doesn't exist
    /// </summary>
    public Task<TdLib.TdApi.Objects.Message> GetChatPinnedMessageAsync(long chatId = default)
    {

           using var activity =  StartCallActivity("GetChatPinnedMessageAsync", typeof(GetChatPinnedMessage).FullName ?? "GetChatPinnedMessageAsync");

           try
           {
             return client.GetChatPinnedMessageAsync(chatId);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd