// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns the list of message sender identifiers, which can be used to send a paid reaction in a chat
    /// </summary>
    public Task<TdLib.TdApi.Objects.MessageSenders> GetChatAvailablePaidMessageReactionSendersAsync(long chatId = default)
    {

           using var activity =  StartCallActivity("GetChatAvailablePaidMessageReactionSendersAsync", typeof(GetChatAvailablePaidMessageReactionSenders).FullName ?? "GetChatAvailablePaidMessageReactionSendersAsync");

           try
           {
             return client.GetChatAvailablePaidMessageReactionSendersAsync(chatId);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd