// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns interactions with a story posted in a chat. Can be used only if story is posted on behalf of a chat and the user is an administrator in the chat
    /// </summary>
    public Task<TdLib.TdApi.Objects.StoryInteractions> GetChatStoryInteractionsAsync(long storyPosterChatId = default, int storyId = default, ReactionType reactionType = default, bool preferForwards = default, string offset = default, int limit = default)
    {

           using var activity =  StartCallActivity("GetChatStoryInteractionsAsync", typeof(GetChatStoryInteractions).FullName ?? "GetChatStoryInteractionsAsync");

           try
           {
             return client.GetChatStoryInteractionsAsync(storyPosterChatId, storyId, reactionType, preferForwards, offset, limit);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd