// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns identifiers of pinned or always included chats from a chat folder, which are suggested to be left when the chat folder is deleted
    /// </summary>
    public Task<TdLib.TdApi.Objects.Chats> GetChatFolderChatsToLeaveAsync(int chatFolderId = default)
    {

           using var activity =  StartCallActivity("GetChatFolderChatsToLeaveAsync", typeof(GetChatFolderChatsToLeave).FullName ?? "GetChatFolderChatsToLeaveAsync");

           try
           {
             return client.GetChatFolderChatsToLeaveAsync(chatFolderId);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd