// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns an ordered list of chats from the beginning of a chat list. For informational purposes only. Use loadChats and updates processing instead to maintain chat lists in a consistent state
    /// </summary>
    public Task<TdLib.TdApi.Objects.Chats> GetChatsAsync(ChatList chatList = default, int limit = default)
    {

           using var activity =  StartCallActivity("GetChatsAsync", typeof(GetChats).FullName ?? "GetChatsAsync");

           try
           {
             return client.GetChatsAsync(chatList, limit);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd