// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns all website where the current user used Telegram to log in
    /// </summary>
    public Task<TdLib.TdApi.Objects.ConnectedWebsites> GetConnectedWebsitesAsync()
    {

           using var activity =  StartCallActivity("GetConnectedWebsitesAsync", typeof(GetConnectedWebsites).FullName ?? "GetConnectedWebsitesAsync");

           try
           {
             return client.GetConnectedWebsitesAsync();
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd