// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns sparse positions of messages of the specified type in the chat to be used for shared media scroll implementation. Returns the results in reverse chronological order (i.e., in order of decreasing message_id).
    /// Cannot be used in secret chats or with searchMessagesFilterFailedToSend filter without an enabled message database
    /// </summary>
    public Task<TdLib.TdApi.Objects.MessagePositions> GetChatSparseMessagePositionsAsync(long chatId = default, SearchMessagesFilter filter = default, long fromMessageId = default, int limit = default, long savedMessagesTopicId = default)
    {

           using var activity =  StartCallActivity("GetChatSparseMessagePositionsAsync", typeof(GetChatSparseMessagePositions).FullName ?? "GetChatSparseMessagePositionsAsync");

           try
           {
             return client.GetChatSparseMessagePositionsAsync(chatId, filter, fromMessageId, limit, savedMessagesTopicId);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd