// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns detailed statistics about a chat. Currently, this method can be used only for supergroups and channels. Can be used only if supergroupFullInfo.can_get_statistics == true
    /// </summary>
    public Task<TdLib.TdApi.Objects.ChatStatistics> GetChatStatisticsAsync(long chatId = default, bool isDark = default)
    {

           using var activity =  StartCallActivity("GetChatStatisticsAsync", typeof(GetChatStatistics).FullName ?? "GetChatStatisticsAsync");

           try
           {
             return client.GetChatStatisticsAsync(chatId, isDark);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd