// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns the list of chats with non-default notification settings for new messages
    /// </summary>
    public Task<TdLib.TdApi.Objects.Chats> GetChatNotificationSettingsExceptionsAsync(NotificationSettingsScope scope = default, bool compareSound = default)
    {

           using var activity =  StartCallActivity("GetChatNotificationSettingsExceptionsAsync", typeof(GetChatNotificationSettingsExceptions).FullName ?? "GetChatNotificationSettingsExceptionsAsync");

           try
           {
             return client.GetChatNotificationSettingsExceptionsAsync(scope, compareSound);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd