// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns the list of features available for different chat boost levels. This is an offline method
    /// </summary>
    public Task<TdLib.TdApi.Objects.ChatBoostFeatures> GetChatBoostFeaturesAsync(bool isChannel = default)
    {

           using var activity =  StartCallActivity("GetChatBoostFeaturesAsync", typeof(GetChatBoostFeatures).FullName ?? "GetChatBoostFeaturesAsync");

           try
           {
             return client.GetChatBoostFeaturesAsync(isChannel);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd