// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns the list of boosts applied to a chat; requires administrator rights in the chat
    /// </summary>
    public Task<TdLib.TdApi.Objects.FoundChatBoosts> GetChatBoostsAsync(long chatId = default, bool onlyGiftCodes = default, string offset = default, int limit = default)
    {

           using var activity =  StartCallActivity("GetChatBoostsAsync", typeof(GetChatBoosts).FullName ?? "GetChatBoostsAsync");

           try
           {
             return client.GetChatBoostsAsync(chatId, onlyGiftCodes, offset, limit);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd