// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns all updates needed to restore current TDLib state, i.e. all actual updateAuthorizationState/updateUser/updateNewChat and others. This is especially useful if TDLib is run in a separate process. Can be called before initialization
    /// </summary>
    public Task<TdLib.TdApi.Objects.Updates> GetCurrentStateAsync()
    {

           using var activity =  StartCallActivity("GetCurrentStateAsync", typeof(GetCurrentState).FullName ?? "GetCurrentStateAsync");

           try
           {
             return client.GetCurrentStateAsync();
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd