// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns invite links for a chat created by specified administrator. Requires administrator privileges and can_invite_users right in the chat to get own links and owner privileges to get other links
    /// </summary>
    public Task<TdLib.TdApi.Objects.ChatInviteLinks> GetChatInviteLinksAsync(long chatId = default, long creatorUserId = default, bool isRevoked = default, int offsetDate = default, string offsetInviteLink = default, int limit = default)
    {

           using var activity =  StartCallActivity("GetChatInviteLinksAsync", typeof(GetChatInviteLinks).FullName ?? "GetChatInviteLinksAsync");

           try
           {
             return client.GetChatInviteLinksAsync(chatId, creatorUserId, isRevoked, offsetDate, offsetInviteLink, limit);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd