// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns the current weather in the given location
    /// </summary>
    public Task<TdLib.TdApi.Objects.CurrentWeather> GetCurrentWeatherAsync(Location location = default)
    {

           using var activity =  StartCallActivity("GetCurrentWeatherAsync", typeof(GetCurrentWeather).FullName ?? "GetCurrentWeatherAsync");

           try
           {
             return client.GetCurrentWeatherAsync(location);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd