// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns information about a given collectible item that was purchased at https://fragment.com
    /// </summary>
    public Task<TdLib.TdApi.Objects.CollectibleItemInfo> GetCollectibleItemInfoAsync(CollectibleItemType type = default)
    {

           using var activity =  StartCallActivity("GetCollectibleItemInfoAsync", typeof(GetCollectibleItemInfo).FullName ?? "GetCollectibleItemInfoAsync");

           try
           {
             return client.GetCollectibleItemInfoAsync(type);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd