// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns an affiliate program that was connected to the given affiliate by identifier of the bot that created the program
    /// </summary>
    public Task<TdLib.TdApi.Objects.ConnectedAffiliateProgram> GetConnectedAffiliateProgramAsync(AffiliateType affiliate = default, long botUserId = default)
    {

           using var activity =  StartCallActivity("GetConnectedAffiliateProgramAsync", typeof(GetConnectedAffiliateProgram).FullName ?? "GetConnectedAffiliateProgramAsync");

           try
           {
             return client.GetConnectedAffiliateProgramAsync(affiliate, botUserId);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd