// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns all close friends of the current user
    /// </summary>
    public Task<TdLib.TdApi.Objects.Users> GetCloseFriendsAsync()
    {

           using var activity =  StartCallActivity("GetCloseFriendsAsync", typeof(GetCloseFriends).FullName ?? "GetCloseFriendsAsync");

           try
           {
             return client.GetCloseFriendsAsync();
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd