// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns the list of story albums owned by the given chat
    /// </summary>
    public Task<TdLib.TdApi.Objects.StoryAlbums> GetChatStoryAlbumsAsync(long chatId = default)
    {

           using var activity =  StartCallActivity("GetChatStoryAlbumsAsync", typeof(GetChatStoryAlbums).FullName ?? "GetChatStoryAlbumsAsync");

           try
           {
             return client.GetChatStoryAlbumsAsync(chatId);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd