// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns approximate number of chats similar to the given chat
    /// </summary>
    public Task<TdLib.TdApi.Objects.Count> GetChatSimilarChatCountAsync(long chatId = default, bool returnLocal = default)
    {

           using var activity =  StartCallActivity("GetChatSimilarChatCountAsync", typeof(GetChatSimilarChatCount).FullName ?? "GetChatSimilarChatCountAsync");

           try
           {
             return client.GetChatSimilarChatCountAsync(chatId, returnLocal);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd