// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns the last message sent in a chat no later than the specified date. Returns a 404 error if such message doesn't exist
    /// </summary>
    public Task<TdLib.TdApi.Objects.Message> GetChatMessageByDateAsync(long chatId = default, int date = default)
    {

           using var activity =  StartCallActivity("GetChatMessageByDateAsync", typeof(GetChatMessageByDate).FullName ?? "GetChatMessageByDateAsync");

           try
           {
             return client.GetChatMessageByDateAsync(chatId, date);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd