// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns the list of features available on the specific chat boost level. This is an offline method
    /// </summary>
    public Task<TdLib.TdApi.Objects.ChatBoostLevelFeatures> GetChatBoostLevelFeaturesAsync(bool isChannel = default, int level = default)
    {

           using var activity =  StartCallActivity("GetChatBoostLevelFeaturesAsync", typeof(GetChatBoostLevelFeatures).FullName ?? "GetChatBoostLevelFeaturesAsync");

           try
           {
             return client.GetChatBoostLevelFeaturesAsync(isChannel, level);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd