// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns the list of custom emoji stickers by their identifiers. Stickers are returned in arbitrary order. Only found stickers are returned
    /// </summary>
    public Task<TdLib.TdApi.Objects.Stickers> GetCustomEmojiStickersAsync(long[] customEmojiIds = default)
    {

           using var activity =  StartCallActivity("GetCustomEmojiStickersAsync", typeof(GetCustomEmojiStickers).FullName ?? "GetCustomEmojiStickersAsync");

           try
           {
             return client.GetCustomEmojiStickersAsync(customEmojiIds);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd