// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns all scheduled messages in a chat. The messages are returned in reverse chronological order (i.e., in order of decreasing message_id)
    /// </summary>
    public Task<TdLib.TdApi.Objects.Messages> GetChatScheduledMessagesAsync(long chatId = default)
    {

           using var activity =  StartCallActivity("GetChatScheduledMessagesAsync", typeof(GetChatScheduledMessages).FullName ?? "GetChatScheduledMessagesAsync");

           try
           {
             return client.GetChatScheduledMessagesAsync(chatId);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd