// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns default list of custom emoji stickers for placing on a profile photo
    /// </summary>
    public Task<TdLib.TdApi.Objects.Stickers> GetDefaultProfilePhotoCustomEmojiStickersAsync()
    {

           using var activity =  StartCallActivity("GetDefaultProfilePhotoCustomEmojiStickersAsync", typeof(GetDefaultProfilePhotoCustomEmojiStickers).FullName ?? "GetDefaultProfilePhotoCustomEmojiStickersAsync");

           try
           {
             return client.GetDefaultProfilePhotoCustomEmojiStickersAsync();
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd