// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns default list of custom emoji stickers for reply background
    /// </summary>
    public Task<TdLib.TdApi.Objects.Stickers> GetDefaultBackgroundCustomEmojiStickersAsync()
    {

           using var activity =  StartCallActivity("GetDefaultBackgroundCustomEmojiStickersAsync", typeof(GetDefaultBackgroundCustomEmojiStickers).FullName ?? "GetDefaultBackgroundCustomEmojiStickersAsync");

           try
           {
             return client.GetDefaultBackgroundCustomEmojiStickersAsync();
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd