// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns database statistics
    /// </summary>
    public Task<TdLib.TdApi.Objects.DatabaseStatistics> GetDatabaseStatisticsAsync()
    {

           using var activity =  StartCallActivity("GetDatabaseStatisticsAsync", typeof(GetDatabaseStatistics).FullName ?? "GetDatabaseStatisticsAsync");

           try
           {
             return client.GetDatabaseStatisticsAsync();
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd