// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns the total number of Telegram Stars received by the channel chat for direct messages from the given topic
    /// </summary>
    public Task<TdLib.TdApi.Objects.StarCount> GetDirectMessagesChatTopicRevenueAsync(long chatId = default, long topicId = default)
    {

           using var activity =  StartCallActivity("GetDirectMessagesChatTopicRevenueAsync", typeof(GetDirectMessagesChatTopicRevenue).FullName ?? "GetDirectMessagesChatTopicRevenueAsync");

           try
           {
             return client.GetDirectMessagesChatTopicRevenueAsync(chatId, topicId);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd