// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns available emoji categories
    /// </summary>
    public Task<TdLib.TdApi.Objects.EmojiCategories> GetEmojiCategoriesAsync(EmojiCategoryType type = default)
    {

           using var activity =  StartCallActivity("GetEmojiCategoriesAsync", typeof(GetEmojiCategories).FullName ?? "GetEmojiCategoriesAsync");

           try
           {
             return client.GetEmojiCategoriesAsync(type);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd