// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns an HTTP URL which can be used to automatically log in to the translation platform and suggest new emoji replacements. The URL will be valid for 30 seconds after generation
    /// </summary>
    public Task<TdLib.TdApi.Objects.HttpUrl> GetEmojiSuggestionsUrlAsync(string languageCode = default)
    {

           using var activity =  StartCallActivity("GetEmojiSuggestionsUrlAsync", typeof(GetEmojiSuggestionsUrl).FullName ?? "GetEmojiSuggestionsUrlAsync");

           try
           {
             return client.GetEmojiSuggestionsUrlAsync(languageCode);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd