// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns the extension of a file, guessed by its MIME type. Returns an empty string on failure. Can be called synchronously
    /// </summary>
    public Task<TdLib.TdApi.Objects.Text> GetFileExtensionAsync(string mimeType = default)
    {

           using var activity =  StartCallActivity("GetFileExtensionAsync", typeof(GetFileExtension).FullName ?? "GetFileExtensionAsync");

           try
           {
             return client.GetFileExtensionAsync(mimeType);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd