// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns the MIME type of a file, guessed by its extension. Returns an empty string on failure. Can be called synchronously
    /// </summary>
    public Task<TdLib.TdApi.Objects.Text> GetFileMimeTypeAsync(string fileName = default)
    {

           using var activity =  StartCallActivity("GetFileMimeTypeAsync", typeof(GetFileMimeType).FullName ?? "GetFileMimeTypeAsync");

           try
           {
             return client.GetFileMimeTypeAsync(fileName);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd