// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns file downloaded prefix size from a given offset, in bytes
    /// </summary>
    public Task<TdLib.TdApi.Objects.FileDownloadedPrefixSize> GetFileDownloadedPrefixSizeAsync(int fileId = default, long offset = default)
    {

           using var activity =  StartCallActivity("GetFileDownloadedPrefixSizeAsync", typeof(GetFileDownloadedPrefixSize).FullName ?? "GetFileDownloadedPrefixSizeAsync");

           try
           {
             return client.GetFileDownloadedPrefixSizeAsync(fileId, offset);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd