// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns collections of gifts owned by the given user or chat
    /// </summary>
    public Task<TdLib.TdApi.Objects.GiftCollections> GetGiftCollectionsAsync(MessageSender ownerId = default)
    {

           using var activity =  StartCallActivity("GetGiftCollectionsAsync", typeof(GetGiftCollections).FullName ?? "GetGiftCollectionsAsync");

           try
           {
             return client.GetGiftCollectionsAsync(ownerId);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd