// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns information about participants of a non-joined group call that is not bound to a chat
    /// </summary>
    public Task<TdLib.TdApi.Objects.GroupCallParticipants> GetGroupCallParticipantsAsync(InputGroupCall inputGroupCall = default, int limit = default)
    {

           using var activity =  StartCallActivity("GetGroupCallParticipantsAsync", typeof(GetGroupCallParticipants).FullName ?? "GetGroupCallParticipantsAsync");

           try
           {
             return client.GetGroupCallParticipantsAsync(inputGroupCall, limit);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd