// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns the most grossing Web App bots
    /// </summary>
    public Task<TdLib.TdApi.Objects.FoundUsers> GetGrossingWebAppBotsAsync(string offset = default, int limit = default)
    {

           using var activity =  StartCallActivity("GetGrossingWebAppBotsAsync", typeof(GetGrossingWebAppBots).FullName ?? "GetGrossingWebAppBotsAsync");

           try
           {
             return client.GetGrossingWebAppBotsAsync(offset, limit);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd