// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns information about a group call
    /// </summary>
    public Task<TdLib.TdApi.Objects.GroupCall> GetGroupCallAsync(int groupCallId = default)
    {

           using var activity =  StartCallActivity("GetGroupCallAsync", typeof(GetGroupCall).FullName ?? "GetGroupCallAsync");

           try
           {
             return client.GetGroupCallAsync(groupCallId);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd