// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns the gifts that were acquired by the current user on a gift auction
    /// </summary>
    public Task<TdLib.TdApi.Objects.GiftAuctionAcquiredGifts> GetGiftAuctionAcquiredGiftsAsync(long giftId = default)
    {

           using var activity =  StartCallActivity("GetGiftAuctionAcquiredGiftsAsync", typeof(GetGiftAuctionAcquiredGifts).FullName ?? "GetGiftAuctionAcquiredGiftsAsync");

           try
           {
             return client.GetGiftAuctionAcquiredGiftsAsync(giftId);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd