// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns information about a giveaway
    /// </summary>
    public Task<TdLib.TdApi.Objects.GiveawayInfo> GetGiveawayInfoAsync(long chatId = default, long messageId = default)
    {

           using var activity =  StartCallActivity("GetGiveawayInfoAsync", typeof(GetGiveawayInfo).FullName ?? "GetGiveawayInfoAsync");

           try
           {
             return client.GetGiveawayInfoAsync(chatId, messageId);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd