// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns a list of common group chats with a given user. Chats are sorted by their type and creation date
    /// </summary>
    public Task<TdLib.TdApi.Objects.Chats> GetGroupsInCommonAsync(long userId = default, long offsetChatId = default, int limit = default)
    {

           using var activity =  StartCallActivity("GetGroupsInCommonAsync", typeof(GetGroupsInCommon).FullName ?? "GetGroupsInCommonAsync");

           try
           {
             return client.GetGroupsInCommonAsync(userId, offsetChatId, limit);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd