// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns examples of possible upgraded gifts for a regular gift
    /// </summary>
    public Task<TdLib.TdApi.Objects.GiftUpgradePreview> GetGiftUpgradePreviewAsync(long regularGiftId = default)
    {

           using var activity =  StartCallActivity("GetGiftUpgradePreviewAsync", typeof(GetGiftUpgradePreview).FullName ?? "GetGiftUpgradePreviewAsync");

           try
           {
             return client.GetGiftUpgradePreviewAsync(regularGiftId);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd