// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns a file with a segment of a video chat or live story in a modified OGG format for audio or MPEG-4 format for video
    /// </summary>
    public Task<TdLib.TdApi.Objects.Data> GetGroupCallStreamSegmentAsync(int groupCallId = default, long timeOffset = default, int scale = default, int channelId = default, GroupCallVideoQuality videoQuality = default)
    {

           using var activity =  StartCallActivity("GetGroupCallStreamSegmentAsync", typeof(GetGroupCallStreamSegment).FullName ?? "GetGroupCallStreamSegmentAsync");

           try
           {
             return client.GetGroupCallStreamSegmentAsync(groupCallId, timeOffset, scale, channelId, videoQuality);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd