// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns backgrounds installed by the user
    /// </summary>
    public Task<TdLib.TdApi.Objects.Backgrounds> GetInstalledBackgroundsAsync(bool forDarkTheme = default)
    {

           using var activity =  StartCallActivity("GetInstalledBackgroundsAsync", typeof(GetInstalledBackgrounds).FullName ?? "GetInstalledBackgroundsAsync");

           try
           {
             return client.GetInstalledBackgroundsAsync(forDarkTheme);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd