// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns a list of recently inactive supergroups and channels. Can be used when user reaches limit on the number of joined supergroups and channels and receives the error "CHANNELS_TOO_MUCH". Also, the limit can be increased with Telegram Premium
    /// </summary>
    public Task<TdLib.TdApi.Objects.Chats> GetInactiveSupergroupChatsAsync()
    {

           using var activity =  StartCallActivity("GetInactiveSupergroupChatsAsync", typeof(GetInactiveSupergroupChats).FullName ?? "GetInactiveSupergroupChatsAsync");

           try
           {
             return client.GetInactiveSupergroupChatsAsync();
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd