// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Sends an inline query to a bot and returns its results. Returns an error with code 502 if the bot fails to answer the query before the query timeout expires
    /// </summary>
    public Task<TdLib.TdApi.Objects.InlineQueryResults> GetInlineQueryResultsAsync(long botUserId = default, long chatId = default, Location userLocation = default, string query = default, string offset = default)
    {

           using var activity =  StartCallActivity("GetInlineQueryResultsAsync", typeof(GetInlineQueryResults).FullName ?? "GetInlineQueryResultsAsync");

           try
           {
             return client.GetInlineQueryResultsAsync(botUserId, chatId, userLocation, query, offset);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd