// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Converts a JsonValue object to corresponding JSON-serialized string. Can be called synchronously
    /// </summary>
    public Task<TdLib.TdApi.Objects.Text> GetJsonStringAsync(JsonValue jsonValue = default)
    {

           using var activity =  StartCallActivity("GetJsonStringAsync", typeof(GetJsonString).FullName ?? "GetJsonStringAsync");

           try
           {
             return client.GetJsonStringAsync(jsonValue);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd