// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Converts a JSON-serialized string to corresponding JsonValue object. Can be called synchronously
    /// </summary>
    public Task<TdLib.TdApi.Objects.JsonValue> GetJsonValueAsync(string json = default)
    {

           using var activity =  StartCallActivity("GetJsonValueAsync", typeof(GetJsonValue).FullName ?? "GetJsonValueAsync");

           try
           {
             return client.GetJsonValueAsync(json);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd