// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns emojis matching the keyword. Supported only if the file database is enabled. Order of results is unspecified
    /// </summary>
    public Task<TdLib.TdApi.Objects.Emojis> GetKeywordEmojisAsync(string text = default, string[] inputLanguageCodes = default)
    {

           using var activity =  StartCallActivity("GetKeywordEmojisAsync", typeof(GetKeywordEmojis).FullName ?? "GetKeywordEmojisAsync");

           try
           {
             return client.GetKeywordEmojisAsync(text, inputLanguageCodes);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd