// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns information about a language pack. Returned language pack identifier may be different from a provided one. Can be called before authorization
    /// </summary>
    public Task<TdLib.TdApi.Objects.LanguagePackInfo> GetLanguagePackInfoAsync(string languagePackId = default)
    {

           using var activity =  StartCallActivity("GetLanguagePackInfoAsync", typeof(GetLanguagePackInfo).FullName ?? "GetLanguagePackInfoAsync");

           try
           {
             return client.GetLanguagePackInfoAsync(languagePackId);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd