// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns a link preview by the text of a message. Do not call this function too often. Returns a 404 error if the text has no link preview
    /// </summary>
    public Task<TdLib.TdApi.Objects.LinkPreview> GetLinkPreviewAsync(FormattedText text = default, LinkPreviewOptions linkPreviewOptions = default)
    {

           using var activity =  StartCallActivity("GetLinkPreviewAsync", typeof(GetLinkPreview).FullName ?? "GetLinkPreviewAsync");

           try
           {
             return client.GetLinkPreviewAsync(text, linkPreviewOptions);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd