// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns the list of message sender identifiers, on whose behalf messages can be sent to a live story
    /// </summary>
    public Task<TdLib.TdApi.Objects.ChatMessageSenders> GetLiveStoryAvailableMessageSendersAsync(int groupCallId = default)
    {

           using var activity =  StartCallActivity("GetLiveStoryAvailableMessageSendersAsync", typeof(GetLiveStoryAvailableMessageSenders).FullName ?? "GetLiveStoryAvailableMessageSendersAsync");

           try
           {
             return client.GetLiveStoryAvailableMessageSendersAsync(groupCallId);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd