// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns RTMP URL for streaming to a live story; requires can_post_stories administrator right for channel chats
    /// </summary>
    public Task<TdLib.TdApi.Objects.RtmpUrl> GetLiveStoryRtmpUrlAsync(long chatId = default)
    {

           using var activity =  StartCallActivity("GetLiveStoryRtmpUrlAsync", typeof(GetLiveStoryRtmpUrl).FullName ?? "GetLiveStoryRtmpUrlAsync");

           try
           {
             return client.GetLiveStoryRtmpUrlAsync(chatId);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd