// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns current verbosity level for a specified TDLib internal log tag. Can be called synchronously
    /// </summary>
    public Task<TdLib.TdApi.Objects.LogVerbosityLevel> GetLogTagVerbosityLevelAsync(string tag = default)
    {

           using var activity =  StartCallActivity("GetLogTagVerbosityLevelAsync", typeof(GetLogTagVerbosityLevel).FullName ?? "GetLogTagVerbosityLevelAsync");

           try
           {
             return client.GetLogTagVerbosityLevelAsync(tag);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd