// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns the list of passkeys allowed to be used for the login by the current user
    /// </summary>
    public Task<TdLib.TdApi.Objects.Passkeys> GetLoginPasskeysAsync()
    {

           using var activity =  StartCallActivity("GetLoginPasskeysAsync", typeof(GetLoginPasskeys).FullName ?? "GetLoginPasskeysAsync");

           try
           {
             return client.GetLoginPasskeysAsync();
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd