// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns information about currently used log stream for internal logging of TDLib. Can be called synchronously
    /// </summary>
    public Task<TdLib.TdApi.Objects.LogStream> GetLogStreamAsync()
    {

           using var activity =  StartCallActivity("GetLogStreamAsync", typeof(GetLogStream).FullName ?? "GetLogStreamAsync");

           try
           {
             return client.GetLogStreamAsync();
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd