// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns the list of available TDLib internal log tags, for example, ["actor", "binlog", "connections", "notifications", "proxy"]. Can be called synchronously
    /// </summary>
    public Task<TdLib.TdApi.Objects.LogTags> GetLogTagsAsync()
    {

           using var activity =  StartCallActivity("GetLogTagsAsync", typeof(GetLogTags).FullName ?? "GetLogTagsAsync");

           try
           {
             return client.GetLogTagsAsync();
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd