// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns an HTTP URL which can be used to automatically authorize the user on a website after clicking an inline button of type inlineKeyboardButtonTypeLoginUrl.
    /// Use the method getLoginUrlInfo to find whether a prior user confirmation is needed. If an error is returned, then the button must be handled as an ordinary URL button
    /// </summary>
    public Task<TdLib.TdApi.Objects.HttpUrl> GetLoginUrlAsync(long chatId = default, long messageId = default, long buttonId = default, bool allowWriteAccess = default)
    {

           using var activity =  StartCallActivity("GetLoginUrlAsync", typeof(GetLoginUrl).FullName ?? "GetLoginUrlAsync");

           try
           {
             return client.GetLoginUrlAsync(chatId, messageId, buttonId, allowWriteAccess);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd