// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns a string stored in the local database from the specified localization target and language pack by its key. Returns a 404 error if the string is not found. Can be called synchronously
    /// </summary>
    public Task<TdLib.TdApi.Objects.LanguagePackStringValue> GetLanguagePackStringAsync(string languagePackDatabasePath = default, string localizationTarget = default, string languagePackId = default, string key = default)
    {

           using var activity =  StartCallActivity("GetLanguagePackStringAsync", typeof(GetLanguagePackString).FullName ?? "GetLanguagePackStringAsync");

           try
           {
             return client.GetLanguagePackStringAsync(languagePackDatabasePath, localizationTarget, languagePackId, key);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd