// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns information about messages. If a message is not found, returns null on the corresponding position of the result
    /// </summary>
    public Task<TdLib.TdApi.Objects.Messages> GetMessagesAsync(long chatId = default, long[] messageIds = default)
    {

           using var activity =  StartCallActivity("GetMessagesAsync", typeof(GetMessages).FullName ?? "GetMessagesAsync");

           try
           {
             return client.GetMessagesAsync(chatId, messageIds);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd