// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns information needed to open the main Web App of a bot
    /// </summary>
    public Task<TdLib.TdApi.Objects.MainWebApp> GetMainWebAppAsync(long chatId = default, long botUserId = default, string startParameter = default, WebAppOpenParameters parameters = default)
    {

           using var activity =  StartCallActivity("GetMainWebAppAsync", typeof(GetMainWebApp).FullName ?? "GetMainWebAppAsync");

           try
           {
             return client.GetMainWebAppAsync(chatId, botUserId, startParameter, parameters);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd