// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns information about a public or private message link. Can be called for any internal link of the type internalLinkTypeMessage
    /// </summary>
    public Task<TdLib.TdApi.Objects.MessageLinkInfo> GetMessageLinkInfoAsync(string url = default)
    {

           using var activity =  StartCallActivity("GetMessageLinkInfoAsync", typeof(GetMessageLinkInfo).FullName ?? "GetMessageLinkInfoAsync");

           try
           {
             return client.GetMessageLinkInfoAsync(url);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd