// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns read date of a recent outgoing message in a private chat. The method can be called if messageProperties.can_get_read_date == true
    /// </summary>
    public Task<TdLib.TdApi.Objects.MessageReadDate> GetMessageReadDateAsync(long chatId = default, long messageId = default)
    {

           using var activity =  StartCallActivity("GetMessageReadDateAsync", typeof(GetMessageReadDate).FullName ?? "GetMessageReadDateAsync");

           try
           {
             return client.GetMessageReadDateAsync(chatId, messageId);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd