// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns a confirmation text to be shown to the user before starting message import
    /// </summary>
    public Task<TdLib.TdApi.Objects.Text> GetMessageImportConfirmationTextAsync(long chatId = default)
    {

           using var activity =  StartCallActivity("GetMessageImportConfirmationTextAsync", typeof(GetMessageImportConfirmationText).FullName ?? "GetMessageImportConfirmationTextAsync");

           try
           {
             return client.GetMessageImportConfirmationTextAsync(chatId);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd