// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns the current user
    /// </summary>
    public Task<TdLib.TdApi.Objects.User> GetMeAsync()
    {

           using var activity =  StartCallActivity("GetMeAsync", typeof(GetMe).FullName ?? "GetMeAsync");

           try
           {
             return client.GetMeAsync();
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd