// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns properties of a message. This is an offline method
    /// </summary>
    public Task<TdLib.TdApi.Objects.MessageProperties> GetMessagePropertiesAsync(long chatId = default, long messageId = default)
    {

           using var activity =  StartCallActivity("GetMessagePropertiesAsync", typeof(GetMessageProperties).FullName ?? "GetMessagePropertiesAsync");

           try
           {
             return client.GetMessagePropertiesAsync(chatId, messageId);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd