// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns information about actual author of a message sent on behalf of a channel. The method can be called if messageProperties.can_get_author == true
    /// </summary>
    public Task<TdLib.TdApi.Objects.User> GetMessageAuthorAsync(long chatId = default, long messageId = default)
    {

           using var activity =  StartCallActivity("GetMessageAuthorAsync", typeof(GetMessageAuthor).FullName ?? "GetMessageAuthorAsync");

           try
           {
             return client.GetMessageAuthorAsync(chatId, messageId);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd