// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns messages in a message thread of a message. Can be used only if messageProperties.can_get_message_thread == true. Message thread of a channel message is in the channel's linked supergroup.
    /// The messages are returned in reverse chronological order (i.e., in order of decreasing message_id). For optimal performance, the number of returned messages is chosen by TDLib
    /// </summary>
    public Task<TdLib.TdApi.Objects.Messages> GetMessageThreadHistoryAsync(long chatId = default, long messageId = default, long fromMessageId = default, int offset = default, int limit = default)
    {

           using var activity =  StartCallActivity("GetMessageThreadHistoryAsync", typeof(GetMessageThreadHistory).FullName ?? "GetMessageThreadHistoryAsync");

           try
           {
             return client.GetMessageThreadHistoryAsync(chatId, messageId, fromMessageId, offset, limit);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd