// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Replaces text entities with Markdown formatting in a human-friendly format. Entities that can't be represented in Markdown unambiguously are kept as is. Can be called synchronously
    /// </summary>
    public Task<TdLib.TdApi.Objects.FormattedText> GetMarkdownTextAsync(FormattedText text = default)
    {

           using var activity =  StartCallActivity("GetMarkdownTextAsync", typeof(GetMarkdownText).FullName ?? "GetMarkdownTextAsync");

           try
           {
             return client.GetMarkdownTextAsync(text);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd