// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns an HTTPS link to a message in a chat. Available only if messageProperties.can_get_link, or if messageProperties.can_get_media_timestamp_links and a media timestamp link is generated. This is an offline method
    /// </summary>
    public Task<TdLib.TdApi.Objects.MessageLink> GetMessageLinkAsync(long chatId = default, long messageId = default, int mediaTimestamp = default, bool forAlbum = default, bool inMessageThread = default)
    {

           using var activity =  StartCallActivity("GetMessageLinkAsync", typeof(GetMessageLink).FullName ?? "GetMessageLinkAsync");

           try
           {
             return client.GetMessageLinkAsync(chatId, messageId, mediaTimestamp, forAlbum, inMessageThread);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd