// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns information about a file with messages exported from another application
    /// </summary>
    public Task<TdLib.TdApi.Objects.MessageFileType> GetMessageFileTypeAsync(string messageFileHead = default)
    {

           using var activity =  StartCallActivity("GetMessageFileTypeAsync", typeof(GetMessageFileType).FullName ?? "GetMessageFileTypeAsync");

           try
           {
             return client.GetMessageFileTypeAsync(messageFileHead);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd