// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns the list of bots owned by the current user
    /// </summary>
    public Task<TdLib.TdApi.Objects.Users> GetOwnedBotsAsync()
    {

           using var activity =  StartCallActivity("GetOwnedBotsAsync", typeof(GetOwnedBots).FullName ?? "GetOwnedBotsAsync");

           try
           {
             return client.GetOwnedBotsAsync();
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd