// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns the value of an option by its name. (Check the list of available options on https://core.telegram.org/tdlib/options.) Can be called before authorization. Can be called synchronously for options "version" and "commit_hash"
    /// </summary>
    public Task<TdLib.TdApi.Objects.OptionValue> GetOptionAsync(string name = default)
    {

           using var activity =  StartCallActivity("GetOptionAsync", typeof(GetOption).FullName ?? "GetOptionAsync");

           try
           {
             return client.GetOptionAsync(name);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd