// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns sticker sets owned by the current user
    /// </summary>
    public Task<TdLib.TdApi.Objects.StickerSets> GetOwnedStickerSetsAsync(long offsetStickerSetId = default, int limit = default)
    {

           using var activity =  StartCallActivity("GetOwnedStickerSetsAsync", typeof(GetOwnedStickerSets).FullName ?? "GetOwnedStickerSetsAsync");

           try
           {
             return client.GetOwnedStickerSetsAsync(offsetStickerSetId, limit);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd