// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns available options for creating of Telegram Premium giveaway or manual distribution of Telegram Premium among chat members
    /// </summary>
    public Task<TdLib.TdApi.Objects.PremiumGiveawayPaymentOptions> GetPremiumGiveawayPaymentOptionsAsync(long boostedChatId = default)
    {

           using var activity =  StartCallActivity("GetPremiumGiveawayPaymentOptionsAsync", typeof(GetPremiumGiveawayPaymentOptions).FullName ?? "GetPremiumGiveawayPaymentOptionsAsync");

           try
           {
             return client.GetPremiumGiveawayPaymentOptionsAsync(boostedChatId);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd