// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Saves an inline message to be sent by the given user
    /// </summary>
    public Task<TdLib.TdApi.Objects.PreparedInlineMessage> GetPreparedInlineMessageAsync(long botUserId = default, string preparedMessageId = default)
    {

           using var activity =  StartCallActivity("GetPreparedInlineMessageAsync", typeof(GetPreparedInlineMessage).FullName ?? "GetPreparedInlineMessageAsync");

           try
           {
             return client.GetPreparedInlineMessageAsync(botUserId, preparedMessageId);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd