// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns examples of premium stickers for demonstration purposes
    /// </summary>
    public Task<TdLib.TdApi.Objects.Stickers> GetPremiumStickerExamplesAsync()
    {

           using var activity =  StartCallActivity("GetPremiumStickerExamplesAsync", typeof(GetPremiumStickerExamples).FullName ?? "GetPremiumStickerExamplesAsync");

           try
           {
             return client.GetPremiumStickerExamplesAsync();
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd