// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns an IETF language tag of the language preferred in the country, which must be used to fill native fields in Telegram Passport personal details. Returns a 404 error if unknown
    /// </summary>
    public Task<TdLib.TdApi.Objects.Text> GetPreferredCountryLanguageAsync(string countryCode = default)
    {

           using var activity =  StartCallActivity("GetPreferredCountryLanguageAsync", typeof(GetPreferredCountryLanguage).FullName ?? "GetPreferredCountryLanguageAsync");

           try
           {
             return client.GetPreferredCountryLanguageAsync(countryCode);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd