// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns available options for gifting Telegram Premium to a user
    /// </summary>
    public Task<TdLib.TdApi.Objects.PremiumGiftPaymentOptions> GetPremiumGiftPaymentOptionsAsync()
    {

           using var activity =  StartCallActivity("GetPremiumGiftPaymentOptionsAsync", typeof(GetPremiumGiftPaymentOptions).FullName ?? "GetPremiumGiftPaymentOptionsAsync");

           try
           {
             return client.GetPremiumGiftPaymentOptionsAsync();
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd