// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns information about a successful payment
    /// </summary>
    public Task<TdLib.TdApi.Objects.PaymentReceipt> GetPaymentReceiptAsync(long chatId = default, long messageId = default)
    {

           using var activity =  StartCallActivity("GetPaymentReceiptAsync", typeof(GetPaymentReceipt).FullName ?? "GetPaymentReceiptAsync");

           try
           {
             return client.GetPaymentReceiptAsync(chatId, messageId);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd