// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns message senders voted for the specified option in a non-anonymous polls. For optimal performance, the number of returned users is chosen by TDLib
    /// </summary>
    public Task<TdLib.TdApi.Objects.PollVoters> GetPollVotersAsync(long chatId = default, long messageId = default, int optionId = default, int offset = default, int limit = default)
    {

           using var activity =  StartCallActivity("GetPollVotersAsync", typeof(GetPollVoters).FullName ?? "GetPollVotersAsync");

           try
           {
             return client.GetPollVotersAsync(chatId, messageId, optionId, offset, limit);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd