// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns already available Telegram Passport elements suitable for completing a Telegram Passport authorization form. Result can be received only once for each authorization form
    /// </summary>
    public Task<TdLib.TdApi.Objects.PassportElementsWithErrors> GetPassportAuthorizationFormAvailableElementsAsync(int authorizationFormId = default, string password = default)
    {

           using var activity =  StartCallActivity("GetPassportAuthorizationFormAvailableElementsAsync", typeof(GetPassportAuthorizationFormAvailableElements).FullName ?? "GetPassportAuthorizationFormAvailableElementsAsync");

           try
           {
             return client.GetPassportAuthorizationFormAvailableElementsAsync(authorizationFormId, password);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd