// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns information about a phone number by its prefix. Can be called before authorization
    /// </summary>
    public Task<TdLib.TdApi.Objects.PhoneNumberInfo> GetPhoneNumberInfoAsync(string phoneNumberPrefix = default)
    {

           using var activity =  StartCallActivity("GetPhoneNumberInfoAsync", typeof(GetPhoneNumberInfo).FullName ?? "GetPhoneNumberInfoAsync");

           try
           {
             return client.GetPhoneNumberInfoAsync(phoneNumberPrefix);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd