// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns the current state of 2-step verification
    /// </summary>
    public Task<TdLib.TdApi.Objects.PasswordState> GetPasswordStateAsync()
    {

           using var activity =  StartCallActivity("GetPasswordStateAsync", typeof(GetPasswordState).FullName ?? "GetPasswordStateAsync");

           try
           {
             return client.GetPasswordStateAsync();
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd