// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns the total number of Telegram Stars received by the current user for paid messages from the given user
    /// </summary>
    public Task<TdLib.TdApi.Objects.StarCount> GetPaidMessageRevenueAsync(long userId = default)
    {

           using var activity =  StartCallActivity("GetPaidMessageRevenueAsync", typeof(GetPaidMessageRevenue).FullName ?? "GetPaidMessageRevenueAsync");

           try
           {
             return client.GetPaidMessageRevenueAsync(userId);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd