// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns parameters for creating of a new passkey as JSON-serialized string
    /// </summary>
    public Task<TdLib.TdApi.Objects.Text> GetPasskeyParametersAsync()
    {

           using var activity =  StartCallActivity("GetPasskeyParametersAsync", typeof(GetPasskeyParameters).FullName ?? "GetPasskeyParametersAsync");

           try
           {
             return client.GetPasskeyParametersAsync();
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd