// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns one of the available Telegram Passport elements
    /// </summary>
    public Task<TdLib.TdApi.Objects.PassportElement> GetPassportElementAsync(PassportElementType type = default, string password = default)
    {

           using var activity =  StartCallActivity("GetPassportElementAsync", typeof(GetPassportElement).FullName ?? "GetPassportElementAsync");

           try
           {
             return client.GetPassportElementAsync(type, password);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd