// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns recommended chat folders for the current user
    /// </summary>
    public Task<TdLib.TdApi.Objects.RecommendedChatFolders> GetRecommendedChatFoldersAsync()
    {

           using var activity =  StartCallActivity("GetRecommendedChatFoldersAsync", typeof(GetRecommendedChatFolders).FullName ?? "GetRecommendedChatFoldersAsync");

           try
           {
             return client.GetRecommendedChatFoldersAsync();
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd