// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns a list of channel chats recommended to the current user
    /// </summary>
    public Task<TdLib.TdApi.Objects.Chats> GetRecommendedChatsAsync()
    {

           using var activity =  StartCallActivity("GetRecommendedChatsAsync", typeof(GetRecommendedChats).FullName ?? "GetRecommendedChatsAsync");

           try
           {
             return client.GetRecommendedChatsAsync();
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd