// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns information about a non-bundled message that is replied by a given message. Also, returns the pinned message for messagePinMessage,
    /// the game message for messageGameScore, the invoice message for messagePaymentSuccessful, the message with a previously set same background for messageChatSetBackground,
    /// the giveaway message for messageGiveawayCompleted, the checklist message for messageChecklistTasksDone, messageChecklistTasksAdded, the message with suggested post information
    /// for messageSuggestedPostApprovalFailed, messageSuggestedPostApproved, messageSuggestedPostDeclined, messageSuggestedPostPaid, messageSuggestedPostRefunded,
    /// the message with the regular gift that was upgraded for messageUpgradedGift with origin of the type upgradedGiftOriginUpgrade,
    /// the message with gift purchase offer for messageUpgradedGiftPurchaseOfferRejected,
    /// the message with the request to disable content protection for messageChatHasProtectedContentToggled,
    /// and the topic creation message for topic messages without non-bundled replied message. Returns a 404 error if the message doesn't exist
    /// </summary>
    public Task<TdLib.TdApi.Objects.Message> GetRepliedMessageAsync(long chatId = default, long messageId = default)
    {

           using var activity =  StartCallActivity("GetRepliedMessageAsync", typeof(GetRepliedMessage).FullName ?? "GetRepliedMessageAsync");

           try
           {
             return client.GetRepliedMessageAsync(chatId, messageId);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd