// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns recent emoji statuses for self status
    /// </summary>
    public Task<TdLib.TdApi.Objects.EmojiStatuses> GetRecentEmojiStatusesAsync()
    {

           using var activity =  StartCallActivity("GetRecentEmojiStatusesAsync", typeof(GetRecentEmojiStatuses).FullName ?? "GetRecentEmojiStatusesAsync");

           try
           {
             return client.GetRecentEmojiStatusesAsync();
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd