// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns privacy settings for message read date
    /// </summary>
    public Task<TdLib.TdApi.Objects.ReadDatePrivacySettings> GetReadDatePrivacySettingsAsync()
    {

           using var activity =  StartCallActivity("GetReadDatePrivacySettingsAsync", typeof(GetReadDatePrivacySettings).FullName ?? "GetReadDatePrivacySettingsAsync");

           try
           {
             return client.GetReadDatePrivacySettingsAsync();
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd