// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns information about a received gift
    /// </summary>
    public Task<TdLib.TdApi.Objects.ReceivedGift> GetReceivedGiftAsync(string receivedGiftId = default)
    {

           using var activity =  StartCallActivity("GetReceivedGiftAsync", typeof(GetReceivedGift).FullName ?? "GetReceivedGiftAsync");

           try
           {
             return client.GetReceivedGiftAsync(receivedGiftId);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd