// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns available options for Telegram Star giveaway creation
    /// </summary>
    public Task<TdLib.TdApi.Objects.StarGiveawayPaymentOptions> GetStarGiveawayPaymentOptionsAsync()
    {

           using var activity =  StartCallActivity("GetStarGiveawayPaymentOptionsAsync", typeof(GetStarGiveawayPaymentOptions).FullName ?? "GetStarGiveawayPaymentOptionsAsync");

           try
           {
             return client.GetStarGiveawayPaymentOptionsAsync();
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd