// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns available options for Telegram Stars gifting
    /// </summary>
    public Task<TdLib.TdApi.Objects.StarPaymentOptions> GetStarGiftPaymentOptionsAsync(long userId = default)
    {

           using var activity =  StartCallActivity("GetStarGiftPaymentOptionsAsync", typeof(GetStarGiftPaymentOptions).FullName ?? "GetStarGiftPaymentOptionsAsync");

           try
           {
             return client.GetStarGiftPaymentOptionsAsync(userId);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd