// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns name of a sticker set by its identifier
    /// </summary>
    public Task<TdLib.TdApi.Objects.Text> GetStickerSetNameAsync(long setId = default)
    {

           using var activity =  StartCallActivity("GetStickerSetNameAsync", typeof(GetStickerSetName).FullName ?? "GetStickerSetNameAsync");

           try
           {
             return client.GetStickerSetNameAsync(setId);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd