// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns detailed statistics about a story. Can be used only if story.can_get_statistics == true
    /// </summary>
    public Task<TdLib.TdApi.Objects.StoryStatistics> GetStoryStatisticsAsync(long chatId = default, int storyId = default, bool isDark = default)
    {

           using var activity =  StartCallActivity("GetStoryStatisticsAsync", typeof(GetStoryStatistics).FullName ?? "GetStoryStatisticsAsync");

           try
           {
             return client.GetStoryStatisticsAsync(chatId, storyId, isDark);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd