// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns emoji corresponding to a sticker. The list is only for informational purposes, because a sticker is always sent with a fixed emoji from the corresponding Sticker object
    /// </summary>
    public Task<TdLib.TdApi.Objects.Emojis> GetStickerEmojisAsync(InputFile sticker = default)
    {

           using var activity =  StartCallActivity("GetStickerEmojisAsync", typeof(GetStickerEmojis).FullName ?? "GetStickerEmojisAsync");

           try
           {
             return client.GetStickerEmojisAsync(sticker);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd