// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns sponsored chats to be shown in the search results
    /// </summary>
    public Task<TdLib.TdApi.Objects.SponsoredChats> GetSearchSponsoredChatsAsync(string query = default)
    {

           using var activity =  StartCallActivity("GetSearchSponsoredChatsAsync", typeof(GetSearchSponsoredChats).FullName ?? "GetSearchSponsoredChatsAsync");

           try
           {
             return client.GetSearchSponsoredChatsAsync(query);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd