// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns information about members or banned users in a supergroup or channel. Can be used only if supergroupFullInfo.can_get_members == true; additionally, administrator privileges may be required for some filters
    /// </summary>
    public Task<TdLib.TdApi.Objects.ChatMembers> GetSupergroupMembersAsync(long supergroupId = default, SupergroupMembersFilter filter = default, int offset = default, int limit = default)
    {

           using var activity =  StartCallActivity("GetSupergroupMembersAsync", typeof(GetSupergroupMembers).FullName ?? "GetSupergroupMembersAsync");

           try
           {
             return client.GetSupergroupMembersAsync(supergroupId, filter, offset, limit);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd