// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns recently searched for hashtags or cashtags by their prefix
    /// </summary>
    public Task<TdLib.TdApi.Objects.Hashtags> GetSearchedForTagsAsync(string tagPrefix = default, int limit = default)
    {

           using var activity =  StartCallActivity("GetSearchedForTagsAsync", typeof(GetSearchedForTags).FullName ?? "GetSearchedForTagsAsync");

           try
           {
             return client.GetSearchedForTagsAsync(tagPrefix, limit);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd