// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns the list of Telegram Star subscriptions for the current user
    /// </summary>
    public Task<TdLib.TdApi.Objects.StarSubscriptions> GetStarSubscriptionsAsync(bool onlyExpiring = default, string offset = default)
    {

           using var activity =  StartCallActivity("GetStarSubscriptionsAsync", typeof(GetStarSubscriptions).FullName ?? "GetStarSubscriptionsAsync");

           try
           {
             return client.GetStarSubscriptionsAsync(onlyExpiring, offset);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd