// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns the list of saved notification sounds. If a sound isn't in the list, then default sound needs to be used
    /// </summary>
    public Task<TdLib.TdApi.Objects.NotificationSounds> GetSavedNotificationSoundsAsync()
    {

           using var activity =  StartCallActivity("GetSavedNotificationSoundsAsync", typeof(GetSavedNotificationSounds).FullName ?? "GetSavedNotificationSoundsAsync");

           try
           {
             return client.GetSavedNotificationSoundsAsync();
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd