// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns the last message sent in a Saved Messages topic no later than the specified date
    /// </summary>
    public Task<TdLib.TdApi.Objects.Message> GetSavedMessagesTopicMessageByDateAsync(long savedMessagesTopicId = default, int date = default)
    {

           using var activity =  StartCallActivity("GetSavedMessagesTopicMessageByDateAsync", typeof(GetSavedMessagesTopicMessageByDate).FullName ?? "GetSavedMessagesTopicMessageByDateAsync");

           try
           {
             return client.GetSavedMessagesTopicMessageByDateAsync(savedMessagesTopicId, date);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd