// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Quickly returns approximate storage usage statistics. Can be called before authorization
    /// </summary>
    public Task<TdLib.TdApi.Objects.StorageStatisticsFast> GetStorageStatisticsFastAsync()
    {

           using var activity =  StartCallActivity("GetStorageStatisticsFastAsync", typeof(GetStorageStatisticsFast).FullName ?? "GetStorageStatisticsFastAsync");

           try
           {
             return client.GetStorageStatisticsFastAsync();
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd