// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns saved order information. Returns a 404 error if there is no saved order information
    /// </summary>
    public Task<TdLib.TdApi.Objects.OrderInfo> GetSavedOrderInfoAsync()
    {

           using var activity =  StartCallActivity("GetSavedOrderInfoAsync", typeof(GetSavedOrderInfo).FullName ?? "GetSavedOrderInfoAsync");

           try
           {
             return client.GetSavedOrderInfoAsync();
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd