// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns stickers from the installed sticker sets that correspond to any of the given emoji or can be found by sticker-specific keywords. If the query is non-empty, then favorite, recently used or trending stickers may also be returned
    /// </summary>
    public Task<TdLib.TdApi.Objects.Stickers> GetStickersAsync(StickerType stickerType = default, string query = default, int limit = default, long chatId = default)
    {

           using var activity =  StartCallActivity("GetStickersAsync", typeof(GetStickers).FullName ?? "GetStickersAsync");

           try
           {
             return client.GetStickersAsync(stickerType, query, limit, chatId);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd