// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns the list of chats with non-default notification settings for stories
    /// </summary>
    public Task<TdLib.TdApi.Objects.Chats> GetStoryNotificationSettingsExceptionsAsync()
    {

           using var activity =  StartCallActivity("GetStoryNotificationSettingsExceptionsAsync", typeof(GetStoryNotificationSettingsExceptions).FullName ?? "GetStoryNotificationSettingsExceptionsAsync");

           try
           {
             return client.GetStoryNotificationSettingsExceptionsAsync();
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd