// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns outline of a sticker as an SVG path. This is an offline method. Returns an empty string if the outline isn't known
    /// </summary>
    public Task<TdLib.TdApi.Objects.Text> GetStickerOutlineSvgPathAsync(int stickerFileId = default, bool forAnimatedEmoji = default, bool forClickedAnimatedEmojiMessage = default)
    {

           using var activity =  StartCallActivity("GetStickerOutlineSvgPathAsync", typeof(GetStickerOutlineSvgPath).FullName ?? "GetStickerOutlineSvgPathAsync");

           try
           {
             return client.GetStickerOutlineSvgPathAsync(stickerFileId, forAnimatedEmoji, forClickedAnimatedEmojiMessage);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd