// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns a list of basic group and supergroup chats, which can be used as a discussion group for a channel. Returned basic group chats must be first upgraded to supergroups before they can be set as a discussion group.
    /// To set a returned supergroup as a discussion group, access to its old messages must be enabled using toggleSupergroupIsAllHistoryAvailable first
    /// </summary>
    public Task<TdLib.TdApi.Objects.Chats> GetSuitableDiscussionChatsAsync()
    {

           using var activity =  StartCallActivity("GetSuitableDiscussionChatsAsync", typeof(GetSuitableDiscussionChats).FullName ?? "GetSuitableDiscussionChatsAsync");

           try
           {
             return client.GetSuitableDiscussionChatsAsync();
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd