// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns information about a supergroup or a channel by its identifier. This is an offline method if the current user is not a bot
    /// </summary>
    public Task<TdLib.TdApi.Objects.Supergroup> GetSupergroupAsync(long supergroupId = default)
    {

           using var activity =  StartCallActivity("GetSupergroupAsync", typeof(GetSupergroup).FullName ?? "GetSupergroupAsync");

           try
           {
             return client.GetSupergroupAsync(supergroupId);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd