// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns a URL for a Telegram Ad platform account that can be used to set up advertisements for the chat paid in the owned Telegram Stars
    /// </summary>
    public Task<TdLib.TdApi.Objects.HttpUrl> GetStarAdAccountUrlAsync(MessageSender ownerId = default)
    {

           using var activity =  StartCallActivity("GetStarAdAccountUrlAsync", typeof(GetStarAdAccountUrl).FullName ?? "GetStarAdAccountUrlAsync");

           try
           {
             return client.GetStarAdAccountUrlAsync(ownerId);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd