// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns saved animations
    /// </summary>
    public Task<TdLib.TdApi.Objects.Animations> GetSavedAnimationsAsync()
    {

           using var activity =  StartCallActivity("GetSavedAnimationsAsync", typeof(GetSavedAnimations).FullName ?? "GetSavedAnimationsAsync");

           try
           {
             return client.GetSavedAnimationsAsync();
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd