// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns information about a secret chat by its identifier. This is an offline method
    /// </summary>
    public Task<TdLib.TdApi.Objects.SecretChat> GetSecretChatAsync(int secretChatId = default)
    {

           using var activity =  StartCallActivity("GetSecretChatAsync", typeof(GetSecretChat).FullName ?? "GetSecretChatAsync");

           try
           {
             return client.GetSecretChatAsync(secretChatId);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd