// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns outline of a sticker. This is an offline method. Returns a 404 error if the outline isn't known
    /// </summary>
    public Task<TdLib.TdApi.Objects.Outline> GetStickerOutlineAsync(int stickerFileId = default, bool forAnimatedEmoji = default, bool forClickedAnimatedEmojiMessage = default)
    {

           using var activity =  StartCallActivity("GetStickerOutlineAsync", typeof(GetStickerOutline).FullName ?? "GetStickerOutlineAsync");

           try
           {
             return client.GetStickerOutlineAsync(stickerFileId, forAnimatedEmoji, forClickedAnimatedEmojiMessage);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd