// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns interactions with a story. The method can be called only for stories posted on behalf of the current user
    /// </summary>
    public Task<TdLib.TdApi.Objects.StoryInteractions> GetStoryInteractionsAsync(int storyId = default, string query = default, bool onlyContacts = default, bool preferForwards = default, bool preferWithReaction = default, string offset = default, int limit = default)
    {

           using var activity =  StartCallActivity("GetStoryInteractionsAsync", typeof(GetStoryInteractions).FullName ?? "GetStoryInteractionsAsync");

           try
           {
             return client.GetStoryInteractionsAsync(storyId, query, onlyContacts, preferForwards, preferWithReaction, offset, limit);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd