// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns a URL for Telegram Star withdrawal
    /// </summary>
    public Task<TdLib.TdApi.Objects.HttpUrl> GetStarWithdrawalUrlAsync(MessageSender ownerId = default, long starCount = default, string password = default)
    {

           using var activity =  StartCallActivity("GetStarWithdrawalUrlAsync", typeof(GetStarWithdrawalUrl).FullName ?? "GetStarWithdrawalUrlAsync");

           try
           {
             return client.GetStarWithdrawalUrlAsync(ownerId, starCount, password);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd