// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns a list of trending sticker sets. For optimal performance, the number of returned sticker sets is chosen by TDLib
    /// </summary>
    public Task<TdLib.TdApi.Objects.TrendingStickerSets> GetTrendingStickerSetsAsync(StickerType stickerType = default, int offset = default, int limit = default)
    {

           using var activity =  StartCallActivity("GetTrendingStickerSetsAsync", typeof(GetTrendingStickerSets).FullName ?? "GetTrendingStickerSetsAsync");

           try
           {
             return client.GetTrendingStickerSetsAsync(stickerType, offset, limit);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd