// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns up to 8 emoji statuses, which must be shown in the emoji status list for chats
    /// </summary>
    public Task<TdLib.TdApi.Objects.EmojiStatusCustomEmojis> GetThemedChatEmojiStatusesAsync()
    {

           using var activity =  StartCallActivity("GetThemedChatEmojiStatusesAsync", typeof(GetThemedChatEmojiStatuses).FullName ?? "GetThemedChatEmojiStatusesAsync");

           try
           {
             return client.GetThemedChatEmojiStatusesAsync();
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd