// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns the list of Toncoin transactions of the current user
    /// </summary>
    public Task<TdLib.TdApi.Objects.TonTransactions> GetTonTransactionsAsync(TransactionDirection direction = default, string offset = default, int limit = default)
    {

           using var activity =  StartCallActivity("GetTonTransactionsAsync", typeof(GetTonTransactions).FullName ?? "GetTonTransactionsAsync");

           try
           {
             return client.GetTonTransactionsAsync(direction, offset, limit);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd