// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns the list of supported time zones
    /// </summary>
    public Task<TdLib.TdApi.Objects.TimeZones> GetTimeZonesAsync()
    {

           using var activity =  StartCallActivity("GetTimeZonesAsync", typeof(GetTimeZones).FullName ?? "GetTimeZonesAsync");

           try
           {
             return client.GetTimeZonesAsync();
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd