// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns information about the current temporary password
    /// </summary>
    public Task<TdLib.TdApi.Objects.TemporaryPasswordState> GetTemporaryPasswordStateAsync()
    {

           using var activity =  StartCallActivity("GetTemporaryPasswordStateAsync", typeof(GetTemporaryPasswordState).FullName ?? "GetTemporaryPasswordStateAsync");

           try
           {
             return client.GetTemporaryPasswordStateAsync();
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd