// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns a list of frequently used chats
    /// </summary>
    public Task<TdLib.TdApi.Objects.Chats> GetTopChatsAsync(TopChatCategory category = default, int limit = default)
    {

           using var activity =  StartCallActivity("GetTopChatsAsync", typeof(GetTopChats).FullName ?? "GetTopChatsAsync");

           try
           {
             return client.GetTopChatsAsync(category, limit);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd