// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns a URL for upgraded gift withdrawal in the TON blockchain as an NFT; requires owner privileges for gifts owned by a chat
    /// </summary>
    public Task<TdLib.TdApi.Objects.HttpUrl> GetUpgradedGiftWithdrawalUrlAsync(string receivedGiftId = default, string password = default)
    {

           using var activity =  StartCallActivity("GetUpgradedGiftWithdrawalUrlAsync", typeof(GetUpgradedGiftWithdrawalUrl).FullName ?? "GetUpgradedGiftWithdrawalUrlAsync");

           try
           {
             return client.GetUpgradedGiftWithdrawalUrlAsync(receivedGiftId, password);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd