// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns information about an upgraded gift by its name
    /// </summary>
    public Task<TdLib.TdApi.Objects.UpgradedGift> GetUpgradedGiftAsync(string name = default)
    {

           using var activity =  StartCallActivity("GetUpgradedGiftAsync", typeof(GetUpgradedGift).FullName ?? "GetUpgradedGiftAsync");

           try
           {
             return client.GetUpgradedGiftAsync(name);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd