// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns all possible variants of upgraded gifts for a regular gift
    /// </summary>
    public Task<TdLib.TdApi.Objects.GiftUpgradeVariants> GetUpgradedGiftVariantsAsync(long regularGiftId = default, bool returnUpgradeModels = default, bool returnCraftModels = default)
    {

           using var activity =  StartCallActivity("GetUpgradedGiftVariantsAsync", typeof(GetUpgradedGiftVariants).FullName ?? "GetUpgradedGiftVariantsAsync");

           try
           {
             return client.GetUpgradedGiftVariantsAsync(regularGiftId, returnUpgradeModels, returnCraftModels);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd