// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns an HTTPS link, which can be used to get information about the current user
    /// </summary>
    public Task<TdLib.TdApi.Objects.UserLink> GetUserLinkAsync()
    {

           using var activity =  StartCallActivity("GetUserLinkAsync", typeof(GetUserLink).FullName ?? "GetUserLinkAsync");

           try
           {
             return client.GetUserLinkAsync();
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd