// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns the list of boosts applied to a chat by a given user; requires administrator rights in the chat; for bots only
    /// </summary>
    public Task<TdLib.TdApi.Objects.FoundChatBoosts> GetUserChatBoostsAsync(long chatId = default, long userId = default)
    {

           using var activity =  StartCallActivity("GetUserChatBoostsAsync", typeof(GetUserChatBoosts).FullName ?? "GetUserChatBoostsAsync");

           try
           {
             return client.GetUserChatBoostsAsync(chatId, userId);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd