// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns promotional anumation for upgraded gifts
    /// </summary>
    public Task<TdLib.TdApi.Objects.Animation> GetUpgradedGiftsPromotionalAnimationAsync()
    {

           using var activity =  StartCallActivity("GetUpgradedGiftsPromotionalAnimationAsync", typeof(GetUpgradedGiftsPromotionalAnimation).FullName ?? "GetUpgradedGiftsPromotionalAnimationAsync");

           try
           {
             return client.GetUpgradedGiftsPromotionalAnimationAsync();
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd