// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns information about value of an upgraded gift by its name
    /// </summary>
    public Task<TdLib.TdApi.Objects.UpgradedGiftValueInfo> GetUpgradedGiftValueInfoAsync(string name = default)
    {

           using var activity =  StartCallActivity("GetUpgradedGiftValueInfoAsync", typeof(GetUpgradedGiftValueInfo).FullName ?? "GetUpgradedGiftValueInfoAsync");

           try
           {
             return client.GetUpgradedGiftValueInfoAsync(name);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd