// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns full information about a user by their identifier
    /// </summary>
    public Task<TdLib.TdApi.Objects.UserFullInfo> GetUserFullInfoAsync(long userId = default)
    {

           using var activity =  StartCallActivity("GetUserFullInfoAsync", typeof(GetUserFullInfo).FullName ?? "GetUserFullInfoAsync");

           try
           {
             return client.GetUserFullInfoAsync(userId);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd