// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns advertisements to be shown while a video from a message is watched. Available only if messageProperties.can_get_video_advertisements
    /// </summary>
    public Task<TdLib.TdApi.Objects.VideoMessageAdvertisements> GetVideoMessageAdvertisementsAsync(long chatId = default, long messageId = default)
    {

           using var activity =  StartCallActivity("GetVideoMessageAdvertisementsAsync", typeof(GetVideoMessageAdvertisements).FullName ?? "GetVideoMessageAdvertisementsAsync");

           try
           {
             return client.GetVideoMessageAdvertisementsAsync(chatId, messageId);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd