// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns RTMP URL for streaming to the video chat of a chat; requires can_manage_video_chats administrator right
    /// </summary>
    public Task<TdLib.TdApi.Objects.RtmpUrl> GetVideoChatRtmpUrlAsync(long chatId = default)
    {

           using var activity =  StartCallActivity("GetVideoChatRtmpUrlAsync", typeof(GetVideoChatRtmpUrl).FullName ?? "GetVideoChatRtmpUrlAsync");

           try
           {
             return client.GetVideoChatRtmpUrlAsync(chatId);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd