// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns invite link to a video chat in a public chat
    /// </summary>
    public Task<TdLib.TdApi.Objects.HttpUrl> GetVideoChatInviteLinkAsync(int groupCallId = default, bool canSelfUnmute = default)
    {

           using var activity =  StartCallActivity("GetVideoChatInviteLinkAsync", typeof(GetVideoChatInviteLink).FullName ?? "GetVideoChatInviteLinkAsync");

           try
           {
             return client.GetVideoChatInviteLinkAsync(groupCallId, canSelfUnmute);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd