// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns a default placeholder for Web Apps of a bot. This is an offline method. Returns a 404 error if the placeholder isn't known
    /// </summary>
    public Task<TdLib.TdApi.Objects.Outline> GetWebAppPlaceholderAsync(long botUserId = default)
    {

           using var activity =  StartCallActivity("GetWebAppPlaceholderAsync", typeof(GetWebAppPlaceholder).FullName ?? "GetWebAppPlaceholderAsync");

           try
           {
             return client.GetWebAppPlaceholderAsync(botUserId);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd