// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns an HTTPS URL of a Web App to open after a link of the type internalLinkTypeWebApp is clicked
    /// </summary>
    public Task<TdLib.TdApi.Objects.HttpUrl> GetWebAppLinkUrlAsync(long chatId = default, long botUserId = default, string webAppShortName = default, string startParameter = default, bool allowWriteAccess = default, WebAppOpenParameters parameters = default)
    {

           using var activity =  StartCallActivity("GetWebAppLinkUrlAsync", typeof(GetWebAppLinkUrl).FullName ?? "GetWebAppLinkUrlAsync");

           try
           {
             return client.GetWebAppLinkUrlAsync(chatId, botUserId, webAppShortName, startParameter, allowWriteAccess, parameters);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd