// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Hides the list of contacts that have close birthdays for 24 hours
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> HideContactCloseBirthdaysAsync()
    {

           using var activity =  StartCallActivity("HideContactCloseBirthdaysAsync", typeof(HideContactCloseBirthdays).FullName ?? "HideContactCloseBirthdaysAsync");

           try
           {
             return client.HideContactCloseBirthdaysAsync();
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd