// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Hides a suggested action
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> HideSuggestedActionAsync(SuggestedAction action = default)
    {

           using var activity =  StartCallActivity("HideSuggestedActionAsync", typeof(HideSuggestedAction).FullName ?? "HideSuggestedActionAsync");

           try
           {
             return client.HideSuggestedActionAsync(action);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd