// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Adds new contacts or edits existing contacts by their phone numbers; contacts' user identifiers are ignored
    /// </summary>
    public Task<TdLib.TdApi.Objects.ImportedContacts> ImportContactsAsync(ImportedContact[] contacts = default)
    {

           using var activity =  StartCallActivity("ImportContactsAsync", typeof(ImportContacts).FullName ?? "ImportContactsAsync");

           try
           {
             return client.ImportContactsAsync(contacts);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd