// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Invites users to an active video chat. Sends a service message of the type messageInviteVideoChatParticipants to the chat bound to the group call
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> InviteVideoChatParticipantsAsync(int groupCallId = default, long[] userIds = default)
    {

           using var activity =  StartCallActivity("InviteVideoChatParticipantsAsync", typeof(InviteVideoChatParticipants).FullName ?? "InviteVideoChatParticipantsAsync");

           try
           {
             return client.InviteVideoChatParticipantsAsync(groupCallId, userIds);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd