// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Invites a user to an active group call; for group calls not bound to a chat only. Sends a service message of the type messageGroupCall.
    /// The group call can have at most getOption("group_call_participant_count_max") participants
    /// </summary>
    public Task<TdLib.TdApi.Objects.InviteGroupCallParticipantResult> InviteGroupCallParticipantAsync(int groupCallId = default, long userId = default, bool isVideo = default)
    {

           using var activity =  StartCallActivity("InviteGroupCallParticipantAsync", typeof(InviteGroupCallParticipant).FullName ?? "InviteGroupCallParticipantAsync");

           try
           {
             return client.InviteGroupCallParticipantAsync(groupCallId, userId, isVideo);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd