// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Checks whether the current user is required to set login email address
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> IsLoginEmailAddressRequiredAsync()
    {

           using var activity =  StartCallActivity("IsLoginEmailAddressRequiredAsync", typeof(IsLoginEmailAddressRequired).FullName ?? "IsLoginEmailAddressRequiredAsync");

           try
           {
             return client.IsLoginEmailAddressRequiredAsync();
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd