// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Checks whether a file is in the profile audio files of the current user. Returns a 404 error if it isn't
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> IsProfileAudioAsync(int fileId = default)
    {

           using var activity =  StartCallActivity("IsProfileAudioAsync", typeof(IsProfileAudio).FullName ?? "IsProfileAudioAsync");

           try
           {
             return client.IsProfileAudioAsync(fileId);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd