// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Joins an active video chat. Returns join response payload for tgcalls
    /// </summary>
    public Task<TdLib.TdApi.Objects.Text> JoinVideoChatAsync(int groupCallId = default, MessageSender participantId = default, GroupCallJoinParameters joinParameters = default, string inviteHash = default)
    {

           using var activity =  StartCallActivity("JoinVideoChatAsync", typeof(JoinVideoChat).FullName ?? "JoinVideoChatAsync");

           try
           {
             return client.JoinVideoChatAsync(groupCallId, participantId, joinParameters, inviteHash);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd