// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Joins a regular group call that is not bound to a chat
    /// </summary>
    public Task<TdLib.TdApi.Objects.GroupCallInfo> JoinGroupCallAsync(InputGroupCall inputGroupCall = default, GroupCallJoinParameters joinParameters = default)
    {

           using var activity =  StartCallActivity("JoinGroupCallAsync", typeof(JoinGroupCall).FullName ?? "JoinGroupCallAsync");

           try
           {
             return client.JoinGroupCallAsync(inputGroupCall, joinParameters);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd