// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Launches a prepaid giveaway
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> LaunchPrepaidGiveawayAsync(long giveawayId = default, GiveawayParameters parameters = default, int winnerCount = default, long starCount = default)
    {

           using var activity =  StartCallActivity("LaunchPrepaidGiveawayAsync", typeof(LaunchPrepaidGiveaway).FullName ?? "LaunchPrepaidGiveawayAsync");

           try
           {
             return client.LaunchPrepaidGiveawayAsync(giveawayId, parameters, winnerCount, starCount);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd