// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Removes the current user from chat members. Private and secret chats can't be left using this method
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> LeaveChatAsync(long chatId = default)
    {

           using var activity =  StartCallActivity("LeaveChatAsync", typeof(LeaveChat).FullName ?? "LeaveChatAsync");

           try
           {
             return client.LeaveChatAsync(chatId);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd