// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Loads more chats from a chat list. The loaded chats and their positions in the chat list will be sent through updates. Chats are sorted by the pair (chat.position.order, chat.id) in descending order. Returns a 404 error if all chats have been loaded
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> LoadChatsAsync(ChatList chatList = default, int limit = default)
    {

           using var activity =  StartCallActivity("LoadChatsAsync", typeof(LoadChats).FullName ?? "LoadChatsAsync");

           try
           {
             return client.LoadChatsAsync(chatList, limit);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd