// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Loads quick reply messages that can be sent by a given quick reply shortcut. The loaded messages will be sent through updateQuickReplyShortcutMessages
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> LoadQuickReplyShortcutMessagesAsync(int shortcutId = default)
    {

           using var activity =  StartCallActivity("LoadQuickReplyShortcutMessagesAsync", typeof(LoadQuickReplyShortcutMessages).FullName ?? "LoadQuickReplyShortcutMessagesAsync");

           try
           {
             return client.LoadQuickReplyShortcutMessagesAsync(shortcutId);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd