// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Loads more Saved Messages topics. The loaded topics will be sent through updateSavedMessagesTopic. Topics are sorted by their topic.order in descending order. Returns a 404 error if all topics have been loaded
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> LoadSavedMessagesTopicsAsync(int limit = default)
    {

           using var activity =  StartCallActivity("LoadSavedMessagesTopicsAsync", typeof(LoadSavedMessagesTopics).FullName ?? "LoadSavedMessagesTopicsAsync");

           try
           {
             return client.LoadSavedMessagesTopicsAsync(limit);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd