// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Loads quick reply shortcuts created by the current user. The loaded data will be sent through updateQuickReplyShortcut and updateQuickReplyShortcuts
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> LoadQuickReplyShortcutsAsync()
    {

           using var activity =  StartCallActivity("LoadQuickReplyShortcutsAsync", typeof(LoadQuickReplyShortcuts).FullName ?? "LoadQuickReplyShortcutsAsync");

           try
           {
             return client.LoadQuickReplyShortcutsAsync();
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd