// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Adds tasks of a checklist in a message as done or not done
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> MarkChecklistTasksAsDoneAsync(long chatId = default, long messageId = default, int[] markedAsDoneTaskIds = default, int[] markedAsNotDoneTaskIds = default)
    {

           using var activity =  StartCallActivity("MarkChecklistTasksAsDoneAsync", typeof(MarkChecklistTasksAsDone).FullName ?? "MarkChecklistTasksAsDoneAsync");

           try
           {
             return client.MarkChecklistTasksAsDoneAsync(chatId, messageId, markedAsDoneTaskIds, markedAsNotDoneTaskIds);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd