// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Informs TDLib that a gift auction was opened by the user
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> OpenGiftAuctionAsync(long giftId = default)
    {

           using var activity =  StartCallActivity("OpenGiftAuctionAsync", typeof(OpenGiftAuction).FullName ?? "OpenGiftAuctionAsync");

           try
           {
             return client.OpenGiftAuctionAsync(giftId);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd