// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Informs TDLib that a chat was opened from the list of similar chats. The method is independent of openChat and closeChat methods
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> OpenChatSimilarChatAsync(long chatId = default, long openedChatId = default)
    {

           using var activity =  StartCallActivity("OpenChatSimilarChatAsync", typeof(OpenChatSimilarChat).FullName ?? "OpenChatSimilarChatAsync");

           try
           {
             return client.OpenChatSimilarChatAsync(chatId, openedChatId);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd