// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Informs TDLib that a bot was opened from the list of similar bots
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> OpenBotSimilarBotAsync(long botUserId = default, long openedBotUserId = default)
    {

           using var activity =  StartCallActivity("OpenBotSimilarBotAsync", typeof(OpenBotSimilarBot).FullName ?? "OpenBotSimilarBotAsync");

           try
           {
             return client.OpenBotSimilarBotAsync(botUserId, openedBotUserId);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd