// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Parses Bold, Italic, Underline, Strikethrough, Spoiler, CustomEmoji, BlockQuote, ExpandableBlockQuote, Code, Pre, PreCode, TextUrl
    /// and MentionName entities from a marked-up text. Can be called synchronously
    /// </summary>
    public Task<TdLib.TdApi.Objects.FormattedText> ParseTextEntitiesAsync(string text = default, TextParseMode parseMode = default)
    {

           using var activity =  StartCallActivity("ParseTextEntitiesAsync", typeof(ParseTextEntities).FullName ?? "ParseTextEntitiesAsync");

           try
           {
             return client.ParseTextEntitiesAsync(text, parseMode);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd