// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Parses Markdown entities in a human-friendly format, ignoring markup errors. Can be called synchronously
    /// </summary>
    public Task<TdLib.TdApi.Objects.FormattedText> ParseMarkdownAsync(FormattedText text = default)
    {

           using var activity =  StartCallActivity("ParseMarkdownAsync", typeof(ParseMarkdown).FullName ?? "ParseMarkdownAsync");

           try
           {
             return client.ParseMarkdownAsync(text);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd