// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Places a bid on an auction gift
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> PlaceGiftAuctionBidAsync(long giftId = default, long starCount = default, long userId = default, FormattedText text = default, bool isPrivate = default)
    {

           using var activity =  StartCallActivity("PlaceGiftAuctionBidAsync", typeof(PlaceGiftAuctionBid).FullName ?? "PlaceGiftAuctionBidAsync");

           try
           {
             return client.PlaceGiftAuctionBidAsync(giftId, starCount, userId, text, isPrivate);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd