// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Handles all pending join requests for a given link in a chat
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> ProcessChatJoinRequestsAsync(long chatId = default, string inviteLink = default, bool approve = default)
    {

           using var activity =  StartCallActivity("ProcessChatJoinRequestsAsync", typeof(ProcessChatJoinRequests).FullName ?? "ProcessChatJoinRequestsAsync");

           try
           {
             return client.ProcessChatJoinRequestsAsync(chatId, inviteLink, approve);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd