// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Processes request to disable has_protected_content in a chat
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> ProcessChatHasProtectedContentDisableRequestAsync(long chatId = default, long requestMessageId = default, bool approve = default)
    {

           using var activity =  StartCallActivity("ProcessChatHasProtectedContentDisableRequestAsync", typeof(ProcessChatHasProtectedContentDisableRequest).FullName ?? "ProcessChatHasProtectedContentDisableRequestAsync");

           try
           {
             return client.ProcessChatHasProtectedContentDisableRequestAsync(chatId, requestMessageId, approve);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd