// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Rates recognized speech in a video note or a voice note message
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> RateSpeechRecognitionAsync(long chatId = default, long messageId = default, bool isGood = default)
    {

           using var activity =  StartCallActivity("RateSpeechRecognitionAsync", typeof(RateSpeechRecognition).FullName ?? "RateSpeechRecognitionAsync");

           try
           {
             return client.RateSpeechRecognitionAsync(chatId, messageId, isGood);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd