// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Marks all mentions in a chat as read
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> ReadAllChatMentionsAsync(long chatId = default)
    {

           using var activity =  StartCallActivity("ReadAllChatMentionsAsync", typeof(ReadAllChatMentions).FullName ?? "ReadAllChatMentionsAsync");

           try
           {
             return client.ReadAllChatMentionsAsync(chatId);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd