// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Traverses all chats in a chat list and marks all messages in the chats as read
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> ReadChatListAsync(ChatList chatList = default)
    {

           using var activity =  StartCallActivity("ReadChatListAsync", typeof(ReadChatList).FullName ?? "ReadChatListAsync");

           try
           {
             return client.ReadChatListAsync(chatList);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd