// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Reads a part of a file from the TDLib file cache and returns read bytes. This method is intended to be used only if the application has no direct access to TDLib's file system, because it is usually slower than a direct read from the file
    /// </summary>
    public Task<TdLib.TdApi.Objects.Data> ReadFilePartAsync(int fileId = default, long offset = default, long count = default)
    {

           using var activity =  StartCallActivity("ReadFilePartAsync", typeof(ReadFilePart).FullName ?? "ReadFilePartAsync");

           try
           {
             return client.ReadFilePartAsync(fileId, offset, count);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd