// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Marks all reactions in a topic in a forum supergroup chat or a chat with a bot with topics as read
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> ReadAllForumTopicReactionsAsync(long chatId = default, int forumTopicId = default)
    {

           using var activity =  StartCallActivity("ReadAllForumTopicReactionsAsync", typeof(ReadAllForumTopicReactions).FullName ?? "ReadAllForumTopicReactionsAsync");

           try
           {
             return client.ReadAllForumTopicReactionsAsync(chatId, forumTopicId);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd