// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Marks all reactions in a chat as read
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> ReadAllChatReactionsAsync(long chatId = default)
    {

           using var activity =  StartCallActivity("ReadAllChatReactionsAsync", typeof(ReadAllChatReactions).FullName ?? "ReadAllChatReactionsAsync");

           try
           {
             return client.ReadAllChatReactionsAsync(chatId);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd