// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Refunds a previously done payment in Telegram Stars; for bots only
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> RefundStarPaymentAsync(long userId = default, string telegramPaymentChargeId = default)
    {

           using var activity =  StartCallActivity("RefundStarPaymentAsync", typeof(RefundStarPayment).FullName ?? "RefundStarPaymentAsync");

           try
           {
             return client.RefundStarPaymentAsync(userId, telegramPaymentChargeId);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd