// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Finishes user registration. Works only when the current authorization state is authorizationStateWaitRegistration
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> RegisterUserAsync(string firstName = default, string lastName = default, bool disableNotification = default)
    {

           using var activity =  StartCallActivity("RegisterUserAsync", typeof(RegisterUser).FullName ?? "RegisterUserAsync");

           try
           {
             return client.RegisterUserAsync(firstName, lastName, disableNotification);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd