// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Removes an active notification from notification list. Needs to be called only if the notification is removed by the current user
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> RemoveNotificationAsync(int notificationGroupId = default, int notificationId = default)
    {

           using var activity =  StartCallActivity("RemoveNotificationAsync", typeof(RemoveNotification).FullName ?? "RemoveNotificationAsync");

           try
           {
             return client.RemoveNotificationAsync(notificationGroupId, notificationId);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd