// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Removes a sticker from the set to which it belongs. The sticker set must be owned by the current user
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> RemoveStickerFromSetAsync(InputFile sticker = default)
    {

           using var activity =  StartCallActivity("RemoveStickerFromSetAsync", typeof(RemoveStickerFromSet).FullName ?? "RemoveStickerFromSetAsync");

           try
           {
             return client.RemoveStickerFromSetAsync(sticker);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd