// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Removes a proxy server. Can be called before authorization
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> RemoveProxyAsync(int proxyId = default)
    {

           using var activity =  StartCallActivity("RemoveProxyAsync", typeof(RemoveProxy).FullName ?? "RemoveProxyAsync");

           try
           {
             return client.RemoveProxyAsync(proxyId);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd