// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Removes a chat from the list of frequently used chats. Supported only if the chat info database is enabled
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> RemoveTopChatAsync(TopChatCategory category = default, long chatId = default)
    {

           using var activity =  StartCallActivity("RemoveTopChatAsync", typeof(RemoveTopChat).FullName ?? "RemoveTopChatAsync");

           try
           {
             return client.RemoveTopChatAsync(category, chatId);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd