// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Removes background from the list of installed backgrounds
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> RemoveInstalledBackgroundAsync(long backgroundId = default)
    {

           using var activity =  StartCallActivity("RemoveInstalledBackgroundAsync", typeof(RemoveInstalledBackground).FullName ?? "RemoveInstalledBackgroundAsync");

           try
           {
             return client.RemoveInstalledBackgroundAsync(backgroundId);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd