// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Removes the connected business bot from a specific chat by adding the chat to businessRecipients.excluded_chat_ids
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> RemoveBusinessConnectedBotFromChatAsync(long chatId = default)
    {

           using var activity =  StartCallActivity("RemoveBusinessConnectedBotFromChatAsync", typeof(RemoveBusinessConnectedBotFromChat).FullName ?? "RemoveBusinessConnectedBotFromChatAsync");

           try
           {
             return client.RemoveBusinessConnectedBotFromChatAsync(chatId);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd