// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Removes a sticker from the list of recently used stickers
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> RemoveRecentStickerAsync(bool isAttached = default, InputFile sticker = default)
    {

           using var activity =  StartCallActivity("RemoveRecentStickerAsync", typeof(RemoveRecentSticker).FullName ?? "RemoveRecentStickerAsync");

           try
           {
             return client.RemoveRecentStickerAsync(isAttached, sticker);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd