// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Removes all files from the file download list
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> RemoveAllFilesFromDownloadsAsync(bool onlyActive = default, bool onlyCompleted = default, bool deleteFromCache = default)
    {

           using var activity =  StartCallActivity("RemoveAllFilesFromDownloadsAsync", typeof(RemoveAllFilesFromDownloads).FullName ?? "RemoveAllFilesFromDownloadsAsync");

           try
           {
             return client.RemoveAllFilesFromDownloadsAsync(onlyActive, onlyCompleted, deleteFromCache);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd