// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Removes a group of active notifications. Needs to be called only if the notification group is removed by the current user
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> RemoveNotificationGroupAsync(int notificationGroupId = default, int maxNotificationId = default)
    {

           using var activity =  StartCallActivity("RemoveNotificationGroupAsync", typeof(RemoveNotificationGroup).FullName ?? "RemoveNotificationGroupAsync");

           try
           {
             return client.RemoveNotificationGroupAsync(notificationGroupId, maxNotificationId);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd