// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Changes order of gifts in a collection. If the collection is owned by a channel chat, then requires can_post_messages administrator right in the channel chat. Returns the changed collection
    /// </summary>
    public Task<TdLib.TdApi.Objects.GiftCollection> ReorderGiftCollectionGiftsAsync(MessageSender ownerId = default, int collectionId = default, string[] receivedGiftIds = default)
    {

           using var activity =  StartCallActivity("ReorderGiftCollectionGiftsAsync", typeof(ReorderGiftCollectionGifts).FullName ?? "ReorderGiftCollectionGiftsAsync");

           try
           {
             return client.ReorderGiftCollectionGiftsAsync(ownerId, collectionId, receivedGiftIds);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd