// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Changes the order of quick reply shortcuts
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> ReorderQuickReplyShortcutsAsync(int[] shortcutIds = default)
    {

           using var activity =  StartCallActivity("ReorderQuickReplyShortcutsAsync", typeof(ReorderQuickReplyShortcuts).FullName ?? "ReorderQuickReplyShortcutsAsync");

           try
           {
             return client.ReorderQuickReplyShortcutsAsync(shortcutIds);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd