// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Changes the order of installed sticker sets
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> ReorderInstalledStickerSetsAsync(StickerType stickerType = default, long[] stickerSetIds = default)
    {

           using var activity =  StartCallActivity("ReorderInstalledStickerSetsAsync", typeof(ReorderInstalledStickerSets).FullName ?? "ReorderInstalledStickerSetsAsync");

           try
           {
             return client.ReorderInstalledStickerSetsAsync(stickerType, stickerSetIds);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd