// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Changes order of story albums. If the albums are owned by a supergroup or a channel chat, then requires can_edit_stories administrator right in the chat
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> ReorderStoryAlbumsAsync(long chatId = default, int[] storyAlbumIds = default)
    {

           using var activity =  StartCallActivity("ReorderStoryAlbumsAsync", typeof(ReorderStoryAlbums).FullName ?? "ReorderStoryAlbumsAsync");

           try
           {
             return client.ReorderStoryAlbumsAsync(chatId, storyAlbumIds);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd