// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Changes order of active usernames of the current user
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> ReorderActiveUsernamesAsync(string[] usernames = default)
    {

           using var activity =  StartCallActivity("ReorderActiveUsernamesAsync", typeof(ReorderActiveUsernames).FullName ?? "ReorderActiveUsernamesAsync");

           try
           {
             return client.ReorderActiveUsernamesAsync(usernames);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd