// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Changes order of active usernames of a bot. Can be called only if userTypeBot.can_be_edited == true
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> ReorderBotActiveUsernamesAsync(long botUserId = default, string[] usernames = default)
    {

           using var activity =  StartCallActivity("ReorderBotActiveUsernamesAsync", typeof(ReorderBotActiveUsernames).FullName ?? "ReorderBotActiveUsernamesAsync");

           try
           {
             return client.ReorderBotActiveUsernamesAsync(botUserId, usernames);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd