// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Replaces the current RTMP URL for streaming to the video chat of a chat; requires owner privileges in the chat
    /// </summary>
    public Task<TdLib.TdApi.Objects.RtmpUrl> ReplaceVideoChatRtmpUrlAsync(long chatId = default)
    {

           using var activity =  StartCallActivity("ReplaceVideoChatRtmpUrlAsync", typeof(ReplaceVideoChatRtmpUrl).FullName ?? "ReplaceVideoChatRtmpUrlAsync");

           try
           {
             return client.ReplaceVideoChatRtmpUrlAsync(chatId);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd