// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Replaces current primary invite link for a chat with a new primary invite link. Available for basic groups, supergroups, and channels. Requires administrator privileges and can_invite_users right
    /// </summary>
    public Task<TdLib.TdApi.Objects.ChatInviteLink> ReplacePrimaryChatInviteLinkAsync(long chatId = default)
    {

           using var activity =  StartCallActivity("ReplacePrimaryChatInviteLinkAsync", typeof(ReplacePrimaryChatInviteLink).FullName ?? "ReplacePrimaryChatInviteLinkAsync");

           try
           {
             return client.ReplacePrimaryChatInviteLinkAsync(chatId);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd