// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Replaces existing sticker in a set. The function is equivalent to removeStickerFromSet, then addStickerToSet, then setStickerPositionInSet
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> ReplaceStickerInSetAsync(long userId = default, string name = default, InputFile oldSticker = default, InputSticker newSticker = default)
    {

           using var activity =  StartCallActivity("ReplaceStickerInSetAsync", typeof(ReplaceStickerInSet).FullName ?? "ReplaceStickerInSetAsync");

           try
           {
             return client.ReplaceStickerInSetAsync(userId, name, oldSticker, newSticker);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd