// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Reports a chat to the Telegram moderators. A chat can be reported only from the chat action bar, or if chat.can_be_reported
    /// </summary>
    public Task<TdLib.TdApi.Objects.ReportChatResult> ReportChatAsync(long chatId = default, byte[] optionId = default, long[] messageIds = default, string text = default)
    {

           using var activity =  StartCallActivity("ReportChatAsync", typeof(ReportChat).FullName ?? "ReportChatAsync");

           try
           {
             return client.ReportChatAsync(chatId, optionId, messageIds, text);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd