// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Reports a video message advertisement to Telegram moderators
    /// </summary>
    public Task<TdLib.TdApi.Objects.ReportSponsoredResult> ReportVideoMessageAdvertisementAsync(long advertisementUniqueId = default, byte[] optionId = default)
    {

           using var activity =  StartCallActivity("ReportVideoMessageAdvertisementAsync", typeof(ReportVideoMessageAdvertisement).FullName ?? "ReportVideoMessageAdvertisementAsync");

           try
           {
             return client.ReportVideoMessageAdvertisementAsync(advertisementUniqueId, optionId);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd