// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Reports reactions set on a message to the Telegram moderators. Reactions on a message can be reported only if messageProperties.can_report_reactions
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> ReportMessageReactionsAsync(long chatId = default, long messageId = default, MessageSender senderId = default)
    {

           using var activity =  StartCallActivity("ReportMessageReactionsAsync", typeof(ReportMessageReactions).FullName ?? "ReportMessageReactionsAsync");

           try
           {
             return client.ReportMessageReactionsAsync(chatId, messageId, senderId);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd