// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Reports a sponsored chat to Telegram moderators
    /// </summary>
    public Task<TdLib.TdApi.Objects.ReportSponsoredResult> ReportSponsoredChatAsync(long sponsoredChatUniqueId = default, byte[] optionId = default)
    {

           using var activity =  StartCallActivity("ReportSponsoredChatAsync", typeof(ReportSponsoredChat).FullName ?? "ReportSponsoredChatAsync");

           try
           {
             return client.ReportSponsoredChatAsync(sponsoredChatUniqueId, optionId);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd