// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Reports that authentication code wasn't delivered via SMS; for official mobile applications only. Works only when the current authorization state is authorizationStateWaitCode
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> ReportAuthenticationCodeMissingAsync(string mobileNetworkCode = default)
    {

           using var activity =  StartCallActivity("ReportAuthenticationCodeMissingAsync", typeof(ReportAuthenticationCodeMissing).FullName ?? "ReportAuthenticationCodeMissingAsync");

           try
           {
             return client.ReportAuthenticationCodeMissingAsync(mobileNetworkCode);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd