// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Reports messages in a supergroup as spam; requires administrator rights in the supergroup
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> ReportSupergroupSpamAsync(long supergroupId = default, long[] messageIds = default)
    {

           using var activity =  StartCallActivity("ReportSupergroupSpamAsync", typeof(ReportSupergroupSpam).FullName ?? "ReportSupergroupSpamAsync");

           try
           {
             return client.ReportSupergroupSpamAsync(supergroupId, messageIds);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd