// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Reports a chat photo to the Telegram moderators. A chat photo can be reported only if chat.can_be_reported
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> ReportChatPhotoAsync(long chatId = default, int fileId = default, ReportReason reason = default, string text = default)
    {

           using var activity =  StartCallActivity("ReportChatPhotoAsync", typeof(ReportChatPhoto).FullName ?? "ReportChatPhotoAsync");

           try
           {
             return client.ReportChatPhotoAsync(chatId, fileId, reason, text);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd