// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Requests to send a 2-step verification password recovery code to an email address that was previously set up
    /// </summary>
    public Task<TdLib.TdApi.Objects.EmailAddressAuthenticationCodeInfo> RequestPasswordRecoveryAsync()
    {

           using var activity =  StartCallActivity("RequestPasswordRecoveryAsync", typeof(RequestPasswordRecovery).FullName ?? "RequestPasswordRecoveryAsync");

           try
           {
             return client.RequestPasswordRecoveryAsync();
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd