// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Resends the authentication code sent to a phone number. Works only if the previously received authenticationCodeInfo next_code_type was not null and the server-specified timeout has passed
    /// </summary>
    public Task<TdLib.TdApi.Objects.AuthenticationCodeInfo> ResendPhoneNumberCodeAsync(ResendCodeReason reason = default)
    {

           using var activity =  StartCallActivity("ResendPhoneNumberCodeAsync", typeof(ResendPhoneNumberCode).FullName ?? "ResendPhoneNumberCodeAsync");

           try
           {
             return client.ResendPhoneNumberCodeAsync(reason);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd