// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Resets list of installed backgrounds to its default value
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> ResetInstalledBackgroundsAsync()
    {

           using var activity =  StartCallActivity("ResetInstalledBackgroundsAsync", typeof(ResetInstalledBackgrounds).FullName ?? "ResetInstalledBackgroundsAsync");

           try
           {
             return client.ResetInstalledBackgroundsAsync();
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd