// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Resets all network data usage statistics to zero. Can be called before authorization
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> ResetNetworkStatisticsAsync()
    {

           using var activity =  StartCallActivity("ResetNetworkStatisticsAsync", typeof(ResetNetworkStatistics).FullName ?? "ResetNetworkStatisticsAsync");

           try
           {
             return client.ResetNetworkStatisticsAsync();
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd