// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Resends the 2-step verification recovery email address verification code
    /// </summary>
    public Task<TdLib.TdApi.Objects.PasswordState> ResendRecoveryEmailAddressCodeAsync()
    {

           using var activity =  StartCallActivity("ResendRecoveryEmailAddressCodeAsync", typeof(ResendRecoveryEmailAddressCode).FullName ?? "ResendRecoveryEmailAddressCodeAsync");

           try
           {
             return client.ResendRecoveryEmailAddressCodeAsync();
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd