// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Resets the login email address. May return an error with a message "TASK_ALREADY_EXISTS" if reset is still pending.
    /// Works only when the current authorization state is authorizationStateWaitEmailCode and authorization_state.can_reset_email_address == true
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> ResetAuthenticationEmailAddressAsync()
    {

           using var activity =  StartCallActivity("ResetAuthenticationEmailAddressAsync", typeof(ResetAuthenticationEmailAddress).FullName ?? "ResetAuthenticationEmailAddressAsync");

           try
           {
             return client.ResetAuthenticationEmailAddressAsync();
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd