// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Resends messages which failed to send. Can be called only for messages for which messageSendingStateFailed.can_retry is true and after specified in messageSendingStateFailed.retry_after time passed.
    /// If a message is re-sent, the corresponding failed to send message is deleted. Returns the sent messages in the same order as the message identifiers passed in message_ids. If a message can't be re-sent, null will be returned instead of the message
    /// </summary>
    public Task<TdLib.TdApi.Objects.Messages> ResendMessagesAsync(long chatId = default, long[] messageIds = default, InputTextQuote quote = default, long paidMessageStarCount = default)
    {

           using var activity =  StartCallActivity("ResendMessagesAsync", typeof(ResendMessages).FullName ?? "ResendMessagesAsync");

           try
           {
             return client.ResendMessagesAsync(chatId, messageIds, quote, paidMessageStarCount);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd