// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Resends the code to verify an email address to be added to a user's Telegram Passport
    /// </summary>
    public Task<TdLib.TdApi.Objects.EmailAddressAuthenticationCodeInfo> ResendEmailAddressVerificationCodeAsync()
    {

           using var activity =  StartCallActivity("ResendEmailAddressVerificationCodeAsync", typeof(ResendEmailAddressVerificationCode).FullName ?? "ResendEmailAddressVerificationCodeAsync");

           try
           {
             return client.ResendEmailAddressVerificationCodeAsync();
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd