// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Revokes invite link for a group call. Requires groupCall.can_be_managed right for video chats or groupCall.is_owned otherwise
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> RevokeGroupCallInviteLinkAsync(int groupCallId = default)
    {

           using var activity =  StartCallActivity("RevokeGroupCallInviteLinkAsync", typeof(RevokeGroupCallInviteLink).FullName ?? "RevokeGroupCallInviteLinkAsync");

           try
           {
             return client.RevokeGroupCallInviteLinkAsync(groupCallId);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd