// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Saves an inline message to be sent by the given user; for bots only
    /// </summary>
    public Task<TdLib.TdApi.Objects.PreparedInlineMessageId> SavePreparedInlineMessageAsync(long userId = default, InputInlineQueryResult result = default, TargetChatTypes chatTypes = default)
    {

           using var activity =  StartCallActivity("SavePreparedInlineMessageAsync", typeof(SavePreparedInlineMessage).FullName ?? "SavePreparedInlineMessageAsync");

           try
           {
             return client.SavePreparedInlineMessageAsync(userId, result, chatTypes);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd