// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Searches for sticker sets by looking for specified query in their title and name. Excludes installed sticker sets from the results
    /// </summary>
    public Task<TdLib.TdApi.Objects.StickerSets> SearchStickerSetsAsync(StickerType stickerType = default, string query = default)
    {

           using var activity =  StartCallActivity("SearchStickerSetsAsync", typeof(SearchStickerSets).FullName ?? "SearchStickerSetsAsync");

           try
           {
             return client.SearchStickerSetsAsync(stickerType, query);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd