// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Searches for emojis by keywords. Supported only if the file database is enabled. Order of results is unspecified
    /// </summary>
    public Task<TdLib.TdApi.Objects.EmojiKeywords> SearchEmojisAsync(string text = default, string[] inputLanguageCodes = default)
    {

           using var activity =  StartCallActivity("SearchEmojisAsync", typeof(SearchEmojis).FullName ?? "SearchEmojisAsync");

           try
           {
             return client.SearchEmojisAsync(text, inputLanguageCodes);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd