// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Searches for files in the file download list or recently downloaded files from the list
    /// </summary>
    public Task<TdLib.TdApi.Objects.FoundFileDownloads> SearchFileDownloadsAsync(string query = default, bool onlyActive = default, bool onlyCompleted = default, string offset = default, int limit = default)
    {

           using var activity =  StartCallActivity("SearchFileDownloadsAsync", typeof(SearchFileDownloads).FullName ?? "SearchFileDownloadsAsync");

           try
           {
             return client.SearchFileDownloadsAsync(query, onlyActive, onlyCompleted, offset, limit);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd