// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Searches for a specified query in the first name, last name and usernames of the members of a specified chat. Requires administrator rights if the chat is a channel
    /// </summary>
    public Task<TdLib.TdApi.Objects.ChatMembers> SearchChatMembersAsync(long chatId = default, string query = default, int limit = default, ChatMembersFilter filter = default)
    {

           using var activity =  StartCallActivity("SearchChatMembersAsync", typeof(SearchChatMembers).FullName ?? "SearchChatMembersAsync");

           try
           {
             return client.SearchChatMembersAsync(chatId, query, limit, filter);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd