// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Searches for outgoing messages with content of the type messageDocument in all chats except secret chats. Returns the results in reverse chronological order
    /// </summary>
    public Task<TdLib.TdApi.Objects.FoundMessages> SearchOutgoingDocumentMessagesAsync(string query = default, int limit = default)
    {

           using var activity =  StartCallActivity("SearchOutgoingDocumentMessagesAsync", typeof(SearchOutgoingDocumentMessages).FullName ?? "SearchOutgoingDocumentMessagesAsync");

           try
           {
             return client.SearchOutgoingDocumentMessagesAsync(query, limit);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd