// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Searches for messages in secret chats. Returns the results in reverse chronological order. For optimal performance, the number of returned messages is chosen by TDLib
    /// </summary>
    public Task<TdLib.TdApi.Objects.FoundMessages> SearchSecretMessagesAsync(long chatId = default, string query = default, string offset = default, int limit = default, SearchMessagesFilter filter = default)
    {

           using var activity =  StartCallActivity("SearchSecretMessagesAsync", typeof(SearchSecretMessages).FullName ?? "SearchSecretMessagesAsync");

           try
           {
             return client.SearchSecretMessagesAsync(chatId, query, offset, limit, filter);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd