// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Searches for public stories by the given address location. For optimal performance, the number of returned stories is chosen by TDLib and can be smaller than the specified limit
    /// </summary>
    public Task<TdLib.TdApi.Objects.FoundStories> SearchPublicStoriesByLocationAsync(LocationAddress address = default, string offset = default, int limit = default)
    {

           using var activity =  StartCallActivity("SearchPublicStoriesByLocationAsync", typeof(SearchPublicStoriesByLocation).FullName ?? "SearchPublicStoriesByLocationAsync");

           try
           {
             return client.SearchPublicStoriesByLocationAsync(address, offset, limit);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd