// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Searches for call and group call messages. Returns the results in reverse chronological order (i.e., in order of decreasing message_id). For optimal performance, the number of returned messages is chosen by TDLib
    /// </summary>
    public Task<TdLib.TdApi.Objects.FoundMessages> SearchCallMessagesAsync(string offset = default, int limit = default, bool onlyMissed = default)
    {

           using var activity =  StartCallActivity("SearchCallMessagesAsync", typeof(SearchCallMessages).FullName ?? "SearchCallMessagesAsync");

           try
           {
             return client.SearchCallMessagesAsync(offset, limit, onlyMissed);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd