// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Searches a user by a token from the user's link
    /// </summary>
    public Task<TdLib.TdApi.Objects.User> SearchUserByTokenAsync(string token = default)
    {

           using var activity =  StartCallActivity("SearchUserByTokenAsync", typeof(SearchUserByToken).FullName ?? "SearchUserByTokenAsync");

           try
           {
             return client.SearchUserByTokenAsync(token);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd