// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Searches a public chat by its username. Currently, only private chats, supergroups and channels can be public. Returns the chat if found; otherwise, an error is returned
    /// </summary>
    public Task<TdLib.TdApi.Objects.Chat> SearchPublicChatAsync(string username = default)
    {

           using var activity =  StartCallActivity("SearchPublicChatAsync", typeof(SearchPublicChat).FullName ?? "SearchPublicChatAsync");

           try
           {
             return client.SearchPublicChatAsync(username);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd