// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Searches specified query by word prefixes in the provided strings. Returns 0-based positions of strings that matched. Can be called synchronously
    /// </summary>
    public Task<TdLib.TdApi.Objects.FoundPositions> SearchStringsByPrefixAsync(string[] strings = default, string query = default, int limit = default, bool returnNoneForEmptyQuery = default)
    {

           using var activity =  StartCallActivity("SearchStringsByPrefixAsync", typeof(SearchStringsByPrefix).FullName ?? "SearchStringsByPrefixAsync");

           try
           {
             return client.SearchStringsByPrefixAsync(strings, query, limit, returnNoneForEmptyQuery);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd