// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Searches for the specified query in the title and username of already known chats. This is an offline method. Returns chats in the order seen in the main chat list
    /// </summary>
    public Task<TdLib.TdApi.Objects.Chats> SearchChatsAsync(string query = default, int limit = default)
    {

           using var activity =  StartCallActivity("SearchChatsAsync", typeof(SearchChats).FullName ?? "SearchChatsAsync");

           try
           {
             return client.SearchChatsAsync(query, limit);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd