// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Searches for messages in all chats except secret chats. Returns the results in reverse chronological order (i.e., in order of decreasing (date, chat_id, message_id)).
    /// For optimal performance, the number of returned messages is chosen by TDLib and can be smaller than the specified limit
    /// </summary>
    public Task<TdLib.TdApi.Objects.FoundMessages> SearchMessagesAsync(ChatList chatList = default, string query = default, string offset = default, int limit = default, SearchMessagesFilter filter = default, SearchMessagesChatTypeFilter chatTypeFilter = default, int minDate = default, int maxDate = default)
    {

           using var activity =  StartCallActivity("SearchMessagesAsync", typeof(SearchMessages).FullName ?? "SearchMessagesAsync");

           try
           {
             return client.SearchMessagesAsync(chatList, query, offset, limit, filter, chatTypeFilter, minDate, maxDate);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd