// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Searches a user by their phone number. Returns a 404 error if the user can't be found
    /// </summary>
    public Task<TdLib.TdApi.Objects.User> SearchUserByPhoneNumberAsync(string phoneNumber = default, bool onlyLocal = default)
    {

           using var activity =  StartCallActivity("SearchUserByPhoneNumberAsync", typeof(SearchUserByPhoneNumber).FullName ?? "SearchUserByPhoneNumberAsync");

           try
           {
             return client.SearchUserByPhoneNumberAsync(phoneNumber, onlyLocal);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd