// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Searches for a background by its name
    /// </summary>
    public Task<TdLib.TdApi.Objects.Background> SearchBackgroundAsync(string name = default)
    {

           using var activity =  StartCallActivity("SearchBackgroundAsync", typeof(SearchBackground).FullName ?? "SearchBackgroundAsync");

           try
           {
             return client.SearchBackgroundAsync(name);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd