// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Searches for public stories containing the given hashtag or cashtag. For optimal performance, the number of returned stories is chosen by TDLib and can be smaller than the specified limit
    /// </summary>
    public Task<TdLib.TdApi.Objects.FoundStories> SearchPublicStoriesByTagAsync(long storyPosterChatId = default, string tag = default, string offset = default, int limit = default)
    {

           using var activity =  StartCallActivity("SearchPublicStoriesByTagAsync", typeof(SearchPublicStoriesByTag).FullName ?? "SearchPublicStoriesByTagAsync");

           try
           {
             return client.SearchPublicStoriesByTagAsync(storyPosterChatId, tag, offset, limit);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd