// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Searches for messages with given words in the chat. Returns the results in reverse chronological order, i.e. in order of decreasing message_id. Cannot be used in secret chats with a non-empty query
    /// (searchSecretMessages must be used instead), or without an enabled message database. For optimal performance, the number of returned messages is chosen by TDLib and can be smaller than the specified limit.
    /// A combination of query, sender_id, filter and topic_id search criteria is expected to be supported, only if it is required for Telegram official application implementation
    /// </summary>
    public Task<TdLib.TdApi.Objects.FoundChatMessages> SearchChatMessagesAsync(long chatId = default, MessageTopic topicId = default, string query = default, MessageSender senderId = default, long fromMessageId = default, int offset = default, int limit = default, SearchMessagesFilter filter = default)
    {

           using var activity =  StartCallActivity("SearchChatMessagesAsync", typeof(SearchChatMessages).FullName ?? "SearchChatMessagesAsync");

           try
           {
             return client.SearchChatMessagesAsync(chatId, topicId, query, senderId, fromMessageId, offset, limit, filter);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd