// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Searches for the specified query in the title and username of up to 50 recently found chats. This is an offline method
    /// </summary>
    public Task<TdLib.TdApi.Objects.Chats> SearchRecentlyFoundChatsAsync(string query = default, int limit = default)
    {

           using var activity =  StartCallActivity("SearchRecentlyFoundChatsAsync", typeof(SearchRecentlyFoundChats).FullName ?? "SearchRecentlyFoundChatsAsync");

           try
           {
             return client.SearchRecentlyFoundChatsAsync(query, limit);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd