// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Invites a bot to a chat (if it is not yet a member) and sends it the /start command; requires can_invite_users member right. Bots can't be invited to a private chat other than the chat with the bot.
    /// Bots can't be invited to channels (although they can be added as admins) and secret chats. Returns the sent message
    /// </summary>
    public Task<TdLib.TdApi.Objects.Message> SendBotStartMessageAsync(long botUserId = default, long chatId = default, string parameter = default)
    {

           using var activity =  StartCallActivity("SendBotStartMessageAsync", typeof(SendBotStartMessage).FullName ?? "SendBotStartMessageAsync");

           try
           {
             return client.SendBotStartMessageAsync(botUserId, chatId, parameter);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd