// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Sends a custom request from a Web App
    /// </summary>
    public Task<TdLib.TdApi.Objects.CustomRequestResult> SendWebAppCustomRequestAsync(long botUserId = default, string method = default, string parameters = default)
    {

           using var activity =  StartCallActivity("SendWebAppCustomRequestAsync", typeof(SendWebAppCustomRequest).FullName ?? "SendWebAppCustomRequestAsync");

           try
           {
             return client.SendWebAppCustomRequestAsync(botUserId, method, parameters);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd