// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Sends a Telegram Passport authorization form, effectively sharing data with the service. This method must be called after getPassportAuthorizationFormAvailableElements if some previously available elements are going to be reused
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> SendPassportAuthorizationFormAsync(int authorizationFormId = default, PassportElementType[] types = default)
    {

           using var activity =  StartCallActivity("SendPassportAuthorizationFormAsync", typeof(SendPassportAuthorizationForm).FullName ?? "SendPassportAuthorizationFormAsync");

           try
           {
             return client.SendPassportAuthorizationFormAsync(authorizationFormId, types);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd