// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Sends the result of an inline query as a message. Returns the sent message. Always clears a chat draft message
    /// </summary>
    public Task<TdLib.TdApi.Objects.Message> SendInlineQueryResultMessageAsync(long chatId = default, MessageTopic topicId = default, InputMessageReplyTo replyTo = default, MessageSendOptions options = default, long queryId = default, string resultId = default, bool hideViaBot = default)
    {

           using var activity =  StartCallActivity("SendInlineQueryResultMessageAsync", typeof(SendInlineQueryResultMessage).FullName ?? "SendInlineQueryResultMessageAsync");

           try
           {
             return client.SendInlineQueryResultMessageAsync(chatId, topicId, replyTo, options, queryId, resultId, hideViaBot);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd