// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Sends call signaling data
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> SendCallSignalingDataAsync(int callId = default, byte[] data = default)
    {

           using var activity =  StartCallActivity("SendCallSignalingDataAsync", typeof(SendCallSignalingData).FullName ?? "SendCallSignalingDataAsync");

           try
           {
             return client.SendCallSignalingDataAsync(callId, data);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd