// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Sends data received from a keyboardButtonTypeWebApp Web App to a bot
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> SendWebAppDataAsync(long botUserId = default, string buttonText = default, string data = default)
    {

           using var activity =  StartCallActivity("SendWebAppDataAsync", typeof(SendWebAppData).FullName ?? "SendWebAppDataAsync");

           try
           {
             return client.SendWebAppDataAsync(botUserId, buttonText, data);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd