// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Sends a message. Returns the sent message
    /// </summary>
    public Task<TdLib.TdApi.Objects.Message> SendMessageAsync(long chatId = default, MessageTopic topicId = default, InputMessageReplyTo replyTo = default, MessageSendOptions options = default, ReplyMarkup replyMarkup = default, InputMessageContent inputMessageContent = default)
    {

           using var activity =  StartCallActivity("SendMessageAsync", typeof(SendMessage).FullName ?? "SendMessageAsync");

           try
           {
             return client.SendMessageAsync(chatId, topicId, replyTo, options, replyMarkup, inputMessageContent);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd