// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Sends a message to other participants of a group call. Requires groupCall.can_send_messages right
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> SendGroupCallMessageAsync(int groupCallId = default, FormattedText text = default, long paidMessageStarCount = default)
    {

           using var activity =  StartCallActivity("SendGroupCallMessageAsync", typeof(SendGroupCallMessage).FullName ?? "SendGroupCallMessageAsync");

           try
           {
             return client.SendGroupCallMessageAsync(groupCallId, text, paidMessageStarCount);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd