// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Sends a filled-out payment form to the bot for final verification
    /// </summary>
    public Task<TdLib.TdApi.Objects.PaymentResult> SendPaymentFormAsync(InputInvoice inputInvoice = default, long paymentFormId = default, string orderInfoId = default, string shippingOptionId = default, InputCredentials credentials = default, long tipAmount = default)
    {

           using var activity =  StartCallActivity("SendPaymentFormAsync", typeof(SendPaymentForm).FullName ?? "SendPaymentFormAsync");

           try
           {
             return client.SendPaymentFormAsync(inputInvoice, paymentFormId, orderInfoId, shippingOptionId, credentials, tipAmount);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd