// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Sends a gift to another user or channel chat. May return an error with a message "STARGIFT_USAGE_LIMITED" if the gift was sold out
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> SendGiftAsync(long giftId = default, MessageSender ownerId = default, FormattedText text = default, bool isPrivate = default, bool payForUpgrade = default)
    {

           using var activity =  StartCallActivity("SendGiftAsync", typeof(SendGift).FullName ?? "SendGiftAsync");

           try
           {
             return client.SendGiftAsync(giftId, ownerId, text, isPrivate, payForUpgrade);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd