// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Sets autosave settings for the given scope. The method is guaranteed to work only after at least one call to getAutosaveSettings
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> SetAutosaveSettingsAsync(AutosaveSettingsScope scope = default, ScopeAutosaveSettings settings = default)
    {

           using var activity =  StartCallActivity("SetAutosaveSettingsAsync", typeof(SetAutosaveSettings).FullName ?? "SetAutosaveSettingsAsync");

           try
           {
             return client.SetAutosaveSettingsAsync(scope, settings);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd