// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Informs server about an in-store purchase of Telegram Premium before authorization. Works only when the current authorization state is authorizationStateWaitPremiumPurchase
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> SetAuthenticationPremiumPurchaseTransactionAsync(StoreTransaction transaction = default, bool isRestore = default, string currency = default, long amount = default)
    {

           using var activity =  StartCallActivity("SetAuthenticationPremiumPurchaseTransactionAsync", typeof(SetAuthenticationPremiumPurchaseTransaction).FullName ?? "SetAuthenticationPremiumPurchaseTransactionAsync");

           try
           {
             return client.SetAuthenticationPremiumPurchaseTransactionAsync(transaction, isRestore, currency, amount);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd