// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Changes settings for automatic moving of chats to and from the Archive chat lists
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> SetArchiveChatListSettingsAsync(ArchiveChatListSettings settings = default)
    {

           using var activity =  StartCallActivity("SetArchiveChatListSettingsAsync", typeof(SetArchiveChatListSettings).FullName ?? "SetArchiveChatListSettingsAsync");

           try
           {
             return client.SetArchiveChatListSettingsAsync(settings);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd