// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Informs TDLib that application or reCAPTCHA verification has been completed. Can be called before authorization
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> SetApplicationVerificationTokenAsync(long verificationId = default, string token = default)
    {

           using var activity =  StartCallActivity("SetApplicationVerificationTokenAsync", typeof(SetApplicationVerificationToken).FullName ?? "SetApplicationVerificationTokenAsync");

           try
           {
             return client.SetApplicationVerificationTokenAsync(verificationId, token);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd