// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Sets the email address of the user and sends an authentication code to the email address. Works only when the current authorization state is authorizationStateWaitEmailAddress
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> SetAuthenticationEmailAddressAsync(string emailAddress = default)
    {

           using var activity =  StartCallActivity("SetAuthenticationEmailAddressAsync", typeof(SetAuthenticationEmailAddress).FullName ?? "SetAuthenticationEmailAddressAsync");

           try
           {
             return client.SetAuthenticationEmailAddressAsync(emailAddress);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd