// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Changes the business start page of the current user. Requires Telegram Business subscription
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> SetBusinessStartPageAsync(InputBusinessStartPage startPage = default)
    {

           using var activity =  StartCallActivity("SetBusinessStartPageAsync", typeof(SetBusinessStartPage).FullName ?? "SetBusinessStartPageAsync");

           try
           {
             return client.SetBusinessStartPageAsync(startPage);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd