// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Sets the text shown on a bot's profile page and sent together with the link when users share the bot. Can be called only if userTypeBot.can_be_edited == true
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> SetBotInfoShortDescriptionAsync(long botUserId = default, string languageCode = default, string shortDescription = default)
    {

           using var activity =  StartCallActivity("SetBotInfoShortDescriptionAsync", typeof(SetBotInfoShortDescription).FullName ?? "SetBotInfoShortDescriptionAsync");

           try
           {
             return client.SetBotInfoShortDescriptionAsync(botUserId, languageCode, shortDescription);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd