// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Changes the bio of the current user
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> SetBioAsync(string bio = default)
    {

           using var activity =  StartCallActivity("SetBioAsync", typeof(SetBio).FullName ?? "SetBioAsync");

           try
           {
             return client.SetBioAsync(bio);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd