// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Changes the business location of the current user. Requires Telegram Business subscription
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> SetBusinessLocationAsync(BusinessLocation location = default)
    {

           using var activity =  StartCallActivity("SetBusinessLocationAsync", typeof(SetBusinessLocation).FullName ?? "SetBusinessLocationAsync");

           try
           {
             return client.SetBusinessLocationAsync(location);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd