// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Changes the birthdate of the current user
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> SetBirthdateAsync(Birthdate birthdate = default)
    {

           using var activity =  StartCallActivity("SetBirthdateAsync", typeof(SetBirthdate).FullName ?? "SetBirthdateAsync");

           try
           {
             return client.SetBirthdateAsync(birthdate);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd