// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Pins or unpins a message sent on behalf of a business account; for bots only
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> SetBusinessMessageIsPinnedAsync(string businessConnectionId = default, long chatId = default, long messageId = default, bool isPinned = default)
    {

           using var activity =  StartCallActivity("SetBusinessMessageIsPinnedAsync", typeof(SetBusinessMessageIsPinned).FullName ?? "SetBusinessMessageIsPinnedAsync");

           try
           {
             return client.SetBusinessMessageIsPinnedAsync(businessConnectionId, chatId, messageId, isPinned);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd