// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Changes the bio of a business account; for bots only
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> SetBusinessAccountBioAsync(string businessConnectionId = default, string bio = default)
    {

           using var activity =  StartCallActivity("SetBusinessAccountBioAsync", typeof(SetBusinessAccountBio).FullName ?? "SetBusinessAccountBioAsync");

           try
           {
             return client.SetBusinessAccountBioAsync(businessConnectionId, bio);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd