// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Changes the business opening hours of the current user. Requires Telegram Business subscription
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> SetBusinessOpeningHoursAsync(BusinessOpeningHours openingHours = default)
    {

           using var activity =  StartCallActivity("SetBusinessOpeningHoursAsync", typeof(SetBusinessOpeningHours).FullName ?? "SetBusinessOpeningHoursAsync");

           try
           {
             return client.SetBusinessOpeningHoursAsync(openingHours);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd