// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Adds or changes business bot that is connected to the current user account
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> SetBusinessConnectedBotAsync(BusinessConnectedBot bot = default)
    {

           using var activity =  StartCallActivity("SetBusinessConnectedBotAsync", typeof(SetBusinessConnectedBot).FullName ?? "SetBusinessConnectedBotAsync");

           try
           {
             return client.SetBusinessConnectedBotAsync(bot);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd