// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Changes the business greeting message settings of the current user. Requires Telegram Business subscription
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> SetBusinessGreetingMessageSettingsAsync(BusinessGreetingMessageSettings greetingMessageSettings = default)
    {

           using var activity =  StartCallActivity("SetBusinessGreetingMessageSettingsAsync", typeof(SetBusinessGreetingMessageSettings).FullName ?? "SetBusinessGreetingMessageSettingsAsync");

           try
           {
             return client.SetBusinessGreetingMessageSettingsAsync(greetingMessageSettings);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd