// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Sets the name of a bot. Can be called only if userTypeBot.can_be_edited == true
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> SetBotNameAsync(long botUserId = default, string languageCode = default, string name = default)
    {

           using var activity =  StartCallActivity("SetBotNameAsync", typeof(SetBotName).FullName ?? "SetBotNameAsync");

           try
           {
             return client.SetBotNameAsync(botUserId, languageCode, name);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd