// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Changes the first and last name of a business account; for bots only
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> SetBusinessAccountNameAsync(string businessConnectionId = default, string firstName = default, string lastName = default)
    {

           using var activity =  StartCallActivity("SetBusinessAccountNameAsync", typeof(SetBusinessAccountName).FullName ?? "SetBusinessAccountNameAsync");

           try
           {
             return client.SetBusinessAccountNameAsync(businessConnectionId, firstName, lastName);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd