// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Changes a profile photo for a bot
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> SetBotProfilePhotoAsync(long botUserId = default, InputChatPhoto photo = default)
    {

           using var activity =  StartCallActivity("SetBotProfilePhotoAsync", typeof(SetBotProfilePhoto).FullName ?? "SetBotProfilePhotoAsync");

           try
           {
             return client.SetBotProfilePhotoAsync(botUserId, photo);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd