// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Changes the Telegram Star amount that must be paid to send a message to a supergroup chat; requires can_restrict_members administrator right and supergroupFullInfo.can_enable_paid_messages
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> SetChatPaidMessageStarCountAsync(long chatId = default, long paidMessageStarCount = default)
    {

           using var activity =  StartCallActivity("SetChatPaidMessageStarCountAsync", typeof(SetChatPaidMessageStarCount).FullName ?? "SetChatPaidMessageStarCountAsync");

           try
           {
             return client.SetChatPaidMessageStarCountAsync(chatId, paidMessageStarCount);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd