// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Changes application-specific data associated with a chat
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> SetChatClientDataAsync(long chatId = default, string clientData = default)
    {

           using var activity =  StartCallActivity("SetChatClientDataAsync", typeof(SetChatClientData).FullName ?? "SetChatClientDataAsync");

           try
           {
             return client.SetChatClientDataAsync(chatId, clientData);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd