// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Changes story list in which stories from the chat are shown
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> SetChatActiveStoriesListAsync(long chatId = default, StoryList storyList = default)
    {

           using var activity =  StartCallActivity("SetChatActiveStoriesListAsync", typeof(SetChatActiveStoriesList).FullName ?? "SetChatActiveStoriesListAsync");

           try
           {
             return client.SetChatActiveStoriesListAsync(chatId, storyList);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd