// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Changes the list of close friends of the current user
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> SetCloseFriendsAsync(long[] userIds = default)
    {

           using var activity =  StartCallActivity("SetCloseFriendsAsync", typeof(SetCloseFriends).FullName ?? "SetCloseFriendsAsync");

           try
           {
             return client.SetCloseFriendsAsync(userIds);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd