// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Changes information about a chat. Available for basic groups, supergroups, and channels. Requires can_change_info member right
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> SetChatDescriptionAsync(long chatId = default, string description = default)
    {

           using var activity =  StartCallActivity("SetChatDescriptionAsync", typeof(SetChatDescription).FullName ?? "SetChatDescriptionAsync");

           try
           {
             return client.SetChatDescriptionAsync(chatId, description);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd