// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Changes the emoji status of a chat. Use chatBoostLevelFeatures.can_set_emoji_status to check whether an emoji status can be set. Requires can_change_info administrator right
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> SetChatEmojiStatusAsync(long chatId = default, EmojiStatus emojiStatus = default)
    {

           using var activity =  StartCallActivity("SetChatEmojiStatusAsync", typeof(SetChatEmojiStatus).FullName ?? "SetChatEmojiStatusAsync");

           try
           {
             return client.SetChatEmojiStatusAsync(chatId, emojiStatus);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd