// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Changes the message auto-delete or self-destruct (for secret chats) time in a chat. Requires change_info administrator right in basic groups, supergroups and channels.
    /// Message auto-delete time can't be changed in a chat with the current user (Saved Messages) and the chat 777000 (Telegram).
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> SetChatMessageAutoDeleteTimeAsync(long chatId = default, int messageAutoDeleteTime = default)
    {

           using var activity =  StartCallActivity("SetChatMessageAutoDeleteTimeAsync", typeof(SetChatMessageAutoDeleteTime).FullName ?? "SetChatMessageAutoDeleteTimeAsync");

           try
           {
             return client.SetChatMessageAutoDeleteTimeAsync(chatId, messageAutoDeleteTime);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd