// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Changes the location of a chat. Available only for some location-based supergroups, use supergroupFullInfo.can_set_location to check whether the method is allowed to use
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> SetChatLocationAsync(long chatId = default, ChatLocation location = default)
    {

           using var activity =  StartCallActivity("SetChatLocationAsync", typeof(SetChatLocation).FullName ?? "SetChatLocationAsync");

           try
           {
             return client.SetChatLocationAsync(chatId, location);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd