// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Selects a message sender to send messages in a chat
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> SetChatMessageSenderAsync(long chatId = default, MessageSender messageSenderId = default)
    {

           using var activity =  StartCallActivity("SetChatMessageSenderAsync", typeof(SetChatMessageSender).FullName ?? "SetChatMessageSenderAsync");

           try
           {
             return client.SetChatMessageSenderAsync(chatId, messageSenderId);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd