// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Changes accent color and background custom emoji for profile of a supergroup or channel chat. Requires can_change_info administrator right
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> SetChatProfileAccentColorAsync(long chatId = default, int profileAccentColorId = default, long profileBackgroundCustomEmojiId = default)
    {

           using var activity =  StartCallActivity("SetChatProfileAccentColorAsync", typeof(SetChatProfileAccentColor).FullName ?? "SetChatProfileAccentColorAsync");

           try
           {
             return client.SetChatProfileAccentColorAsync(chatId, profileAccentColorId, profileBackgroundCustomEmojiId);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd