// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Sets the background in a specific chat. Supported only in private and secret chats with non-deleted users, and in chats with sufficient boost level and can_change_info administrator right
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> SetChatBackgroundAsync(long chatId = default, InputBackground background = default, BackgroundType type = default, int darkThemeDimming = default, bool onlyForSelf = default)
    {

           using var activity =  StartCallActivity("SetChatBackgroundAsync", typeof(SetChatBackground).FullName ?? "SetChatBackgroundAsync");

           try
           {
             return client.SetChatBackgroundAsync(chatId, background, type, darkThemeDimming, onlyForSelf);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd