// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Adds, edits or deletes a string in a custom local language pack. Can be called before authorization
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> SetCustomLanguagePackStringAsync(string languagePackId = default, LanguagePackString newString = default)
    {

           using var activity =  StartCallActivity("SetCustomLanguagePackStringAsync", typeof(SetCustomLanguagePackString).FullName ?? "SetCustomLanguagePackStringAsync");

           try
           {
             return client.SetCustomLanguagePackStringAsync(languagePackId, newString);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd