// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Changes the status of a chat member; requires can_invite_users member right to add a chat member, can_promote_members administrator right to change administrator rights of the member,
    /// and can_restrict_members administrator right to change restrictions of a user. This function is currently not suitable for transferring chat ownership; use transferChatOwnership instead.
    /// Use addChatMember or banChatMember if some additional parameters needs to be passed
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> SetChatMemberStatusAsync(long chatId = default, MessageSender memberId = default, ChatMemberStatus status = default)
    {

           using var activity =  StartCallActivity("SetChatMemberStatusAsync", typeof(SetChatMemberStatus).FullName ?? "SetChatMemberStatusAsync");

           try
           {
             return client.SetChatMemberStatusAsync(chatId, memberId, status);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd