// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Changes the draft message in a chat or a topic
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> SetChatDraftMessageAsync(long chatId = default, MessageTopic topicId = default, DraftMessage draftMessage = default)
    {

           using var activity =  StartCallActivity("SetChatDraftMessageAsync", typeof(SetChatDraftMessage).FullName ?? "SetChatDraftMessageAsync");

           try
           {
             return client.SetChatDraftMessageAsync(chatId, topicId, draftMessage);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd