// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Changes the discussion group of a channel chat; requires can_change_info administrator right in the channel if it is specified
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> SetChatDiscussionGroupAsync(long chatId = default, long discussionChatId = default)
    {

           using var activity =  StartCallActivity("SetChatDiscussionGroupAsync", typeof(SetChatDiscussionGroup).FullName ?? "SetChatDiscussionGroupAsync");

           try
           {
             return client.SetChatDiscussionGroupAsync(chatId, discussionChatId);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd