// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Sets a custom emoji sticker set thumbnail
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> SetCustomEmojiStickerSetThumbnailAsync(string name = default, long customEmojiId = default)
    {

           using var activity =  StartCallActivity("SetCustomEmojiStickerSetThumbnailAsync", typeof(SetCustomEmojiStickerSetThumbnail).FullName ?? "SetCustomEmojiStickerSetThumbnailAsync");

           try
           {
             return client.SetCustomEmojiStickerSetThumbnailAsync(name, customEmojiId);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd