// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Changes the marked as unread state of the topic in a channel direct messages chat administered by the current user
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> SetDirectMessagesChatTopicIsMarkedAsUnreadAsync(long chatId = default, long topicId = default, bool isMarkedAsUnread = default)
    {

           using var activity =  StartCallActivity("SetDirectMessagesChatTopicIsMarkedAsUnreadAsync", typeof(SetDirectMessagesChatTopicIsMarkedAsUnread).FullName ?? "SetDirectMessagesChatTopicIsMarkedAsUnreadAsync");

           try
           {
             return client.SetDirectMessagesChatTopicIsMarkedAsUnreadAsync(chatId, topicId, isMarkedAsUnread);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd