// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Changes the default message auto-delete time for new chats
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> SetDefaultMessageAutoDeleteTimeAsync(MessageAutoDeleteTime messageAutoDeleteTime = default)
    {

           using var activity =  StartCallActivity("SetDefaultMessageAutoDeleteTimeAsync", typeof(SetDefaultMessageAutoDeleteTime).FullName ?? "SetDefaultMessageAutoDeleteTimeAsync");

           try
           {
             return client.SetDefaultMessageAutoDeleteTimeAsync(messageAutoDeleteTime);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd