// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Changes type of default reaction for the current user
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> SetDefaultReactionTypeAsync(ReactionType reactionType = default)
    {

           using var activity =  StartCallActivity("SetDefaultReactionTypeAsync", typeof(SetDefaultReactionType).FullName ?? "SetDefaultReactionTypeAsync");

           try
           {
             return client.SetDefaultReactionTypeAsync(reactionType);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd