// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Changes the notification settings of a forum topic in a forum supergroup chat or a chat with a bot with topics
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> SetForumTopicNotificationSettingsAsync(long chatId = default, int forumTopicId = default, ChatNotificationSettings notificationSettings = default)
    {

           using var activity =  StartCallActivity("SetForumTopicNotificationSettingsAsync", typeof(SetForumTopicNotificationSettings).FullName ?? "SetForumTopicNotificationSettingsAsync");

           try
           {
             return client.SetForumTopicNotificationSettingsAsync(chatId, forumTopicId, notificationSettings);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd