// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Informs TDLib on a file generation progress
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> SetFileGenerationProgressAsync(long generationId = default, long expectedSize = default, long localPrefixSize = default)
    {

           using var activity =  StartCallActivity("SetFileGenerationProgressAsync", typeof(SetFileGenerationProgress).FullName ?? "SetFileGenerationProgressAsync");

           try
           {
             return client.SetFileGenerationProgressAsync(generationId, expectedSize, localPrefixSize);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd