// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Changes resale price of a unique gift owned by the current user
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> SetGiftResalePriceAsync(string receivedGiftId = default, GiftResalePrice price = default)
    {

           using var activity =  StartCallActivity("SetGiftResalePriceAsync", typeof(SetGiftResalePrice).FullName ?? "SetGiftResalePriceAsync");

           try
           {
             return client.SetGiftResalePriceAsync(receivedGiftId, price);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd