// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Changes volume level of a participant of an active group call; not supported for live stories. If the current user can manage the group call or is the owner of the group call,
    /// then the participant's volume level will be changed for all users with the default volume level
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> SetGroupCallParticipantVolumeLevelAsync(int groupCallId = default, MessageSender participantId = default, int volumeLevel = default)
    {

           using var activity =  StartCallActivity("SetGroupCallParticipantVolumeLevelAsync", typeof(SetGroupCallParticipantVolumeLevel).FullName ?? "SetGroupCallParticipantVolumeLevelAsync");

           try
           {
             return client.SetGroupCallParticipantVolumeLevelAsync(groupCallId, participantId, volumeLevel);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd