// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Updates the game score of the specified user in a game; for bots only
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> SetInlineGameScoreAsync(string inlineMessageId = default, bool editMessage = default, long userId = default, int score = default, bool force = default)
    {

           using var activity =  StartCallActivity("SetInlineGameScoreAsync", typeof(SetInlineGameScore).FullName ?? "SetInlineGameScoreAsync");

           try
           {
             return client.SetInlineGameScoreAsync(inlineMessageId, editMessage, userId, score, force);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd