// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Changes the login email address of the user. The email address can be changed only if the current user already has login email and passwordState.login_email_address_pattern is non-empty,
    /// or the user received suggestedActionSetLoginEmailAddress and isLoginEmailAddressRequired succeeds. The change will not be applied until the new login email address is confirmed with checkLoginEmailAddressCode.
    /// To use Apple ID/Google ID instead of an email address, call checkLoginEmailAddressCode directly
    /// </summary>
    public Task<TdLib.TdApi.Objects.EmailAddressAuthenticationCodeInfo> SetLoginEmailAddressAsync(string newLoginEmailAddress = default)
    {

           using var activity =  StartCallActivity("SetLoginEmailAddressAsync", typeof(SetLoginEmailAddress).FullName ?? "SetLoginEmailAddressAsync");

           try
           {
             return client.SetLoginEmailAddressAsync(newLoginEmailAddress);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd