// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Sets the verbosity level of the internal logging of TDLib. Can be called synchronously
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> SetLogVerbosityLevelAsync(int newVerbosityLevel = default)
    {

           using var activity =  StartCallActivity("SetLogVerbosityLevelAsync", typeof(SetLogVerbosityLevel).FullName ?? "SetLogVerbosityLevelAsync");

           try
           {
             return client.SetLogVerbosityLevelAsync(newVerbosityLevel);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd