// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Changes the main profile tab of the current user
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> SetMainProfileTabAsync(ProfileTab mainProfileTab = default)
    {

           using var activity =  StartCallActivity("SetMainProfileTabAsync", typeof(SetMainProfileTab).FullName ?? "SetMainProfileTabAsync");

           try
           {
             return client.SetMainProfileTabAsync(mainProfileTab);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd