// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Changes the block list of a message sender. Currently, only users and supergroup chats can be blocked
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> SetMessageSenderBlockListAsync(MessageSender senderId = default, BlockList blockList = default)
    {

           using var activity =  StartCallActivity("SetMessageSenderBlockListAsync", typeof(SetMessageSenderBlockList).FullName ?? "SetMessageSenderBlockListAsync");

           try
           {
             return client.SetMessageSenderBlockListAsync(senderId, blockList);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd