// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Sets menu button for the given user or for all users; for bots only
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> SetMenuButtonAsync(long userId = default, BotMenuButton menuButton = default)
    {

           using var activity =  StartCallActivity("SetMenuButtonAsync", typeof(SetMenuButton).FullName ?? "SetMenuButtonAsync");

           try
           {
             return client.SetMenuButtonAsync(userId, menuButton);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd