// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Sets the current network type. Can be called before authorization. Calling this method forces all network connections to reopen, mitigating the delay in switching between different networks,
    /// so it must be called whenever the network is changed, even if the network type remains the same. Network type is used to check whether the library can use the network at all and also for collecting detailed network data usage statistics
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> SetNetworkTypeAsync(NetworkType type = default)
    {

           using var activity =  StartCallActivity("SetNetworkTypeAsync", typeof(SetNetworkType).FullName ?? "SetNetworkTypeAsync");

           try
           {
             return client.SetNetworkTypeAsync(type);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd