// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Changes a profile photo for the current user
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> SetProfilePhotoAsync(InputChatPhoto photo = default, bool isPublic = default)
    {

           using var activity =  StartCallActivity("SetProfilePhotoAsync", typeof(SetProfilePhoto).FullName ?? "SetProfilePhotoAsync");

           try
           {
             return client.SetProfilePhotoAsync(photo, isPublic);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd