// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Changes the order of pinned Saved Messages topics
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> SetPinnedSavedMessagesTopicsAsync(long[] savedMessagesTopicIds = default)
    {

           using var activity =  StartCallActivity("SetPinnedSavedMessagesTopicsAsync", typeof(SetPinnedSavedMessagesTopics).FullName ?? "SetPinnedSavedMessagesTopicsAsync");

           try
           {
             return client.SetPinnedSavedMessagesTopicsAsync(savedMessagesTopicIds);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd