// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Changes the personal chat of the current user
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> SetPersonalChatAsync(long chatId = default)
    {

           using var activity =  StartCallActivity("SetPersonalChatAsync", typeof(SetPersonalChat).FullName ?? "SetPersonalChatAsync");

           try
           {
             return client.SetPersonalChatAsync(chatId);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd