// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Changes the order of pinned chats
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> SetPinnedChatsAsync(ChatList chatList = default, long[] chatIds = default)
    {

           using var activity =  StartCallActivity("SetPinnedChatsAsync", typeof(SetPinnedChats).FullName ?? "SetPinnedChatsAsync");

           try
           {
             return client.SetPinnedChatsAsync(chatList, chatIds);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd