// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Changes the order of pinned topics in a forum supergroup chat or a chat with a bot with topics; requires can_manage_topics administrator right in the supergroup
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> SetPinnedForumTopicsAsync(long chatId = default, int[] forumTopicIds = default)
    {

           using var activity =  StartCallActivity("SetPinnedForumTopicsAsync", typeof(SetPinnedForumTopics).FullName ?? "SetPinnedForumTopicsAsync");

           try
           {
             return client.SetPinnedForumTopicsAsync(chatId, forumTopicIds);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd