// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Changes position of an audio file in the profile audio files of the current user
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> SetProfileAudioPositionAsync(int fileId = default, int afterFileId = default)
    {

           using var activity =  StartCallActivity("SetProfileAudioPositionAsync", typeof(SetProfileAudioPosition).FullName ?? "SetProfileAudioPositionAsync");

           try
           {
             return client.SetProfileAudioPositionAsync(fileId, afterFileId);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd