// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Changes the 2-step verification password for the current user. If a new recovery email address is specified, then the change will not be applied until the new recovery email address is confirmed
    /// </summary>
    public Task<TdLib.TdApi.Objects.PasswordState> SetPasswordAsync(string oldPassword = default, string newPassword = default, string newHint = default, bool setRecoveryEmailAddress = default, string newRecoveryEmailAddress = default)
    {

           using var activity =  StartCallActivity("SetPasswordAsync", typeof(SetPassword).FullName ?? "SetPasswordAsync");

           try
           {
             return client.SetPasswordAsync(oldPassword, newPassword, newHint, setRecoveryEmailAddress, newRecoveryEmailAddress);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd