// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Changes type of paid message reaction of the current user on a message. The message must have paid reaction added by the current user
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> SetPaidMessageReactionTypeAsync(long chatId = default, long messageId = default, PaidReactionType type = default)
    {

           using var activity =  StartCallActivity("SetPaidMessageReactionTypeAsync", typeof(SetPaidMessageReactionType).FullName ?? "SetPaidMessageReactionTypeAsync");

           try
           {
             return client.SetPaidMessageReactionTypeAsync(chatId, messageId, type);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd