// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Changes name of a quick reply shortcut
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> SetQuickReplyShortcutNameAsync(int shortcutId = default, string name = default)
    {

           using var activity =  StartCallActivity("SetQuickReplyShortcutNameAsync", typeof(SetQuickReplyShortcutName).FullName ?? "SetQuickReplyShortcutNameAsync");

           try
           {
             return client.SetQuickReplyShortcutNameAsync(shortcutId, name);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd