// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Changes privacy settings for message read date
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> SetReadDatePrivacySettingsAsync(ReadDatePrivacySettings settings = default)
    {

           using var activity =  StartCallActivity("SetReadDatePrivacySettingsAsync", typeof(SetReadDatePrivacySettings).FullName ?? "SetReadDatePrivacySettingsAsync");

           try
           {
             return client.SetReadDatePrivacySettingsAsync(settings);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd