// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Changes notification settings for reactions
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> SetReactionNotificationSettingsAsync(ReactionNotificationSettings notificationSettings = default)
    {

           using var activity =  StartCallActivity("SetReactionNotificationSettingsAsync", typeof(SetReactionNotificationSettings).FullName ?? "SetReactionNotificationSettingsAsync");

           try
           {
             return client.SetReactionNotificationSettingsAsync(notificationSettings);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd