// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Changes the sticker set of a supergroup; requires can_change_info administrator right
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> SetSupergroupStickerSetAsync(long supergroupId = default, long stickerSetId = default)
    {

           using var activity =  StartCallActivity("SetSupergroupStickerSetAsync", typeof(SetSupergroupStickerSet).FullName ?? "SetSupergroupStickerSetAsync");

           try
           {
             return client.SetSupergroupStickerSetAsync(supergroupId, stickerSetId);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd