// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Sets a sticker set title
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> SetStickerSetTitleAsync(string name = default, string title = default)
    {

           using var activity =  StartCallActivity("SetStickerSetTitleAsync", typeof(SetStickerSetTitle).FullName ?? "SetStickerSetTitleAsync");

           try
           {
             return client.SetStickerSetTitleAsync(name, title);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd