// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Changes chosen reaction on a story that has already been sent; not supported for live stories
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> SetStoryReactionAsync(long storyPosterChatId = default, int storyId = default, ReactionType reactionType = default, bool updateRecentReactions = default)
    {

           using var activity =  StartCallActivity("SetStoryReactionAsync", typeof(SetStoryReaction).FullName ?? "SetStoryReactionAsync");

           try
           {
             return client.SetStoryReactionAsync(storyPosterChatId, storyId, reactionType, updateRecentReactions);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd