// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Changes label of a Saved Messages tag; for Telegram Premium users only
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> SetSavedMessagesTagLabelAsync(ReactionType tag = default, string label = default)
    {

           using var activity =  StartCallActivity("SetSavedMessagesTagLabelAsync", typeof(SetSavedMessagesTagLabel).FullName ?? "SetSavedMessagesTagLabelAsync");

           try
           {
             return client.SetSavedMessagesTagLabelAsync(tag, label);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd