// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Changes notification settings for chats of a given type
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> SetScopeNotificationSettingsAsync(NotificationSettingsScope scope = default, ScopeNotificationSettings notificationSettings = default)
    {

           using var activity =  StartCallActivity("SetScopeNotificationSettingsAsync", typeof(SetScopeNotificationSettings).FullName ?? "SetScopeNotificationSettingsAsync");

           try
           {
             return client.SetScopeNotificationSettingsAsync(scope, notificationSettings);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd