// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Changes the custom emoji sticker set of a supergroup; requires can_change_info administrator right. The chat must have at least chatBoostFeatures.min_custom_emoji_sticker_set_boost_level boost level to pass the corresponding color
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> SetSupergroupCustomEmojiStickerSetAsync(long supergroupId = default, long customEmojiStickerSetId = default)
    {

           using var activity =  StartCallActivity("SetSupergroupCustomEmojiStickerSetAsync", typeof(SetSupergroupCustomEmojiStickerSet).FullName ?? "SetSupergroupCustomEmojiStickerSetAsync");

           try
           {
             return client.SetSupergroupCustomEmojiStickerSetAsync(supergroupId, customEmojiStickerSetId);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd