// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Changes privacy settings of a story. The method can be called only for stories posted on behalf of the current user and if story.can_set_privacy_settings == true
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> SetStoryPrivacySettingsAsync(int storyId = default, StoryPrivacySettings privacySettings = default)
    {

           using var activity =  StartCallActivity("SetStoryPrivacySettingsAsync", typeof(SetStoryPrivacySettings).FullName ?? "SetStoryPrivacySettingsAsync");

           try
           {
             return client.SetStoryPrivacySettingsAsync(storyId, privacySettings);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd