// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Changes the editable username of a supergroup or channel, requires owner privileges in the supergroup or channel
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> SetSupergroupUsernameAsync(long supergroupId = default, string username = default)
    {

           using var activity =  StartCallActivity("SetSupergroupUsernameAsync", typeof(SetSupergroupUsername).FullName ?? "SetSupergroupUsernameAsync");

           try
           {
             return client.SetSupergroupUsernameAsync(supergroupId, username);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd