// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Changes color scheme for the current user based on an owned or a hosted upgraded gift; for Telegram Premium users only
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> SetUpgradedGiftColorsAsync(long upgradedGiftColorsId = default)
    {

           using var activity =  StartCallActivity("SetUpgradedGiftColorsAsync", typeof(SetUpgradedGiftColors).FullName ?? "SetUpgradedGiftColorsAsync");

           try
           {
             return client.SetUpgradedGiftColorsAsync(upgradedGiftColorsId);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd