// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Changes user privacy settings
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> SetUserPrivacySettingRulesAsync(UserPrivacySetting setting = default, UserPrivacySettingRules rules = default)
    {

           using var activity =  StartCallActivity("SetUserPrivacySettingRulesAsync", typeof(SetUserPrivacySettingRules).FullName ?? "SetUserPrivacySettingRulesAsync");

           try
           {
             return client.SetUserPrivacySettingRulesAsync(setting, rules);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd