// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Changes the editable username of the current user
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> SetUsernameAsync(string username = default)
    {

           using var activity =  StartCallActivity("SetUsernameAsync", typeof(SetUsername).FullName ?? "SetUsernameAsync");

           try
           {
             return client.SetUsernameAsync(username);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd