// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Sets support information for the given user; for Telegram support only
    /// </summary>
    public Task<TdLib.TdApi.Objects.UserSupportInfo> SetUserSupportInfoAsync(long userId = default, FormattedText message = default)
    {

           using var activity =  StartCallActivity("SetUserSupportInfoAsync", typeof(SetUserSupportInfo).FullName ?? "SetUserSupportInfoAsync");

           try
           {
             return client.SetUserSupportInfoAsync(userId, message);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd