// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Sets title of a video chat; requires groupCall.can_be_managed right
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> SetVideoChatTitleAsync(int groupCallId = default, string title = default)
    {

           using var activity =  StartCallActivity("SetVideoChatTitleAsync", typeof(SetVideoChatTitle).FullName ?? "SetVideoChatTitleAsync");

           try
           {
             return client.SetVideoChatTitleAsync(groupCallId, title);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd