// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Changes default participant identifier, on whose behalf a video chat in the chat will be joined
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> SetVideoChatDefaultParticipantAsync(long chatId = default, MessageSender defaultParticipantId = default)
    {

           using var activity =  StartCallActivity("SetVideoChatDefaultParticipantAsync", typeof(SetVideoChatDefaultParticipant).FullName ?? "SetVideoChatDefaultParticipantAsync");

           try
           {
             return client.SetVideoChatDefaultParticipantAsync(chatId, defaultParticipantId);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd