// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Shares a chat after pressing a keyboardButtonTypeRequestChat button with the bot
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> ShareChatWithBotAsync(long chatId = default, long messageId = default, int buttonId = default, long sharedChatId = default, bool onlyCheck = default)
    {

           using var activity =  StartCallActivity("ShareChatWithBotAsync", typeof(ShareChatWithBot).FullName ?? "ShareChatWithBotAsync");

           try
           {
             return client.ShareChatWithBotAsync(chatId, messageId, buttonId, sharedChatId, onlyCheck);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd