// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Starts a scheduled video chat
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> StartScheduledVideoChatAsync(int groupCallId = default)
    {

           using var activity =  StartCallActivity("StartScheduledVideoChatAsync", typeof(StartScheduledVideoChat).FullName ?? "StartScheduledVideoChatAsync");

           try
           {
             return client.StartScheduledVideoChatAsync(groupCallId);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd