// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Summarizes content of the message with non-empty summary_language_code
    /// </summary>
    public Task<TdLib.TdApi.Objects.FormattedText> SummarizeMessageAsync(long chatId = default, long messageId = default, string translateToLanguageCode = default)
    {

           using var activity =  StartCallActivity("SummarizeMessageAsync", typeof(SummarizeMessage).FullName ?? "SummarizeMessageAsync");

           try
           {
             return client.SummarizeMessageAsync(chatId, messageId, translateToLanguageCode);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd