// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Fetches the latest versions of all strings from a language pack in the current localization target from the server.
    /// This method doesn't need to be called explicitly for the current used/base language packs. Can be called before authorization
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> SynchronizeLanguagePackAsync(string languagePackId = default)
    {

           using var activity =  StartCallActivity("SynchronizeLanguagePackAsync", typeof(SynchronizeLanguagePack).FullName ?? "SynchronizeLanguagePackAsync");

           try
           {
             return client.SynchronizeLanguagePackAsync(languagePackId);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd