// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Terminates a session of the current user
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> TerminateSessionAsync(long sessionId = default)
    {

           using var activity =  StartCallActivity("TerminateSessionAsync", typeof(TerminateSession).FullName ?? "TerminateSessionAsync");

           try
           {
             return client.TerminateSessionAsync(sessionId);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd