// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Sends a simple network request to the Telegram servers via proxy; for testing only. Can be called before authorization
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> TestProxyAsync(Proxy proxy = default, int dcId = default, double? timeout = default)
    {

           using var activity =  StartCallActivity("TestProxyAsync", typeof(TestProxy).FullName ?? "TestProxyAsync");

           try
           {
             return client.TestProxyAsync(proxy, dcId, timeout);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd