// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns the received vector of strings; for testing only. This is an offline method. Can be called before authorization
    /// </summary>
    public Task<TdLib.TdApi.Objects.TestVectorString> TestCallVectorStringAsync(string[] x = default)
    {

           using var activity =  StartCallActivity("TestCallVectorStringAsync", typeof(TestCallVectorString).FullName ?? "TestCallVectorStringAsync");

           try
           {
             return client.TestCallVectorStringAsync(x);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd