// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns the specified error and ensures that the Error object is used; for testing only. Can be called synchronously
    /// </summary>
    public Task<TdLib.TdApi.Objects.Error> TestReturnErrorAsync(Error error = default)
    {

           using var activity =  StartCallActivity("TestReturnErrorAsync", typeof(TestReturnError).FullName ?? "TestReturnErrorAsync");

           try
           {
             return client.TestReturnErrorAsync(error);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd