// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Forces an updates.getDifference call to the Telegram servers; for testing only
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> TestGetDifferenceAsync()
    {

           using var activity =  StartCallActivity("TestGetDifferenceAsync", typeof(TestGetDifference).FullName ?? "TestGetDifferenceAsync");

           try
           {
             return client.TestGetDifferenceAsync();
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd