// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns the received vector of objects containing a string; for testing only. This is an offline method. Can be called before authorization
    /// </summary>
    public Task<TdLib.TdApi.Objects.TestVectorStringObject> TestCallVectorStringObjectAsync(TestString[] x = default)
    {

           using var activity =  StartCallActivity("TestCallVectorStringObjectAsync", typeof(TestCallVectorStringObject).FullName ?? "TestCallVectorStringObjectAsync");

           try
           {
             return client.TestCallVectorStringObjectAsync(x);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd