// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns the received string; for testing only. This is an offline method. Can be called before authorization
    /// </summary>
    public Task<TdLib.TdApi.Objects.TestString> TestCallStringAsync(string x = default)
    {

           using var activity =  StartCallActivity("TestCallStringAsync", typeof(TestCallString).FullName ?? "TestCallStringAsync");

           try
           {
             return client.TestCallStringAsync(x);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd