// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Returns the squared received number; for testing only. This is an offline method. Can be called before authorization
    /// </summary>
    public Task<TdLib.TdApi.Objects.TestInt> TestSquareIntAsync(int x = default)
    {

           using var activity =  StartCallActivity("TestSquareIntAsync", typeof(TestSquareInt).FullName ?? "TestSquareIntAsync");

           try
           {
             return client.TestSquareIntAsync(x);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd