// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Pauses or unpauses screen sharing in a joined group call; not supported in live stories
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> ToggleGroupCallScreenSharingIsPausedAsync(int groupCallId = default, bool isPaused = default)
    {

           using var activity =  StartCallActivity("ToggleGroupCallScreenSharingIsPausedAsync", typeof(ToggleGroupCallScreenSharingIsPaused).FullName ?? "ToggleGroupCallScreenSharingIsPausedAsync");

           try
           {
             return client.ToggleGroupCallScreenSharingIsPausedAsync(groupCallId, isPaused);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd