// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Changes the marked as unread state of a chat
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> ToggleChatIsMarkedAsUnreadAsync(long chatId = default, bool isMarkedAsUnread = default)
    {

           using var activity =  StartCallActivity("ToggleChatIsMarkedAsUnreadAsync", typeof(ToggleChatIsMarkedAsUnread).FullName ?? "ToggleChatIsMarkedAsUnreadAsync");

           try
           {
             return client.ToggleChatIsMarkedAsUnreadAsync(chatId, isMarkedAsUnread);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd