// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Toggles whether notifications for new gifts received by a channel chat are sent to the current user; requires can_post_messages administrator right in the chat
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> ToggleChatGiftNotificationsAsync(long chatId = default, bool areEnabled = default)
    {

           using var activity =  StartCallActivity("ToggleChatGiftNotificationsAsync", typeof(ToggleChatGiftNotifications).FullName ?? "ToggleChatGiftNotificationsAsync");

           try
           {
             return client.ToggleChatGiftNotificationsAsync(chatId, areEnabled);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd