// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Changes the translatable state of a chat
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> ToggleChatIsTranslatableAsync(long chatId = default, bool isTranslatable = default)
    {

           using var activity =  StartCallActivity("ToggleChatIsTranslatableAsync", typeof(ToggleChatIsTranslatable).FullName ?? "ToggleChatIsTranslatableAsync");

           try
           {
             return client.ToggleChatIsTranslatableAsync(chatId, isTranslatable);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd