// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Toggles whether new participants of a video chat can be unmuted only by administrators of the video chat. Requires groupCall.can_toggle_mute_new_participants right
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> ToggleVideoChatMuteNewParticipantsAsync(int groupCallId = default, bool muteNewParticipants = default)
    {

           using var activity =  StartCallActivity("ToggleVideoChatMuteNewParticipantsAsync", typeof(ToggleVideoChatMuteNewParticipants).FullName ?? "ToggleVideoChatMuteNewParticipantsAsync");

           try
           {
             return client.ToggleVideoChatMuteNewParticipantsAsync(groupCallId, muteNewParticipants);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd