// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Changes the pinned state of a topic in a forum supergroup chat or a chat with a bot with topics; requires can_manage_topics administrator right in the supergroup.
    /// There can be up to getOption("pinned_forum_topic_count_max") pinned forum topics
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> ToggleForumTopicIsPinnedAsync(long chatId = default, int forumTopicId = default, bool isPinned = default)
    {

           using var activity =  StartCallActivity("ToggleForumTopicIsPinnedAsync", typeof(ToggleForumTopicIsPinned).FullName ?? "ToggleForumTopicIsPinnedAsync");

           try
           {
             return client.ToggleForumTopicIsPinnedAsync(chatId, forumTopicId, isPinned);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd