// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Changes active state for a username of a bot. The editable username can be disabled only if there are other active usernames.
    /// May return an error with a message "USERNAMES_ACTIVE_TOO_MUCH" if the maximum number of active usernames has been reached. Can be called only if userTypeBot.can_be_edited == true
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> ToggleBotUsernameIsActiveAsync(long botUserId = default, string username = default, bool isActive = default)
    {

           using var activity =  StartCallActivity("ToggleBotUsernameIsActiveAsync", typeof(ToggleBotUsernameIsActive).FullName ?? "ToggleBotUsernameIsActiveAsync");

           try
           {
             return client.ToggleBotUsernameIsActiveAsync(botUserId, username, isActive);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd