// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Toggles whether current user's video is enabled
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> ToggleGroupCallIsMyVideoEnabledAsync(int groupCallId = default, bool isMyVideoEnabled = default)
    {

           using var activity =  StartCallActivity("ToggleGroupCallIsMyVideoEnabledAsync", typeof(ToggleGroupCallIsMyVideoEnabled).FullName ?? "ToggleGroupCallIsMyVideoEnabledAsync");

           try
           {
             return client.ToggleGroupCallIsMyVideoEnabledAsync(groupCallId, isMyVideoEnabled);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd