// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Toggles whether aggressive anti-spam checks are enabled in the supergroup. Can be called only if supergroupFullInfo.can_toggle_aggressive_anti_spam == true
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> ToggleSupergroupHasAggressiveAntiSpamEnabledAsync(long supergroupId = default, bool hasAggressiveAntiSpamEnabled = default)
    {

           using var activity =  StartCallActivity("ToggleSupergroupHasAggressiveAntiSpamEnabledAsync", typeof(ToggleSupergroupHasAggressiveAntiSpamEnabled).FullName ?? "ToggleSupergroupHasAggressiveAntiSpamEnabledAsync");

           try
           {
             return client.ToggleSupergroupHasAggressiveAntiSpamEnabledAsync(supergroupId, hasAggressiveAntiSpamEnabled);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd