// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Toggles whether a session can accept incoming calls
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> ToggleSessionCanAcceptCallsAsync(long sessionId = default, bool canAcceptCalls = default)
    {

           using var activity =  StartCallActivity("ToggleSessionCanAcceptCallsAsync", typeof(ToggleSessionCanAcceptCalls).FullName ?? "ToggleSessionCanAcceptCallsAsync");

           try
           {
             return client.ToggleSessionCanAcceptCallsAsync(sessionId, canAcceptCalls);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd