// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Changes the pinned state of a Saved Messages topic. There can be up to getOption("pinned_saved_messages_topic_count_max") pinned topics. The limit can be increased with Telegram Premium
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> ToggleSavedMessagesTopicIsPinnedAsync(long savedMessagesTopicId = default, bool isPinned = default)
    {

           using var activity =  StartCallActivity("ToggleSavedMessagesTopicIsPinnedAsync", typeof(ToggleSavedMessagesTopicIsPinned).FullName ?? "ToggleSavedMessagesTopicIsPinnedAsync");

           try
           {
             return client.ToggleSavedMessagesTopicIsPinnedAsync(savedMessagesTopicId, isPinned);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd