// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Toggles whether all users directly joining the supergroup need to be approved by supergroup administrators; requires can_restrict_members administrator right
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> ToggleSupergroupJoinByRequestAsync(long supergroupId = default, bool joinByRequest = default)
    {

           using var activity =  StartCallActivity("ToggleSupergroupJoinByRequestAsync", typeof(ToggleSupergroupJoinByRequest).FullName ?? "ToggleSupergroupJoinByRequestAsync");

           try
           {
             return client.ToggleSupergroupJoinByRequestAsync(supergroupId, joinByRequest);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd