// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Toggles whether the bot can manage emoji status of the current user
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> ToggleBotCanManageEmojiStatusAsync(long botUserId = default, bool canManageEmojiStatus = default)
    {

           using var activity =  StartCallActivity("ToggleBotCanManageEmojiStatusAsync", typeof(ToggleBotCanManageEmojiStatus).FullName ?? "ToggleBotCanManageEmojiStatusAsync");

           try
           {
             return client.ToggleBotCanManageEmojiStatusAsync(botUserId, canManageEmojiStatus);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd