// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Toggles whether participants of a group call can send messages there. Requires groupCall.can_toggle_are_messages_allowed right
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> ToggleGroupCallAreMessagesAllowedAsync(int groupCallId = default, bool areMessagesAllowed = default)
    {

           using var activity =  StartCallActivity("ToggleGroupCallAreMessagesAllowedAsync", typeof(ToggleGroupCallAreMessagesAllowed).FullName ?? "ToggleGroupCallAreMessagesAllowedAsync");

           try
           {
             return client.ToggleGroupCallAreMessagesAllowedAsync(groupCallId, areMessagesAllowed);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd