// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Changes the ability of users to save, forward, or copy chat content. Requires owner privileges in basic groups, supergroups and channels.
    /// Requires Telegram Premium to enable protected content in private chats. Not available in Saved Messages and private chats with bots or support accounts
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> ToggleChatHasProtectedContentAsync(long chatId = default, bool hasProtectedContent = default)
    {

           using var activity =  StartCallActivity("ToggleChatHasProtectedContentAsync", typeof(ToggleChatHasProtectedContent).FullName ?? "ToggleChatHasProtectedContentAsync");

           try
           {
             return client.ToggleChatHasProtectedContentAsync(chatId, hasProtectedContent);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd