// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Toggles whether current user's video is paused
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> ToggleGroupCallIsMyVideoPausedAsync(int groupCallId = default, bool isMyVideoPaused = default)
    {

           using var activity =  StartCallActivity("ToggleGroupCallIsMyVideoPausedAsync", typeof(ToggleGroupCallIsMyVideoPaused).FullName ?? "ToggleGroupCallIsMyVideoPausedAsync");

           try
           {
             return client.ToggleGroupCallIsMyVideoPausedAsync(groupCallId, isMyVideoPaused);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd