// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Toggles whether a story is accessible after expiration. Can be called only if story.can_toggle_is_posted_to_chat_page == true
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> ToggleStoryIsPostedToChatPageAsync(long storyPosterChatId = default, int storyId = default, bool isPostedToChatPage = default)
    {

           using var activity =  StartCallActivity("ToggleStoryIsPostedToChatPageAsync", typeof(ToggleStoryIsPostedToChatPage).FullName ?? "ToggleStoryIsPostedToChatPageAsync");

           try
           {
             return client.ToggleStoryIsPostedToChatPageAsync(storyPosterChatId, storyId, isPostedToChatPage);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd