// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Changes the view_as_topics setting of a forum chat or Saved Messages
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> ToggleChatViewAsTopicsAsync(long chatId = default, bool viewAsTopics = default)
    {

           using var activity =  StartCallActivity("ToggleChatViewAsTopicsAsync", typeof(ToggleChatViewAsTopics).FullName ?? "ToggleChatViewAsTopicsAsync");

           try
           {
             return client.ToggleChatViewAsTopicsAsync(chatId, viewAsTopics);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd