// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Toggles whether messages are automatically translated in the channel chat; requires can_change_info administrator right in the channel.
    /// The chat must have at least chatBoostFeatures.min_automatic_translation_boost_level boost level to enable automatic translation
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> ToggleSupergroupHasAutomaticTranslationAsync(long supergroupId = default, bool hasAutomaticTranslation = default)
    {

           using var activity =  StartCallActivity("ToggleSupergroupHasAutomaticTranslationAsync", typeof(ToggleSupergroupHasAutomaticTranslation).FullName ?? "ToggleSupergroupHasAutomaticTranslationAsync");

           try
           {
             return client.ToggleSupergroupHasAutomaticTranslationAsync(supergroupId, hasAutomaticTranslation);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd