// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Toggles whether chat folder tags are enabled
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> ToggleChatFolderTagsAsync(bool areTagsEnabled = default)
    {

           using var activity =  StartCallActivity("ToggleChatFolderTagsAsync", typeof(ToggleChatFolderTags).FullName ?? "ToggleChatFolderTagsAsync");

           try
           {
             return client.ToggleChatFolderTagsAsync(areTagsEnabled);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd