// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Allows to send unpaid messages to the given topic of the channel direct messages chat administered by the current user
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> ToggleDirectMessagesChatTopicCanSendUnpaidMessagesAsync(long chatId = default, long topicId = default, bool canSendUnpaidMessages = default, bool refundPayments = default)
    {

           using var activity =  StartCallActivity("ToggleDirectMessagesChatTopicCanSendUnpaidMessagesAsync", typeof(ToggleDirectMessagesChatTopicCanSendUnpaidMessages).FullName ?? "ToggleDirectMessagesChatTopicCanSendUnpaidMessagesAsync");

           try
           {
             return client.ToggleDirectMessagesChatTopicCanSendUnpaidMessagesAsync(chatId, topicId, canSendUnpaidMessages, refundPayments);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd