// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Changes pause state of all files in the file download list
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> ToggleAllDownloadsArePausedAsync(bool arePaused = default)
    {

           using var activity =  StartCallActivity("ToggleAllDownloadsArePausedAsync", typeof(ToggleAllDownloadsArePaused).FullName ?? "ToggleAllDownloadsArePausedAsync");

           try
           {
             return client.ToggleAllDownloadsArePausedAsync(arePaused);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd