// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Toggles whether the current user will receive a notification when the video chat starts; for scheduled video chats only
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> ToggleVideoChatEnabledStartNotificationAsync(int groupCallId = default, bool enabledStartNotification = default)
    {

           using var activity =  StartCallActivity("ToggleVideoChatEnabledStartNotificationAsync", typeof(ToggleVideoChatEnabledStartNotification).FullName ?? "ToggleVideoChatEnabledStartNotificationAsync");

           try
           {
             return client.ToggleVideoChatEnabledStartNotificationAsync(groupCallId, enabledStartNotification);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd