// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Changes the pinned state of a chat. There can be up to getOption("pinned_chat_count_max")/getOption("pinned_archived_chat_count_max") pinned non-secret chats and the same number of secret chats in the main/archive chat list. The limit can be increased with Telegram Premium
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> ToggleChatIsPinnedAsync(ChatList chatList = default, long chatId = default, bool isPinned = default)
    {

           using var activity =  StartCallActivity("ToggleChatIsPinnedAsync", typeof(ToggleChatIsPinned).FullName ?? "ToggleChatIsPinnedAsync");

           try
           {
             return client.ToggleChatIsPinnedAsync(chatList, chatId, isPinned);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd