// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Changes the owner of a chat; for basic groups, supergroups and channel chats only; requires owner privileges in the chat. Use the method canTransferOwnership to check whether the ownership can be transferred from the current session
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> TransferChatOwnershipAsync(long chatId = default, long userId = default, string password = default)
    {

           using var activity =  StartCallActivity("TransferChatOwnershipAsync", typeof(TransferChatOwnership).FullName ?? "TransferChatOwnershipAsync");

           try
           {
             return client.TransferChatOwnershipAsync(chatId, userId, password);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd