// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Translates a text to the given language. If the current user is a Telegram Premium user, then text formatting is preserved
    /// </summary>
    public Task<TdLib.TdApi.Objects.FormattedText> TranslateTextAsync(FormattedText text = default, string toLanguageCode = default)
    {

           using var activity =  StartCallActivity("TranslateTextAsync", typeof(TranslateText).FullName ?? "TranslateTextAsync");

           try
           {
             return client.TranslateTextAsync(text, toLanguageCode);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd