// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Removes a pinned message from a chat; requires can_pin_messages member right if the chat is a basic group or supergroup, or can_edit_messages administrator right if the chat is a channel
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> UnpinChatMessageAsync(long chatId = default, long messageId = default)
    {

           using var activity =  StartCallActivity("UnpinChatMessageAsync", typeof(UnpinChatMessage).FullName ?? "UnpinChatMessageAsync");

           try
           {
             return client.UnpinChatMessageAsync(chatId, messageId);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd