// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Removes all pinned messages from a chat; requires can_pin_messages member right if the chat is a basic group or supergroup, or can_edit_messages administrator right if the chat is a channel
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> UnpinAllChatMessagesAsync(long chatId = default)
    {

           using var activity =  StartCallActivity("UnpinAllChatMessagesAsync", typeof(UnpinAllChatMessages).FullName ?? "UnpinAllChatMessagesAsync");

           try
           {
             return client.UnpinAllChatMessagesAsync(chatId);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd