// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Uploads a file with a sticker; returns the uploaded file
    /// </summary>
    public Task<TdLib.TdApi.Objects.File> UploadStickerFileAsync(long userId = default, StickerFormat stickerFormat = default, InputFile sticker = default)
    {

           using var activity =  StartCallActivity("UploadStickerFileAsync", typeof(UploadStickerFile).FullName ?? "UploadStickerFileAsync");

           try
           {
             return client.UploadStickerFileAsync(userId, stickerFormat, sticker);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd