// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Validates the order information provided by a user and returns the available shipping options for a flexible invoice
    /// </summary>
    public Task<TdLib.TdApi.Objects.ValidatedOrderInfo> ValidateOrderInfoAsync(InputInvoice inputInvoice = default, OrderInfo orderInfo = default, bool allowSave = default)
    {

           using var activity =  StartCallActivity("ValidateOrderInfoAsync", typeof(ValidateOrderInfo).FullName ?? "ValidateOrderInfoAsync");

           try
           {
             return client.ValidateOrderInfoAsync(inputInvoice, orderInfo, allowSave);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd