// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Informs TDLib that the user fully viewed a sponsored chat
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> ViewSponsoredChatAsync(long sponsoredChatUniqueId = default)
    {

           using var activity =  StartCallActivity("ViewSponsoredChatAsync", typeof(ViewSponsoredChat).FullName ?? "ViewSponsoredChatAsync");

           try
           {
             return client.ViewSponsoredChatAsync(sponsoredChatUniqueId);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd