// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Informs the server that some trending sticker sets have been viewed by the user
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> ViewTrendingStickerSetsAsync(long[] stickerSetIds = default)
    {

           using var activity =  StartCallActivity("ViewTrendingStickerSetsAsync", typeof(ViewTrendingStickerSets).FullName ?? "ViewTrendingStickerSetsAsync");

           try
           {
             return client.ViewTrendingStickerSetsAsync(stickerSetIds);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd