// REUSE-IgnoreStart

using TdLib.TdApi;
using TdLib.TdApi.Objects;
namespace TdLib.Api.OpenTelemetry;
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>

public partial class ClientOpenTelemetryDecorator
{
    /// <summary>
    /// Writes a part of a generated file. This method is intended to be used only if the application has no direct access to TDLib's file system, because it is usually slower than a direct write to the destination file
    /// </summary>
    public Task<TdLib.TdApi.Objects.Ok> WriteGeneratedFilePartAsync(long generationId = default, long offset = default, byte[] data = default)
    {

           using var activity =  StartCallActivity("WriteGeneratedFilePartAsync", typeof(WriteGeneratedFilePart).FullName ?? "WriteGeneratedFilePartAsync");

           try
           {
             return client.WriteGeneratedFilePartAsync(generationId, offset, data);
           }
           catch (Exception ex)
           {
               MarkAsError(activity, ex);
               throw;
           }
    }
}
// REUSE-IgnoreEnd