using System;
using System.Threading.Tasks;
using Newtonsoft.Json;
using TdLib.TdApi.Objects;
// REUSE-IgnoreStart

namespace TdLib.TdApi;
/// <summary>
/// Returns available options for Telegram Star giveaway creation
/// </summary>
public class GetStarGiveawayPaymentOptions : Function<StarGiveawayPaymentOptions>
{
    /// <summary>
    /// Data type for serialization
    /// </summary>
    [JsonProperty("@type")]
    public override string DataType { get; set; } = "getStarGiveawayPaymentOptions";

    /// <summary>
    /// Extra data attached to the function
    /// </summary>
    [JsonProperty("@extra")]
    public override string Extra { get; set; }


}
/// <summary>
/// Autogenerated TDLib APIs
/// </summary>
public partial class StarGiveawayPaymentOptionsClient : BaseClient
{
    /// <summary>
    /// Returns available options for Telegram Star giveaway creation
    /// </summary>
    public Task<StarGiveawayPaymentOptions> GetStarGiveawayPaymentOptionsAsync()
    {
    //test
        return ExecuteAsync(new GetStarGiveawayPaymentOptions
        {
            
        });
    }
}
public partial interface IStarGiveawayPaymentOptionsClient
{
    /// <summary>
    /// Returns available options for Telegram Star giveaway creation
    /// </summary>
    Task<StarGiveawayPaymentOptions> GetStarGiveawayPaymentOptionsAsync();
}


// REUSE-IgnoreEnd